# Generated by Django 2.2.6 on 2020-12-28 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAthosGr2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaAthosGr2020', to='menu.AlmacenesAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferesGr2020', to='menu.ChoferesVehiculos')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosEmpGr2020', to='menu.DatosEmpresa')),
                ('anexo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculosGr2020', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuiaGr2020', to='menu.ejezona')),
                ('ubic_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaLLGr2020', to='menu.LugarAthos')),
                ('ubic_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaPGr2020', to='menu.LugarAthos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuiaGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Athos-GRANADA 2020',
                'verbose_name_plural': 'Guias Athos-GRANADA 2020',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthosGr2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadMGr2020', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosGr2020', to='granada.GuiaAthosGr2020')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioGr2020', to='menu.MaterialAcopio')),
                ('anexo_ubi_mmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundoAthosGr2020Athos', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaDGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos-Granada 2020',
                'verbose_name_plural': 'Guias  Detalles Athos- Granada 2020',
            },
        ),
        migrations.CreateModel(
            name='InfoPalet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacenGr2020', to='menu.AlmacenesAthos')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosGr2020', to='granada.GuiaDetallesAthosGr2020')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuelaGr2020', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPaletsGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPaletsGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet-GRANADA 2020',
                'verbose_name_plural': 'Info Palets-GRANADA 2020',
            },
        ),
    ]
