# Generated by Django 2.2.6 on 2020-12-28 00:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoPalet',
            new_name='InfoPaletGr2020',
        ),
    ]
