# Generated by Django 2.2.6 on 2020-12-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0159_materialacopio_anexo_cultivo'),
        ('granada', '0002_auto_20201228_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaathosgr2020',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoGuiaGr2020', to='menu.fundo'),
        ),
    ]
