# Generated by Django 2.2.6 on 2021-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0003_guiaathosgr2020_anexo_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaathosgr2020',
            name='nroprecinto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
