# Generated by Django 2.2.6 on 2021-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0004_guiaathosgr2020_nroprecinto'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaathosgr2020',
            name='nroprecinto1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
