# Generated by Django 2.2.6 on 2021-01-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0005_guiaathosgr2020_nroprecinto1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaathosgr2020',
            name='nroprecinto1',
        ),
    ]
