# Generated by Django 2.2.6 on 2021-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granada', '0006_remove_guiaathosgr2020_nroprecinto1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenAcopioGr2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo Qr')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionAlmacenAcopioGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionnAlmacenAcopioGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Almacen Acopio-GRANADA 2020',
                'verbose_name_plural': 'Almacen Acopio-GRANADA 2020',
            },
        ),
    ]
