# Generated by Django 2.2.6 on 2021-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0007_almacenacopiogr2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenacopiogr2020',
            name='codigoqr',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Codigo Qr'),
        ),
    ]
