# Generated by Django 2.2.6 on 2021-12-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0184_auto_20211021_1332'),
        ('granada', '0008_auto_20210603_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalidaDescarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Salida Descarte')),
            ],
            options={
                'verbose_name': 'Tipo Salidad Descarte',
                'verbose_name_plural': 'Tipo Salida Descarte',
            },
        ),
        migrations.CreateModel(
            name='SalidaDescarteGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nroguia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro Guia')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoSalidaDescarteGrIca2021', to='menu.cultivo')),
                ('anexo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeSalidaDescarteGrIca2021', to='menu.ejezona')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoSalidaDescarteGrIca2021', to='granada.TipoSalidaDescarte')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionSalidaDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModSalidaDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Descarte-Gr Ica 2021',
                'verbose_name_plural': 'Salida Descarte- Gr Ica 2021',
            },
        ),
        migrations.CreateModel(
            name='DescarteAthosGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.IntegerField(blank=True, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_lanzado', models.DateField(verbose_name='Fecha Lanzado')),
                ('peso_descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('merma_maquina', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('merma_proceso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('merma_recepcion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descarte_mini', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recuperable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('norecuperable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteEjeGrIca2021', to='menu.ejezona')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteFundoGrIca2021', to='menu.fundo')),
                ('anexo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteMMPPGrIca2021', to='menu.MaterialMMPP')),
                ('anexo_nave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteNaveGrIca2021', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescartePlantaGrIca2021', to='menu.Planta')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteTurnoGrIca2021', to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarte Planta Athos-Gr Ica 2021',
                'verbose_name_plural': 'Descarte Planta Athos-Gr Ica 2021',
            },
        ),
    ]
