# Generated by Django 2.2.6 on 2021-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0009_descarteathosgrica2021_salidadescartegrica2021_tiposalidadescarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha'),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='trazabilidad',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Trazabilidad'),
        ),
    ]
