# Generated by Django 2.2.6 on 2021-12-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0011_detallesalidadescartegrica2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCalidadFruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Calidad Fruta')),
            ],
            options={
                'verbose_name': 'Tipo  Calidad de fruta',
                'verbose_name_plural': 'Tipo Calidad de fruta',
            },
        ),
    ]
