# Generated by Django 2.2.6 on 2021-12-22 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0184_auto_20211021_1332'),
        ('granada', '0012_tipocalidadfruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAthosGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('nroprecinto', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaAthosGrIca2021', to='menu.AlmacenesAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferesGrIca2021', to='menu.ChoferesVehiculos')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoGuiaGrIca2021', to='menu.fundo')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosEmpGrIca2021', to='menu.DatosEmpresa')),
                ('anexo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculosGrIca2021', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuiaGrIca2021', to='menu.ejezona')),
                ('ubic_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaLLGrIca2021', to='menu.LugarAthos')),
                ('ubic_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaPGrIca2021', to='menu.LugarAthos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuiaGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Athos-GRANADA 2021',
                'verbose_name_plural': 'Guias Athos-GRANADA 2021',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthosGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadMGrIca2021', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosGrIca2021', to='granada.GuiaAthosGrIca2021')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioGrIca2021', to='menu.MaterialAcopio')),
                ('anexo_ubi_mmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundoAthosGrIca2021', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaDGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos-Granada 2021',
                'verbose_name_plural': 'Guias  Detalles Athos- Granada 2021',
            },
        ),
        migrations.CreateModel(
            name='InfoPaletGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacenGrIca2021', to='menu.AlmacenesAthos')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosGrIca2021', to='granada.GuiaDetallesAthosGrIca2021')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuelaGrIca2021', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPaletsGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPaletsGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet-GRANADA ICA 2021',
                'verbose_name_plural': 'Info Palets-GRANADA ICA 2021',
            },
        ),
        migrations.CreateModel(
            name='AlmacenAcopioGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Codigo Qr')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionAlmacenAcopioGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionnAlmacenAcopioGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Almacen Acopio-GRANADA 2021',
                'verbose_name_plural': 'Almacen Acopio-GRANADA 2021',
            },
        ),
    ]
