# Generated by Django 2.2.6 on 2022-01-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0013_almacenacopiogrica2021_guiaathosgrica2021_guiadetallesathosgrica2021_infopaletgrica2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='anexo_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Descarte'),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='anexo_turno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turno Descarte'),
        ),
    ]
