# Generated by Django 2.2.6 on 2022-01-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0185_auto_20220108_1224'),
        ('granada', '0014_auto_20220106_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='anexo_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescartePPGrIca2021', to='menu.ProgramaProduccion'),
        ),
    ]
