# Generated by Django 2.2.6 on 2022-01-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0015_descarteathosgrica2021_anexo_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='anexo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteMatmpGrIca2021', to='menu.MaterialMMPP'),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteTurnoGrIca2021', to='menu.Turno'),
        ),
    ]
