# Generated by Django 2.2.6 on 2022-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0016_auto_20220119_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='descarte_mini',
        ),
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='merma_maquina',
        ),
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='merma_proceso',
        ),
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='merma_recepcion',
        ),
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='norecuperable',
        ),
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='recuperable',
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='alternaria',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='bajo_peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='cochinilla',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_roedor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='gelechidae',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_corona',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='inmadurez_verde',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='insolacion_fuerte',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='pudricion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='quereza',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_ae',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_golpe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
