# Generated by Django 2.2.6 on 2022-02-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0017_auto_20220202_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='anexo_produccion',
        ),
    ]
