# Generated by Django 2.2.6 on 2022-02-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0012_lineasplanta'),
        ('granada', '0018_remove_descarteathosgrica2021_anexo_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='anexo_linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granada_planta.LineasPlanta'),
        ),
    ]
