# Generated by Django 2.2.6 on 2022-02-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0019_descarteathosgrica2021_anexo_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descarteathosgrica2021',
            name='anexo_nave',
        ),
    ]
