# Generated by Django 2.2.6 on 2022-02-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0020_remove_descarteathosgrica2021_anexo_nave'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_campo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='deformes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='alternaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='bajo_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='cochinilla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='danio_roedor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='gelechidae',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='hongo_corona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='inmadurez_verde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='insolacion_fuerte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='peso_bruto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='pudricion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='quereza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='rajadas_ae',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='rajadas_golpe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
