# Generated by Django 2.2.6 on 2022-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0021_auto_20220209_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='alternaria_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='alternaria_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='alternaria_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='bajo_peso_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='bajo_peso_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='bajo_peso_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='cochinilla_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='cochinilla_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='cochinilla_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_campo_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_campo_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_campo_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_mecanico_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_roedor_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_roedor_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_roedor_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='deformes_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='deformes_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='deformes_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='gelechidae_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='gelechidae_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='gelechidae_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_corona_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_corona_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_corona_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='inmadurez_verde_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='inmadurez_verde_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='inmadurez_verde_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='insolacion_fuerte_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='insolacion_fuerte_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='insolacion_fuerte_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='pudricion_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='pudricion_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='pudricion_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='quereza_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='quereza_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='quereza_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_ae_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_ae_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_ae_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_golpe_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_golpe_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='rajadas_golpe_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
