# Generated by Django 2.2.6 on 2022-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0022_auto_20220216_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descarteathosgrica2021',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
