# Generated by Django 2.2.6 on 2022-03-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0023_auto_20220217_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='calibre18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='calibre18_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='calibre18_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='calibre18_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
