# Generated by Django 2.2.6 on 2022-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0024_auto_20220308_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_industrial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_industrial_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_industrial_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='danio_industrial_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
