# Generated by Django 2.2.6 on 2022-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0025_auto_20220323_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='arilo_pardo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='arilo_pardo_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='arilo_pardo_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='arilo_pardo_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
