# Generated by Django 2.2.6 on 2022-04-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0026_auto_20220326_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_industrial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_industrial_linea2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_industrial_linea3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarteathosgrica2021',
            name='hongo_industrial_linea4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
