# Generated by Django 2.2.6 on 2023-01-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0191_auto_20221121_1025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granada', '0027_auto_20220406_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAthosGrIca2023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('nroprecinto', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaAthosGrIca2023', to='menu.AlmacenesAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferesGrIca2023', to='menu.ChoferesVehiculos')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoGuiaGrIca2023', to='menu.fundo')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosEmpGrIca2023', to='menu.DatosEmpresa')),
                ('anexo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculosGrIca2023', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuiaGrIca2023', to='menu.ejezona')),
                ('ubic_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaLLGrIca2023', to='menu.LugarAthos')),
                ('ubic_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaPGrIca2023', to='menu.LugarAthos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuiaGrIca2023', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaGrIca2023', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Athos-Granada Ica 2023',
                'verbose_name_plural': 'Guias Athos-Granada Ica 2023',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthosGrIca2023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadMGrIca2023', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosGrIca2023', to='granada.GuiaAthosGrIca2023')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioGrIca2023', to='menu.MaterialAcopio')),
                ('anexo_ubi_mmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundoAthosGrIca2023', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaDGrIca2023', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDGrIca2023', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos-Granada Ica 2023',
                'verbose_name_plural': 'Guias  Detalles Athos- Granada Ica 2023',
            },
        ),
        migrations.CreateModel(
            name='InfoPaletGrIca2023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacenGrIca2023', to='menu.AlmacenesAthos')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosGrIca2023', to='granada.GuiaDetallesAthosGrIca2023')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuelaGrIca2023', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPaletsGrIca2023', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPaletsGrIca2023', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet-Granada Ica 2023',
                'verbose_name_plural': 'Info Palets-Granada Ica 2023',
            },
        ),
    ]
