# Generated by Django 2.2.6 on 2021-11-18 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('compra', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('venta', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionTasadeCambio', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModTasadeCambio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Cambio Athos ',
                'verbose_name_plural': 'Tipo Cambio Athos',
            },
        ),
    ]
