# Generated by Django 2.2.6 on 2021-11-18 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controlgestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProveedoresAthos',
            new_name='TasaCambioAthos',
        ),
    ]
