# Generated by Django 2.2.6 on 2022-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1')),
                ('fundo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1')),
                ('cultivo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1')),
                ('dni_supervisor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1')),
            ],
        ),
    ]
