# Generated by Django 2.2.6 on 2022-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileniveluno',
            name='cultivo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='mobileniveluno',
            name='dni_supervisor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='mobileniveluno',
            name='fundo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='mobileniveluno',
            name='zona',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zona'),
        ),
    ]
