# Generated by Django 2.2.6 on 2022-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220614_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileniveluno',
            name='fecha',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='mobileniveluno',
            name='hora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora'),
        ),
    ]
