# Generated by Django 2.2.6 on 2022-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220615_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileniveluno',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mobileniveluno',
            name='hora',
        ),
    ]
