# Generated by Django 2.2.6 on 2022-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220615_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestraAccesoAthosMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Trabajador')),
                ('dni', models.CharField(blank=True, max_length=12, null=True, verbose_name='DNI')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Trabajador')),
            ],
            options={
                'verbose_name': 'Maestras de Accesos Athos Mobile',
                'verbose_name_plural': 'Maestra de Acceso Athos Mobile',
            },
        ),
    ]
