# Generated by Django 2.2.6 on 2022-06-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maestraaccesoathosmobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileniveluno',
            options={'verbose_name': 'Tareo AR Primer Nivel', 'verbose_name_plural': 'Tareo AR Primer Nivel'},
        ),
    ]
