# Generated by Django 2.2.6 on 2022-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220616_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestraaccesoathosmobile',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='maestraaccesoathosmobile',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Usuario'),
        ),
    ]
