# Generated by Django 2.2.6 on 2022-06-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220616_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestraaccesoathosmobile',
            old_name='tipo',
            new_name='tipo_usuario',
        ),
        migrations.RenameField(
            model_name='maestraaccesoathosmobile',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
