# Generated by Django 2.2.6 on 2022-06-17 09:15

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220616_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuarioAccesoAthosMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Usuario')),
            ],
            options={
                'verbose_name': 'Tipos de Usuarios Accesos Athos Mobile',
                'verbose_name_plural': 'Tipo de Usuario Acceso Athos Mobile',
            },
        ),
        migrations.AlterField(
            model_name='maestraaccesoathosmobile',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=apps.api.models.TipoUsuarioAccesoAthosMobile),
        ),
    ]
