# Generated by Django 2.2.6 on 2022-06-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220617_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestraaccesoathosmobile',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoUsuarioAccesoAthos', to='api.TipoUsuarioAccesoAthosMobile'),
        ),
    ]
