# Generated by Django 2.2.6 on 2022-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220617_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileGaritaBusNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal')),
                ('contador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contador')),
                ('anexo_placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Garita Bus Nivel Dos',
                'verbose_name_plural': 'Garita Bus Nivel Dos',
            },
        ),
        migrations.CreateModel(
            name='MobileGaritaPersonalNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zona')),
                ('fundo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo')),
                ('personal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal')),
                ('tipo_hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Hora')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Garita Personal Nivel Uno',
                'verbose_name_plural': 'Garita Personal Nivel Uno',
            },
        ),
        migrations.CreateModel(
            name='MobileGaritaUnidadNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zona')),
                ('fundo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo')),
                ('personal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal')),
                ('tipo_hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Hora')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Garita Unidad Nivel Uno',
                'verbose_name_plural': 'Garita Unidad Nivel Uno',
            },
        ),
        migrations.CreateModel(
            name='MobileNivelDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_grupo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo Grupo')),
                ('fundo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo')),
                ('modulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Modulo')),
                ('lote', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lote')),
                ('labor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Labor')),
                ('personal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal')),
                ('anexo_supervisor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Supervisor')),
                ('jarra_uno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jarra Uno')),
                ('jarra_dos', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jarra Dos')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora_inicio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora Final')),
                ('estado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tareo AR Tercer Nivel',
                'verbose_name_plural': 'Tareo AR Tercer Nivel',
            },
        ),
        migrations.CreateModel(
            name='MobileNivelUnoMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Grupo')),
                ('contador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contador Grupo')),
                ('anexo_supervisor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tareo AR Segundo Nivel',
                'verbose_name_plural': 'Tareo AR Segundo Nivel',
            },
        ),
        migrations.CreateModel(
            name='MobileProductividadAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
                ('jarra', models.CharField(blank=True, max_length=30, null=True, verbose_name='Jarra')),
            ],
            options={
                'verbose_name': 'Productividad AR Primer Nivel',
                'verbose_name_plural': 'Productividad AR Primer Nivel',
            },
        ),
    ]
