# Generated by Django 2.2.6 on 2022-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mobilegaritabusniveluno_mobilegaritapersonalniveluno_mobilegaritaunidadniveluno_mobileniveldos_mobil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileGaritaBusNivelDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Personal')),
                ('contador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contador')),
                ('anexo_placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Garita Bus Nivel Dos',
                'verbose_name_plural': 'Garita Bus Nivel Dos',
            },
        ),
        migrations.AlterModelOptions(
            name='mobilegaritabusniveluno',
            options={'verbose_name': 'Garita Bus Nivel Uno', 'verbose_name_plural': 'Garita Bus Nivel Uno'},
        ),
        migrations.RenameField(
            model_name='mobilegaritabusniveluno',
            old_name='anexo_placa',
            new_name='placa',
        ),
        migrations.RemoveField(
            model_name='mobilegaritabusniveluno',
            name='contador',
        ),
        migrations.AddField(
            model_name='mobilegaritabusniveluno',
            name='fecha',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='mobilegaritabusniveluno',
            name='fundo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo'),
        ),
        migrations.AddField(
            model_name='mobilegaritabusniveluno',
            name='hora',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='mobilegaritabusniveluno',
            name='zona',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zona'),
        ),
    ]
