# Generated by Django 2.2.6 on 2022-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220620_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileniveldos',
            name='anexo_grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Grupo'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='anexo_supervisor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='fundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='hora_final',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='jarra_dos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jarra Dos'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='jarra_uno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jarra Uno'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='labor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Labor'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='modulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal'),
        ),
    ]
