# Generated by Django 2.2.6 on 2022-06-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220621_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileniveldos',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='mobileniveluno',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='mobilenivelunomedio',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Hora'),
        ),
    ]
