# Generated by Django 2.2.6 on 2022-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220621_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilegaritabusniveldos',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AddField(
            model_name='mobilegaritabusniveluno',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AddField(
            model_name='mobilegaritapersonalniveluno',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AddField(
            model_name='mobilegaritaunidadniveluno',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AlterField(
            model_name='mobileniveldos',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AlterField(
            model_name='mobileniveluno',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
        migrations.AlterField(
            model_name='mobilenivelunomedio',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
    ]
