# Generated by Django 2.2.6 on 2022-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220624_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproductividadar',
            name='sinc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado'),
        ),
    ]
