# Generated by Django 2.2.6 on 2022-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mobileproductividadar_sinc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegaritabusniveldos',
            name='anexo_placa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveldos',
            name='contador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contador'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveldos',
            name='personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='fundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='hora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='placa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='fundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='hora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='tipo_hora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Hora'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='fundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='hora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='tipo_hora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Hora'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona'),
        ),
    ]
