# Generated by Django 2.2.6 on 2022-07-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220625_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileniveldos',
            name='jarra_dos',
        ),
        migrations.RemoveField(
            model_name='mobileniveldos',
            name='jarra_uno',
        ),
    ]
