# Generated by Django 2.2.6 on 2022-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220705_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileproductividadar',
            name='jarra',
        ),
        migrations.AddField(
            model_name='mobileproductividadar',
            name='dni_personal',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='dni_personal'),
        ),
    ]
