# Generated by Django 2.2.6 on 2022-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220705_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileniveluno',
            name='pep',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pep'),
        ),
        migrations.AddField(
            model_name='mobilenivelunomedio',
            name='anexo_pep',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pep'),
        ),
    ]
