# Generated by Django 2.2.6 on 2022-07-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220708_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileniveluno',
            name='pep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pep'),
        ),
        migrations.AlterField(
            model_name='mobilenivelunomedio',
            name='anexo_pep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pep'),
        ),
    ]
