# Generated by Django 2.2.6 on 2022-07-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220709_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTareoArNivelDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_nivel1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Nivel 1')),
                ('id_grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Grupo')),
                ('contador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contador Grupo')),
                ('anexo_supervisor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Nivel Dos',
                'verbose_name_plural': 'Tareo AR Nivel Dos',
            },
        ),
        migrations.CreateModel(
            name='MobileTareoArNivelTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Grupo')),
                ('fundo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fundo')),
                ('modulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modulo')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('labor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Labor')),
                ('personal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Personal')),
                ('anexo_supervisor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor')),
                ('fecha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha')),
                ('hora_inicio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Final')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Nivel Tres',
                'verbose_name_plural': 'Tareo AR Nivel Tres',
            },
        ),
        migrations.CreateModel(
            name='MobileTareoArNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nivel_uno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Nivel 1')),
                ('zona', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zona')),
                ('fundo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo')),
                ('cultivo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cultivo')),
                ('dni_supervisor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Supervisor')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Nivel Uno',
                'verbose_name_plural': 'Tareo AR Nivel Uno',
            },
        ),
    ]
