# Generated by Django 2.2.6 on 2022-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_mobiletareoarniveldos_mobiletareoarniveltres_mobiletareoarniveluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTareoArPlantaNivelDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_nivel1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Nivel 1')),
                ('id_grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Grupo')),
                ('contador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contador Grupo')),
                ('dni', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI')),
                ('estado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Planta Nivel Dos',
                'verbose_name_plural': 'Tareo AR Planta Nivel Dos',
            },
        ),
        migrations.CreateModel(
            name='MobileTareoArPlantaNivelTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_grupo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anexo Grupo')),
                ('proceso', models.CharField(blank=True, max_length=30, null=True, verbose_name='Proceso')),
                ('actividad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Actividad')),
                ('labor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Labor')),
                ('mesa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mesa')),
                ('dni', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI')),
                ('fecha', models.CharField(blank=True, max_length=15, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=15, null=True, verbose_name='Hora')),
                ('estado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Planta Nivel Tres',
                'verbose_name_plural': 'Tareo AR Planta Nivel Tres',
            },
        ),
        migrations.CreateModel(
            name='MobileTareoArPlantaNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nivel_uno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Nivel 1')),
                ('nave', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nave')),
                ('linea', models.CharField(blank=True, max_length=30, null=True, verbose_name='Linea')),
                ('turno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Turno')),
                ('dni', models.CharField(blank=True, max_length=30, null=True, verbose_name='DNI')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
            ],
            options={
                'verbose_name': 'Tareo AR Planta Nivel Uno',
                'verbose_name_plural': 'Tareo AR Planta Nivel Uno',
            },
        ),
    ]
