# Generated by Django 2.2.6 on 2022-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mobiletareoarplantaniveldos_mobiletareoarplantaniveltres_mobiletareoarplantaniveluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletareoarplantaniveltres',
            name='actividad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='mobiletareoarplantaniveltres',
            name='labor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Labor'),
        ),
        migrations.AlterField(
            model_name='mobiletareoarplantaniveltres',
            name='mesa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='mobiletareoarplantaniveltres',
            name='proceso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proceso'),
        ),
    ]
