# Generated by Django 2.2.6 on 2022-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220717_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproductividadar',
            name='dni',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI'),
        ),
    ]
