# Generated by Django 2.2.6 on 2022-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_mobileproductividadar_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletareoarplantaniveltres',
            name='qr_personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QR Personal'),
        ),
    ]
