# Generated by Django 2.2.6 on 2022-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_mobiletareoarplantaniveltres_qr_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletareoarplantaniveltres',
            name='hora_final',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='mobiletareoarplantaniveltres',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Inicio'),
        ),
    ]
