# Generated by Django 2.2.6 on 2022-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220804_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegaritabusniveldos',
            name='anexo_placa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveldos',
            name='personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritabusniveluno',
            name='placa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='mobilegaritapersonalniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobilegaritaunidadniveluno',
            name='personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobileproductividadar',
            name='dni_personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='dni_personal'),
        ),
        migrations.AlterField(
            model_name='mobiletareoarniveltres',
            name='personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='mobiletareoarplantaniveltres',
            name='qr_personal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='QR Personal'),
        ),
    ]
