# Generated by Django 2.2.6 on 2022-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220826_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletareoarniveltres',
            name='actividad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Actividad'),
        ),
    ]
