# Generated by Django 2.2.6 on 2022-09-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_mobiletareoarniveltres_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedesAthosMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sede Descripcion')),
            ],
            options={
                'verbose_name': 'Sedes Accesos Athos Mobile',
                'verbose_name_plural': 'Sedes Acceso Athos Mobile',
            },
        ),
        migrations.CreateModel(
            name='MaestraAccesoSeguridadAthosMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario')),
                ('dni', models.CharField(blank=True, max_length=12, null=True, verbose_name='DNI')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SedesAthos', to='api.SedesAthosMobile')),
            ],
            options={
                'verbose_name': 'Maestras de Accesos Seguridad Athos Mobile',
                'verbose_name_plural': 'Maestra de Acceso Seguridad Athos Mobile',
            },
        ),
    ]
