# Generated by Django 2.2.6 on 2022-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_maestraaccesoseguridadathosmobile_mobileseguridadniveluno_sedesathosmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSeguridadNivelUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nivel_uno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Id Nivel 1')),
                ('dni', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI')),
                ('usuario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuario')),
                ('sede', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sede')),
                ('unidad_operaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad Operativa')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area')),
                ('tipo_reporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Reporte')),
                ('nombre_reporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acto Inseguro')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
            ],
            options={
                'verbose_name': 'Seguridad Nivel Uno',
                'verbose_name_plural': 'Seguridad Nivel Uno',
            },
        ),
    ]
