# Generated by Django 2.2.6 on 2022-10-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_mobileseguridadniveluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileseguridadniveluno',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='mobileseguridadniveluno',
            name='nombre_reporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Reporte'),
        ),
    ]
