# Generated by Django 2.2.6 on 2022-10-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20221011_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileseguridadniveluno',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='mobileseguridadniveluno',
            name='nombre_reporte',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Reporte'),
        ),
        migrations.AlterField(
            model_name='mobileseguridadniveluno',
            name='tipo_reporte',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo Reporte'),
        ),
        migrations.AlterField(
            model_name='mobileseguridadniveluno',
            name='unidad_operaria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Unidad Operativa'),
        ),
    ]
