# Generated by Django 2.2.6 on 2022-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20221011_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestraaccesoseguridadathosmobile',
            name='posicion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='maestraaccesoseguridadathosmobile',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
