# Generated by Django 2.2.6 on 2022-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20221105_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestraaccesoseguridadathosmobile',
            name='posicion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Posicion'),
        ),
    ]
