# Generated by Django 2.2.6 on 2022-11-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20221107_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProductividadPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Usuario')),
                ('qr', models.CharField(blank=True, max_length=100, null=True, verbose_name='QR')),
                ('fecha', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha')),
                ('hora', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hora')),
                ('sinc', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sincronizado')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
            ],
            options={
                'verbose_name': 'Productividad Planta Mobile',
                'verbose_name_plural': 'Productividad Planta Mobile',
            },
        ),
    ]
