# Generated by Django 2.2.6 on 2021-06-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta-Encuesta-Capacitacion',
                'verbose_name_plural': 'Respuesta-Encuesta-Capacitacion',
            },
        ),
        migrations.CreateModel(
            name='EncuestaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leer Dni')),
                ('fecha_capacitacion', models.DateField(blank=True, null=True, verbose_name='Fecha fecha_capacitacion')),
                ('imagen_justificacion1', models.ImageField(blank=True, null=True, upload_to='justificacion_capacitacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_rpta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaEncuesta1', to='capacitaciones.RespuestaEncuesta')),
                ('anexo_rpta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaEncuesta2', to='capacitaciones.RespuestaEncuesta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEncuestaCapacitacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEncuestaCapacitacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta Capacitacion',
                'verbose_name_plural': 'Encuesta Capacitacion',
            },
        ),
    ]
