# Generated by Django 2.2.6 on 2021-06-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0175_personalplanta_athos'),
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_capacitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCapacitacionEncuesta1', to='menu.CapacitacionCapacitacion'),
        ),
    ]
