# Generated by Django 2.2.6 on 2021-06-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0175_personalplanta_athos'),
        ('capacitaciones', '0002_encuestacapacitacion_anexo_capacitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEncuesta', to='menu.ejezona'),
        ),
        migrations.AlterField(
            model_name='encuestacapacitacion',
            name='anexo_capacitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCapacitacionEncuesta', to='menu.CapacitacionCapacitacion'),
        ),
    ]
