# Generated by Django 2.2.6 on 2021-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_auto_20210622_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaNumericaEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'RespuestaNumerica -Encuesta-Capacitacion',
                'verbose_name_plural': 'RespuestaNumerica -Encuesta-Capacitacion',
            },
        ),
    ]
