# Generated by Django 2.2.6 on 2021-06-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0004_respuestanumericaencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_rpta3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta3', to='capacitaciones.RespuestaNumericaEncuesta'),
        ),
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_rpta4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta4', to='capacitaciones.RespuestaNumericaEncuesta'),
        ),
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_rpta5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta5', to='capacitaciones.RespuestaNumericaEncuesta'),
        ),
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_rpta6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta6', to='capacitaciones.RespuestaNumericaEncuesta'),
        ),
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_rpta7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta7', to='capacitaciones.RespuestaNumericaEncuesta'),
        ),
    ]
