# Generated by Django 2.2.6 on 2021-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0005_auto_20210625_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta Aprobacion')),
            ],
            options={
                'verbose_name': 'Respuesta-Aprobacion-Capacitacion',
                'verbose_name_plural': 'Respuesta-Aprobacion-Capacitacion',
            },
        ),
    ]
