# Generated by Django 2.2.6 on 2021-06-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0006_respuestaaprobacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacapacitacion',
            name='anexo_capacitacion',
        ),
        migrations.RemoveField(
            model_name='encuestacapacitacion',
            name='anexo_zona',
        ),
    ]
