# Generated by Django 2.2.6 on 2021-06-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0177_asistenciacapacitacion_anexo_estado'),
        ('capacitaciones', '0007_auto_20210629_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestacapacitacion',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexozonaEncuesta', to='menu.ejezona'),
        ),
    ]
