# Generated by Django 2.2.6 on 2021-07-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0008_encuestacapacitacion_anexo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestacapacitacion',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCapacitacionEncuesta', to='menu.CapacitacionCapacitacion'),
        ),
    ]
