# Generated by Django 2.2.6 on 2021-07-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0010_auto_20210701_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestacapacitacion',
            old_name='anexo_capacitacion',
            new_name='anexo_capacitacion1',
        ),
    ]
