# Generated by Django 2.2.6 on 2021-07-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0012_auto_20210701_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacapacitacion',
            name='anexo_capacitacion',
        ),
    ]
