# Generated by Django 2.2.6 on 2021-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0014_encuestacapacitacion_anexo_capacitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacapacitacion',
            name='anexo_capacitacion1',
        ),
    ]
