# Generated by Django 2.2.6 on 2021-07-01 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0177_asistenciacapacitacion_anexo_estado'),
        ('capacitaciones', '0015_remove_encuestacapacitacion_anexo_capacitacion1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaCapacitacionNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leer Dni')),
                ('fecha_capacitacion', models.DateField(blank=True, null=True, verbose_name='Fecha fecha_capacitacion')),
                ('imagen_justificacion1', models.ImageField(blank=True, null=True, upload_to='justificacion_capacitacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCapacitacionEncuestaNew', to='menu.CapacitacionCapacitacion')),
                ('anexo_rpta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaEncuesta1New', to='capacitaciones.RespuestaEncuesta')),
                ('anexo_rpta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaEncuesta2New', to='capacitaciones.RespuestaEncuesta')),
                ('anexo_rpta3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta3New', to='capacitaciones.RespuestaNumericaEncuesta')),
                ('anexo_rpta4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta4New', to='capacitaciones.RespuestaNumericaEncuesta')),
                ('anexo_rpta5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta5New', to='capacitaciones.RespuestaNumericaEncuesta')),
                ('anexo_rpta6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta6New', to='capacitaciones.RespuestaNumericaEncuesta')),
                ('anexo_rpta7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRespuestaNumericaEncuesta7New', to='capacitaciones.RespuestaNumericaEncuesta')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexozonaEncuestaNew', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEncuestaCapacitacionNew', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEncuestaCapacitacionNew', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta Capacitacion New',
                'verbose_name_plural': 'Encuesta Capacitacion New',
            },
        ),
    ]
