# Generated by Django 2.2.6 on 2021-07-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0016_encuestacapacitacionnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacapacitacionnew',
            name='fecha_capacitacion',
        ),
    ]
