# Generated by Django 2.2.6 on 2021-11-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0017_remove_encuestacapacitacionnew_fecha_capacitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestacapacitacionnew',
            name='anexo_rpta7',
        ),
    ]
