# Generated by Django 2.2.6 on 2021-01-27 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleGaritaBusAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionDetalleGaritaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionDetalleGaritaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Bus Garita Athos',
                'verbose_name_plural': 'Detalle Bus Garita Athos',
            },
        ),
    ]
