# Generated by Django 2.2.6 on 2021-01-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garita', '0002_detallegaritabusathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegaritabusathos',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleGaritaBus', to='garita.GaritaAthos'),
        ),
    ]
