# Generated by Django 2.2.6 on 2021-04-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0170_auto_20210323_1459'),
        ('garita', '0003_detallegaritabusathos_anexo_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegaritabusathos',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetFunGaritaAthos', to='menu.fundo'),
        ),
        migrations.AddField(
            model_name='detallegaritabusathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetZonaGaritaAthos', to='menu.ejezona'),
        ),
    ]
