# Generated by Django 2.2.6 on 2021-04-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garita', '0004_auto_20210405_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garitaathos',
            name='anexo_ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRutaAthos', to='menu.DetallePlacasVehiculares'),
        ),
    ]
