# Generated by Django 2.2.6 on 2021-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garita', '0006_auto_20210406_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='garitaathos',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
