# Generated by Django 2.2.6 on 2021-04-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garita', '0007_garitaathos_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoGaritaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traslado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Traslado')),
            ],
            options={
                'verbose_name': ' Traslado Garita Athos',
                'verbose_name_plural': 'Traslado Garita Athos',
            },
        ),
        migrations.AddField(
            model_name='garitaathos',
            name='anexo_traslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTrasladoGaritaAthos', to='garita.TrasladoGaritaAthos'),
        ),
    ]
