# Generated by Django 2.2.6 on 2020-07-03 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModEnfriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('cod_termometro', models.CharField(max_length=30, verbose_name='Codigo de termometro')),
                ('cod_vac1', models.CharField(max_length=30, verbose_name='Codigo de Vacuometro 1')),
                ('cod_vac2', models.CharField(max_length=30, verbose_name='Codigo de Vacuometro 2')),
                ('cod_vac3', models.CharField(max_length=30, verbose_name='Codigo de Vacuometro 3')),
                ('hora_inicio', models.TimeField(verbose_name='Ingreso de Enfriado')),
                ('hora_inicio_enfriado', models.TimeField(verbose_name='Inicio de Enfriado')),
                ('hora_salida', models.TimeField(verbose_name='Salida de Enfriado')),
                ('hora_salida_enfriado', models.TimeField(verbose_name='Termino de Salida de Enfriado')),
                ('hora_enfriamiento', models.TimeField(verbose_name='Horas de enfriamiento')),
                ('hora_total_enfriado', models.TimeField(verbose_name='Total de horas de operacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEnfriado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEnfriado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo Enfriado',
                'verbose_name_plural': 'Modulo de Enfriado',
            },
        ),
    ]
