# Generated by Django 2.2.6 on 2020-07-03 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionEnfriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura_qr', models.CharField(max_length=50, verbose_name='Lectura QR')),
                ('n_palet', models.DecimalField(decimal_places=0, max_digits=5)),
                ('calibre', models.DecimalField(decimal_places=0, max_digits=5)),
                ('caja', models.CharField(max_length=30, verbose_name='Caja')),
                ('formato', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presentacion', models.CharField(max_length=30, verbose_name='Presentacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDistribucion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDistribucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo Enfriado',
                'verbose_name_plural': 'Modulo de Enfriado',
            },
        ),
    ]
