# Generated by Django 2.2.6 on 2020-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0002_distribucionenfriado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribucionenfriado',
            options={'verbose_name': 'Distribucion Enfriado', 'verbose_name_plural': 'Distribucion Enfriado'},
        ),
        migrations.AddField(
            model_name='distribucionenfriado',
            name='n_tunel',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
