# Generated by Django 2.2.6 on 2020-07-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0003_auto_20200703_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionenfriado',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoDistribucion', to='acopio.ModEnfriado'),
        ),
    ]
