# Generated by Django 2.2.6 on 2020-07-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0005_temperaturaenfriado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribucionenfriado',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='distribucionenfriado',
            name='calibre',
        ),
        migrations.RemoveField(
            model_name='distribucionenfriado',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='distribucionenfriado',
            name='presentacion',
        ),
    ]
