# Generated by Django 2.2.6 on 2020-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0006_auto_20200708_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadosTunel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lados', models.CharField(max_length=50, verbose_name='Lados Tunel')),
            ],
            options={
                'verbose_name': 'Lados Tunel',
                'verbose_name_plural': 'Lados Tunel',
            },
        ),
    ]
