# Generated by Django 2.2.6 on 2020-07-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0007_ladostunel'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionenfriado',
            name='anexo_lado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLadoTunelD', to='acopio.LadosTunel'),
        ),
    ]
