# Generated by Django 2.2.6 on 2020-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0008_distribucionenfriado_anexo_lado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_enfriamiento',
        ),
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_inicio_enfriado',
        ),
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_salida_enfriado',
        ),
        migrations.RemoveField(
            model_name='modenfriado',
            name='hora_total_enfriado',
        ),
        migrations.AlterField(
            model_name='modenfriado',
            name='cod_termometro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de termometro'),
        ),
        migrations.AlterField(
            model_name='modenfriado',
            name='cod_vac1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1'),
        ),
        migrations.AlterField(
            model_name='modenfriado',
            name='cod_vac2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 2'),
        ),
        migrations.AlterField(
            model_name='modenfriado',
            name='cod_vac3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 3'),
        ),
    ]
