# Generated by Django 2.2.6 on 2020-07-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0009_auto_20200717_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionenfriado',
            name='lectura_qr',
            field=models.CharField(max_length=100, verbose_name='Lectura QR'),
        ),
    ]
