# Generated by Django 2.2.6 on 2020-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0010_auto_20200720_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionenfriado',
            name='tunel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribucionenfriado',
            name='n_tunel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
