# Generated by Django 2.2.6 on 2020-07-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0011_auto_20200720_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionenfriado',
            name='lectura_qr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Lectura QR'),
        ),
    ]
