# Generated by Django 2.2.6 on 2020-08-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0012_auto_20200724_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturaenfriado',
            old_name='m_vacio',
            new_name='m_tempambiente',
        ),
    ]
