# Generated by Django 2.2.6 on 2020-09-01 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0139_auto_20200821_2303'),
        ('acopio', '0013_auto_20200804_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDescarteAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descarte', models.CharField(max_length=50, verbose_name='TipoDescarte')),
            ],
            options={
                'verbose_name': 'Tipo Descarte',
                'verbose_name_plural': 'Tipo Descarte',
            },
        ),
        migrations.CreateModel(
            name='DescarteAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzado', models.DateField(verbose_name='Fecha Lanzado')),
                ('peso_descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteEje', to='menu.ejezona')),
                ('anexo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteMMPP', to='menu.MaterialMMPP')),
                ('anexo_nave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteNave', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescartePlanta', to='menu.Planta')),
                ('tipo_descarte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionDescarte', to='acopio.TipoDescarteAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDescarte', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDescarte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarte Planta Athos',
                'verbose_name_plural': 'Descarte Planta Athos',
            },
        ),
    ]
