# Generated by Django 2.2.6 on 2020-09-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0014_descarteathos_tipodescarteathos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descarteathos',
            name='tipo_descarte',
        ),
    ]
