# Generated by Django 2.2.6 on 2020-09-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0015_remove_descarteathos_tipo_descarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathos',
            name='descarte_mini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='descarteathos',
            name='merma_maquina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='descarteathos',
            name='merma_proceso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='descarteathos',
            name='merma_recepcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
