# Generated by Django 2.2.6 on 2020-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0016_auto_20200902_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathos',
            name='norecuperable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='descarteathos',
            name='recuperable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
