# Generated by Django 2.2.6 on 2020-09-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0140_lpaletas_anexo_cultivo'),
        ('acopio', '0017_auto_20200902_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathos',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteTurno', to='menu.Turno'),
        ),
    ]
