# Generated by Django 2.2.6 on 2020-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0018_descarteathos_anexo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionenfriado',
            name='n_tunel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
