# Generated by Django 2.2.6 on 2021-01-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0164_variedad_tipo_fruta'),
        ('acopio', '0019_auto_20201028_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathos',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteFundo', to='menu.fundo'),
        ),
        migrations.AddField(
            model_name='descarteathos',
            name='cant_jabas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
