# Generated by Django 2.2.6 on 2021-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0020_auto_20210125_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarteathos',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
