# Generated by Django 2.2.6 on 2021-02-01 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0164_variedad_tipo_fruta'),
        ('acopio', '0022_auto_20210125_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSalidaDescarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Salida Descarte')),
            ],
            options={
                'verbose_name': 'Tipo Salidad Descarte',
                'verbose_name_plural': 'Tipo Salida Descarte',
            },
        ),
        migrations.CreateModel(
            name='SalidaDescarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoSalidaDescarte', to='menu.cultivo')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoSalidaDescarte', to='acopio.TipoSalidaDescarte')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionSalidaDescarte', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModSalidaDescarte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida Descarte',
                'verbose_name_plural': 'Salida Descarte',
            },
        ),
    ]
