# Generated by Django 2.2.6 on 2021-02-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0164_variedad_tipo_fruta'),
        ('acopio', '0023_salidadescarte_tiposalidadescarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidadescarte',
            name='anexo_eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeSalidaDescarte', to='menu.ejezona'),
        ),
    ]
