# Generated by Django 2.2.6 on 2021-02-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0024_salidadescarte_anexo_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidadescarte',
            name='nroguia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro Guia'),
        ),
    ]
