# Generated by Django 2.2.6 on 2021-07-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0025_salidadescarte_nroguia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionEnfriadoArCaraz2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunel', models.IntegerField(blank=True, null=True)),
                ('n_tunel', models.CharField(blank=True, max_length=100, null=True)),
                ('lectura_qr', models.CharField(max_length=100, unique=True, verbose_name='Lectura QR')),
                ('n_palet', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Distribucion Enfriado-Arandano Caraz 2021',
                'verbose_name_plural': 'Distribucion Enfriado-Arandano Caraz 2021',
            },
        ),
        migrations.CreateModel(
            name='TemperaturaEnfriadoArCaraz2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_tempambiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('m_tempinterna', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_tempexterna', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_temperatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTemperaturaEnfriadoArCaraz2021', to='acopio.DistribucionEnfriadoArCaraz2021')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionTemperaturaArCaraz2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModTemperaturaArCaraz2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temperatura Enfriado-Arandanos Caraz 2021',
                'verbose_name_plural': 'Temperatura Enfriado-Arandanos Caraz 2021',
            },
        ),
        migrations.CreateModel(
            name='ModEnfriadoArCaraz2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('cod_termometro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de termometro')),
                ('cod_vac1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 1')),
                ('cod_vac2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 2')),
                ('cod_vac3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Vacuometro 3')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEnfriadoArCaraz2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEnfriadoArCaraz2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo Enfriado-Arandano Caraz 2021',
                'verbose_name_plural': 'Modulo de Enfriado-Arandano Caraz 2021',
            },
        ),
        migrations.AddField(
            model_name='distribucionenfriadoarcaraz2021',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoDistribucionArCaraz2021', to='acopio.ModEnfriadoArCaraz2021'),
        ),
        migrations.AddField(
            model_name='distribucionenfriadoarcaraz2021',
            name='anexo_lado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLadoTunelDArCaraz2021', to='acopio.LadosTunel'),
        ),
        migrations.AddField(
            model_name='distribucionenfriadoarcaraz2021',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDistribucionArCaraz2021', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribucionenfriadoarcaraz2021',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDistribucionArCaraz2021', to=settings.AUTH_USER_MODEL),
        ),
    ]
