# Generated by Django 2.2.6 on 2022-07-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0189_auto_20220609_0915'),
        ('acopio', '0027_auto_20220606_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='modenfriadoarcaraz202102',
            name='anexo_planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlantaEnfriado', to='menu.Planta'),
        ),
    ]
