# Generated by Django 2.2.6 on 2022-08-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0029_modenfriado2022_tipomodenfriado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionModEnfriado2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ticket', models.CharField(max_length=50, verbose_name='N° Ticket')),
            ],
            options={
                'verbose_name': 'Confirmacion Mod Enfriado 2022',
                'verbose_name_plural': 'Confirmacion Mod Enfriado 2022',
            },
        ),
        migrations.AlterModelOptions(
            name='tipomodenfriado',
            options={'verbose_name': 'Tipo Enfriado', 'verbose_name_plural': 'Tipo Enfriado'},
        ),
        migrations.CreateModel(
            name='TomaDatosModEnfriado2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_tempinterna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('m_tempexterna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('m_tempambiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anexo_lado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLadoTunelTomaDatosModEnfriado2022', to='acopio.LadosTunel')),
            ],
            options={
                'verbose_name': 'Toma de Datos Mod Enfriado 2022',
                'verbose_name_plural': 'Toma de Datos Mod Enfriado 2022',
            },
        ),
    ]
