# Generated by Django 2.2.6 on 2022-08-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0030_auto_20220808_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoConfirmacion', to='acopio.ModEnfriado'),
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoTomaDatos', to='acopio.ModEnfriado'),
        ),
    ]
