# Generated by Django 2.2.6 on 2022-08-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0032_auto_20220808_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirmacionEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserConfirmacionModEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionTomaDatosEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTomaDatosModEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
    ]
