# Generated by Django 2.2.6 on 2022-08-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0033_auto_20220808_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacionmodenfriado2022',
            name='n_ticket',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022',
            name='n_palet',
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022',
            name='n_palet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confirmacionmodenfriado2022',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoConfirmacionPalet', to='acopio.ModEnfriado2022'),
        ),
        migrations.AlterField(
            model_name='confirmacionmodenfriado2022',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirmacionPaletEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmacionmodenfriado2022',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserConfirmacionPaletModEnfriado2022', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConfirmacionTicketModEnfriado2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ticket', models.CharField(max_length=50, verbose_name='N° Ticket')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_palet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoConfirmacionTicket', to='acopio.ConfirmacionModEnfriado2022')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirmacionTicketEnfriado2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserConfirmacionTicketModEnfriado2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmacion Mod Ticket Enfriado 2022',
                'verbose_name_plural': 'Confirmacion Mod Ticket Enfriado 2022',
            },
        ),
    ]
