# Generated by Django 2.2.6 on 2022-08-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0034_auto_20220810_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_palet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoPalet', to='acopio.ConfirmacionModEnfriado2022'),
        ),
    ]
