# Generated by Django 2.2.6 on 2022-08-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0035_tomadatosmodenfriado2022_anexo_palet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_palet',
        ),
    ]
