# Generated by Django 2.2.6 on 2022-08-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0036_remove_tomadatosmodenfriado2022_anexo_palet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_enfriado',
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_palet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoTomaDatos', to='acopio.ConfirmacionModEnfriado2022'),
        ),
    ]
