# Generated by Django 2.2.6 on 2022-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0037_auto_20220811_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022',
            name='m_tempambiente',
        ),
        migrations.AddField(
            model_name='modenfriado2022',
            name='m_tempambiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
