# Generated by Django 2.2.6 on 2022-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0038_auto_20220811_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='modenfriado2022',
            name='n_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
