# Generated by Django 2.2.6 on 2022-08-16 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0039_modenfriado2022_n_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modenfriado2022',
            name='m_tempambiente',
        ),
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_palet',
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='n_palet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroTemperaturaModEnfriado2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_tempambiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_enfriado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoRTemperatura', to='acopio.ModEnfriado2022')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRTemperaturaEnfriado2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserRTemperaturaModEnfriado2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Temperaturas Mod Enfriado 2022',
                'verbose_name_plural': 'Registro de Temperaturas Mod Enfriado 2022',
            },
        ),
        migrations.AddField(
            model_name='tomadatosmodenfriado2022',
            name='anexo_temperatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoTomaDatos', to='acopio.RegistroTemperaturaModEnfriado2022'),
        ),
    ]
