# Generated by Django 2.2.6 on 2022-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0040_auto_20220816_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacionticketmodenfriado2022',
            name='n_ticket',
            field=models.CharField(max_length=150, verbose_name='N° Ticket'),
        ),
    ]
