# Generated by Django 2.2.6 on 2022-08-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acopio', '0041_auto_20220817_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionModEnfriado2022COPIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_palet', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Confirmacion Mod Enfriado 2022COPIA',
                'verbose_name_plural': 'Confirmacion Mod Enfriado 2022COPIA',
            },
        ),
        migrations.CreateModel(
            name='ModEnfriado2022COPIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('n_tunel', models.IntegerField(blank=True, null=True)),
                ('n_batch', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLadoTunelModEnfriado2022COPIA', to='acopio.LadosTunel')),
                ('anexo_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlantaEnfriado2022COPIA', to='menu.Planta')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoModEnfriado2022COPIA', to='acopio.TipoModEnfriado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo Enfriado 2022COPIA',
                'verbose_name_plural': 'Modulo de Enfriado 2022COPIA',
            },
        ),
        migrations.CreateModel(
            name='RegistroTemperaturaModEnfriado2022COPIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_tempambiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_enfriado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoRTemperaturaCOPIA', to='acopio.ModEnfriado2022COPIA')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRTemperaturaEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserRTemperaturaModEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Temperaturas Mod Enfriado 2022COPIA',
                'verbose_name_plural': 'Registro de Temperaturas Mod Enfriado 2022COPIA',
            },
        ),
        migrations.CreateModel(
            name='TomaDatosModEnfriado2022COPIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_palet', models.IntegerField(blank=True, null=True)),
                ('m_tempinterna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('m_tempexterna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_temperatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoTomaDatosCOPIA', to='acopio.RegistroTemperaturaModEnfriado2022COPIA')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionTomaDatosEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTomaDatosModEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toma de Datos Mod Enfriado 2022COPIA',
                'verbose_name_plural': 'Toma de Datos Mod Enfriado 2022COPIA',
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionTicketModEnfriado2022COPIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ticket', models.CharField(max_length=150, verbose_name='N° Ticket')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_palet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoConfirmacionTicketCOPIA', to='acopio.ConfirmacionModEnfriado2022COPIA')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirmacionTicketEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserConfirmacionTicketModEnfriado2022COPIA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Confirmacion Mod Ticket Enfriado 2022COPIA',
                'verbose_name_plural': 'Confirmacion Mod Ticket Enfriado 2022COPIA',
            },
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022copia',
            name='anexo_enfriado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnfriadoConfirmacionPaletCOPIA', to='acopio.ModEnfriado2022COPIA'),
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022copia',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirmacionPaletEnfriado2022COPIA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmacionmodenfriado2022copia',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserConfirmacionPaletModEnfriado2022COPIA', to=settings.AUTH_USER_MODEL),
        ),
    ]
