# Generated by Django 2.2.6 on 2022-08-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acopio', '0042_auto_20220822_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacionticketmodenfriado2022copia',
            name='anexo_palet',
        ),
        migrations.RemoveField(
            model_name='confirmacionticketmodenfriado2022copia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='confirmacionticketmodenfriado2022copia',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022copia',
            name='anexo_lado',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022copia',
            name='anexo_planta',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022copia',
            name='anexo_tipo',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022copia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='modenfriado2022copia',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='registrotemperaturamodenfriado2022copia',
            name='anexo_enfriado',
        ),
        migrations.RemoveField(
            model_name='registrotemperaturamodenfriado2022copia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='registrotemperaturamodenfriado2022copia',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022copia',
            name='anexo_temperatura',
        ),
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022copia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tomadatosmodenfriado2022copia',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='ConfirmacionModEnfriado2022COPIA',
        ),
        migrations.DeleteModel(
            name='ConfirmacionTicketModEnfriado2022COPIA',
        ),
        migrations.DeleteModel(
            name='ModEnfriado2022COPIA',
        ),
        migrations.DeleteModel(
            name='RegistroTemperaturaModEnfriado2022COPIA',
        ),
        migrations.DeleteModel(
            name='TomaDatosModEnfriado2022COPIA',
        ),
    ]
