# Generated by Django 2.2.6 on 2022-10-05 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('acopio', '0043_auto_20220822_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescartePlantaHgAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(verbose_name='Fecha Proceso')),
                ('descarte1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte11', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte12', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte13', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte14', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte15', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte16', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte17', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descarte18', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteMMPPHg2022', to='menu.MaterialMMPP')),
                ('anexo_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescartePlantaHg2022', to='menu.Planta')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDescarteTurnoHg2022', to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDescarteHg2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDescarteHg2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarte Planta Hg Athos 2022',
                'verbose_name_plural': 'Descarte Planta Hg Athos 2022',
            },
        ),
    ]
