# Generated by Django 2.2.6 on 2021-04-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0170_auto_20210323_1459'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosJustificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo Justificacion Topico',
                'verbose_name_plural': 'Motivo Justificacion Topico',
            },
        ),
        migrations.CreateModel(
            name='JustificacionTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leer Dni')),
                ('fecha_justificacion', models.DateField(blank=True, null=True, verbose_name='Fecha Justificacion')),
                ('imagen_justificacion1', models.ImageField(blank=True, null=True, upload_to='foto_capacitacion')),
                ('imagen_justificacion2', models.ImageField(blank=True, null=True, upload_to='foto_acta_capacitacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoJustificacionLugar', to='menu.LugarAthos')),
                ('anexo_motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoJustificacionZona', to='topico.MotivosJustificacion')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoJustificacionZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionJustificacionTopico', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModJustificacionTopico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificacion Topico',
                'verbose_name_plural': 'Justificacion Topico',
            },
        ),
    ]
