# Generated by Django 2.2.6 on 2021-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificaciontopico',
            name='imagen_justificacion1',
            field=models.ImageField(blank=True, null=True, upload_to='foto_topico'),
        ),
        migrations.AlterField(
            model_name='justificaciontopico',
            name='imagen_justificacion2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_topico'),
        ),
    ]
