# Generated by Django 2.2.6 on 2021-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0002_auto_20210405_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificaciontopico',
            name='justificacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Justificacion'),
        ),
    ]
