# Generated by Django 2.2.6 on 2021-04-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0003_justificaciontopico_justificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMotivosJustificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Detalle Motivo Justificacion Topico',
                'verbose_name_plural': 'Detalle Motivo Justificacion Topico',
            },
        ),
        migrations.AddField(
            model_name='justificaciontopico',
            name='anexo_detallemotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleJustificacionZona', to='topico.DetalleMotivosJustificacion'),
        ),
    ]
