# Generated by Django 2.2.6 on 2021-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0004_auto_20210407_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificaciontopico',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='justificaciontopico',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
