# Generated by Django 2.2.6 on 2021-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0005_auto_20210616_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificaciontopico',
            name='adjunta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adjunta'),
        ),
    ]
