# Generated by Django 2.2.6 on 2021-06-21 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0175_personalplanta_athos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topico', '0006_justificaciontopico_adjunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAmonestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Motivo Amonestacion- Topico',
                'verbose_name_plural': 'Motivo Amonestacion- Topico',
            },
        ),
        migrations.CreateModel(
            name='AmonestacionTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amonestado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Amonestado')),
                ('sap', models.IntegerField(blank=True, null=True)),
                ('amonestador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Amonestador')),
                ('asunto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Asunto')),
                ('fecha_actual', models.DateField(blank=True, null=True, verbose_name='Fecha Actual')),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Motivacion')),
                ('fecha_amonestacion', models.DateField(blank=True, null=True, verbose_name='Fecha Amonestacion')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('articulos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Articulos')),
                ('antecedentes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Articulos')),
                ('otros', models.CharField(blank=True, max_length=250, null=True, verbose_name='Otros')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAmonestacionLugar', to='menu.LugarAthos')),
                ('anexo_motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMotivoAmonestacion', to='topico.MotivoAmonestacion')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAmonestacionZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionAmonestacionTopico', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModAmonestacionTopico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amonestacion Topico',
                'verbose_name_plural': 'Amonestacion Topico',
            },
        ),
    ]
