# Generated by Django 2.2.6 on 2021-11-24 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0184_auto_20211021_1332'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topico', '0007_amonestaciontopico_motivoamonestacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta Topico',
                'verbose_name_plural': 'Respuesta Topico',
            },
        ),
        migrations.CreateModel(
            name='TipoDolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dolor')),
            ],
            options={
                'verbose_name': 'TIPO DE DOLOR',
                'verbose_name_plural': 'TIPO DE DOLOR',
            },
        ),
        migrations.CreateModel(
            name='FichaSintomatologiaCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leer Dni')),
                ('nombre_completo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Completo')),
                ('area_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Area Trabajo')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaSCovEmpresa', to='menu.DatosEmpresa')),
                ('anexo_preg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta1', to='topico.RespuestaTopico')),
                ('anexo_preg2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta2_1', to='topico.RespuestaTopico')),
                ('anexo_preg3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta2_2', to='topico.RespuestaTopico')),
                ('anexo_preg4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta2_3', to='topico.RespuestaTopico')),
                ('anexo_preg5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta2_4', to='topico.RespuestaTopico')),
                ('anexo_preg6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichascovidRpta2_5', to='topico.RespuestaTopico')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usercreacionfichascovuser', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModfichascovuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha sintomatologica  Topico',
                'verbose_name_plural': 'Ficha sintomatologica  Topico',
            },
        ),
        migrations.CreateModel(
            name='FichaEpidemiologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leer Dni')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('nombre_completo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Completo')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Genero')),
                ('fecha_sintomas', models.DateField(blank=True, null=True, verbose_name='Fecha Sintomas')),
                ('lugar_visita', models.CharField(blank=True, max_length=250, null=True, verbose_name='Lugar Visita')),
                ('trimestre_embarazo', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaEpiLugar', to='menu.LugarAthos')),
                ('anexo_preg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta1', to='topico.RespuestaTopico')),
                ('anexo_preg2_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_1', to='topico.RespuestaTopico')),
                ('anexo_preg2_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_2', to='topico.RespuestaTopico')),
                ('anexo_preg2_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_3', to='topico.RespuestaTopico')),
                ('anexo_preg2_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_4', to='topico.RespuestaTopico')),
                ('anexo_preg2_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_5', to='topico.RespuestaTopico')),
                ('anexo_preg2_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_6', to='topico.TipoDolor')),
                ('anexo_preg2_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta2_7', to='topico.RespuestaTopico')),
                ('anexo_preg4_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta4_1', to='topico.RespuestaTopico')),
                ('anexo_preg5_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta5_1', to='topico.RespuestaTopico')),
                ('anexo_preg6_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_1', to='topico.RespuestaTopico')),
                ('anexo_preg6_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_10', to='topico.RespuestaTopico')),
                ('anexo_preg6_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_2', to='topico.RespuestaTopico')),
                ('anexo_preg6_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_3', to='topico.RespuestaTopico')),
                ('anexo_preg6_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_4', to='topico.RespuestaTopico')),
                ('anexo_preg6_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_5', to='topico.RespuestaTopico')),
                ('anexo_preg6_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_6', to='topico.RespuestaTopico')),
                ('anexo_preg6_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_7', to='topico.RespuestaTopico')),
                ('anexo_preg6_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_8', to='topico.RespuestaTopico')),
                ('anexo_preg6_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaepiRpta6_9', to='topico.RespuestaTopico')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaEpiZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usercreacionfichaepiuser', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModfichaepiuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha epidemiologica  Topico',
                'verbose_name_plural': 'Ficha epidemiologica  Topico',
            },
        ),
    ]
