# Generated by Django 2.2.6 on 2020-07-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0127_auto_20200721_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionArandano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Año')),
                ('semana', models.CharField(blank=True, max_length=30, null=True, verbose_name='Semana')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cultivo')),
                ('anexo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ejezona')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.fundo')),
                ('anexo_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.VariableAgronomica')),
            ],
            options={
                'verbose_name': 'Proyeccion Arandano',
                'verbose_name_plural': 'Proyecciones Arandanos',
            },
        ),
        migrations.CreateModel(
            name='ProyeccionSemanalArandano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.IntegerField(blank=True, null=True, verbose_name='Lunes')),
                ('martes', models.IntegerField(blank=True, null=True, verbose_name='Martes')),
                ('miercoles', models.IntegerField(blank=True, null=True, verbose_name='Miercoles')),
                ('jueves', models.IntegerField(blank=True, null=True, verbose_name='Jueves')),
                ('viernes', models.IntegerField(blank=True, null=True, verbose_name='Viernes')),
                ('sabado', models.IntegerField(blank=True, null=True, verbose_name='Sabado')),
                ('domingo', models.IntegerField(blank=True, null=True, verbose_name='Domingo')),
                ('semana1', models.IntegerField(blank=True, null=True, verbose_name='Semana 1')),
                ('semana2', models.IntegerField(blank=True, null=True, verbose_name='Semana 2 ')),
                ('anexo_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecciones.ProyeccionArandano')),
            ],
            options={
                'verbose_name': ' Proyeccion Semanal Arandano',
                'verbose_name_plural': ' Proyecciones  Semanales Arandanos',
            },
        ),
        migrations.CreateModel(
            name='DetalleProyeccionArandano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.IntegerField(blank=True, null=True, verbose_name='Lunes')),
                ('martes', models.IntegerField(blank=True, null=True, verbose_name='Martes')),
                ('miercoles', models.IntegerField(blank=True, null=True, verbose_name='Miercoles')),
                ('jueves', models.IntegerField(blank=True, null=True, verbose_name='Jueves')),
                ('viernes', models.IntegerField(blank=True, null=True, verbose_name='Viernes')),
                ('sabado', models.IntegerField(blank=True, null=True, verbose_name='Sabado')),
                ('domingo', models.IntegerField(blank=True, null=True, verbose_name='Domingo')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecciones.ProyeccionArandano')),
                ('anexo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ProgramaProduccion')),
                ('anexo_subvariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.SubVariableAgronomica')),
            ],
            options={
                'verbose_name': 'Detalle Proyeccion Arandano',
                'verbose_name_plural': 'Detalle Proyecciones Arandanos',
            },
        ),
    ]
