# Generated by Django 2.2.6 on 2020-07-23 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionDetProyeccionArandano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionDetProyeccionArandano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyeccionarandano',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='proyeccionarandano',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='proyeccionarandano',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionProyeccionArandano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyeccionarandano',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionProyeccionArandano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyeccionsemanalarandano',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='proyeccionsemanalarandano',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='proyeccionsemanalarandano',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionProyeccionSemArandano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyeccionsemanalarandano',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionProyeccionSemArandano', to=settings.AUTH_USER_MODEL),
        ),
    ]
