# Generated by Django 2.2.6 on 2020-08-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0139_auto_20200821_2303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecciones', '0002_auto_20200723_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionDiariaArandano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Año')),
                ('semana', models.CharField(blank=True, max_length=30, null=True, verbose_name='Semana')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoArandano', to='menu.cultivo')),
                ('anexo_eje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeArandano', to='menu.ejezona')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoArandano', to='menu.fundo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionProyeccionDiariaArandano', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionProyeccionDiariaArandano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyeccion Arandano Diaria',
                'verbose_name_plural': 'Proyecciones Arandanos Diarias',
            },
        ),
    ]
