# Generated by Django 2.2.6 on 2020-08-27 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecciones', '0003_proyecciondiariaarandano'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetProyeccionDiariaArandano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.IntegerField(blank=True, null=True, verbose_name='Lunes')),
                ('martes', models.IntegerField(blank=True, null=True, verbose_name='Martes')),
                ('miercoles', models.IntegerField(blank=True, null=True, verbose_name='Miercoles')),
                ('jueves', models.IntegerField(blank=True, null=True, verbose_name='Jueves')),
                ('viernes', models.IntegerField(blank=True, null=True, verbose_name='Viernes')),
                ('sabado', models.IntegerField(blank=True, null=True, verbose_name='Sabado')),
                ('domingo', models.IntegerField(blank=True, null=True, verbose_name='Domingo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecciones.ProyeccionDiariaArandano')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreacionDetProyeccionDiariaArandano', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModificacionDetProyeccionDiariaArandano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Proyeccion Diaria Arandano',
                'verbose_name_plural': 'Detalle Proyecciones Diarias Arandanos',
            },
        ),
    ]
