# Generated by Django 2.2.6 on 2020-09-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0141_programaproduccion_responsable'),
        ('proyecciones', '0004_detproyecciondiariaarandano'),
    ]

    operations = [
        migrations.AddField(
            model_name='detproyecciondiariaarandano',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDiariaFundoPep', to='menu.ProgramaProduccion'),
        ),
    ]
