# Generated by Django 2.2.6 on 2020-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0006_detalleproyeccionanualarandano_proyeccionanualarandano'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionanualarandano',
            name='anexo_aniocosecha',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Año Cosecha'),
        ),
    ]
