# Generated by Django 2.2.6 on 2020-09-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0007_detalleproyeccionanualarandano_anexo_aniocosecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproyeccionanualarandano',
            options={'verbose_name': 'Detalle Proyeccion Anuales Arandano', 'verbose_name_plural': 'Detalle Proyecciones Anuales Arandanos'},
        ),
        migrations.AlterModelOptions(
            name='proyeccionanualarandano',
            options={'verbose_name': 'Proyeccion Arandano Anuales', 'verbose_name_plural': 'Proyecciones Arandanos Anuales'},
        ),
    ]
