# Generated by Django 2.2.6 on 2020-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0008_auto_20200916_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproyeccionarandano',
            options={'verbose_name': 'EV. Detalle Proyeccion Arandano', 'verbose_name_plural': 'EV. Detalle Proyecciones Arandanos'},
        ),
        migrations.AlterModelOptions(
            name='proyeccionarandano',
            options={'verbose_name': 'EV. Proyeccion Arandano', 'verbose_name_plural': ' EV. Proyecciones Arandanos'},
        ),
    ]
