# Generated by Django 2.2.6 on 2020-12-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0159_materialacopio_anexo_cultivo'),
        ('proyecciones', '0009_auto_20200928_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.variedad'),
        ),
    ]
