# Generated by Django 2.2.6 on 2020-12-31 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0159_materialacopio_anexo_cultivo'),
        ('proyecciones', '0010_detalleproyeccionarandano_anexo_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detproyecciondiariaarandano',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.variedad'),
        ),
    ]
