# Generated by Django 2.2.6 on 2021-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0011_detproyecciondiariaarandano_anexo_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionanualarandano',
            name='semana53',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semana53'),
        ),
    ]
