# Generated by Django 2.2.6 on 2021-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0012_detalleproyeccionanualarandano_semana53'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='semana2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='semana3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='semana4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
