# Generated by Django 2.2.6 on 2021-12-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0013_auto_20210129_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='domingo_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Domingo2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='jueves_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jueves2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='lunes_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lunes2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='martes_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Martes2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='miercoles_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Miercoles2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='sabado_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sabado2'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionarandano',
            name='viernes_sem2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Viernes2'),
        ),
    ]
