# Generated by Django 2.2.6 on 2020-09-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionesAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentaciong', models.CharField(max_length=30, verbose_name='PresentacionG')),
                ('presentacion', models.CharField(max_length=30, verbose_name='Presentacion')),
                ('pesodestino', models.IntegerField(blank=True, null=True)),
                ('pesomin', models.IntegerField(blank=True, null=True)),
                ('pesomax', models.IntegerField(blank=True, null=True)),
                ('por_pesomin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('por_pesomax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.CharField(max_length=30, verbose_name='Cliente')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMPresentacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMPresentacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentaciones Athos',
                'verbose_name_plural': '\tPresentaciones Athos',
            },
        ),
    ]
