# Generated by Django 2.2.6 on 2020-09-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0142_auto_20200916_1654'),
        ('maestras', '0002_auto_20200922_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrapresentacionesathos',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoPresentacionesA', to='menu.cultivo'),
        ),
        migrations.AddField(
            model_name='presentacionesathos',
            name='anexo_centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCentroPresentacionesG', to='menu.CentrosAthos'),
        ),
        migrations.AddField(
            model_name='presentacionesathos',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoPresentacionesG', to='menu.cultivo'),
        ),
    ]
