# Generated by Django 2.2.6 on 2020-10-02 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0142_auto_20200916_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0004_lineaempaqueathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartillasAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartilla', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cartilla')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo')),
                ('grupo', models.CharField(blank=True, max_length=100, null=True, verbose_name='grupo')),
                ('subgrupo', models.CharField(blank=True, max_length=100, null=True, verbose_name='subgrupo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCartillasCalibres', to='menu.CentrosAthos')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoCartillas', to='menu.cultivo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionCartillasAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModCartillasAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartillas Athos',
                'verbose_name_plural': 'Cartillas Athos',
            },
        ),
    ]
