# Generated by Django 2.2.6 on 2020-10-02 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0142_auto_20200916_1654'),
        ('maestras', '0005_cartillasathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboresAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipolabor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Labor')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion Labor')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLaboresCalibres', to='menu.CentrosAthos')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoLabores', to='menu.cultivo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionLaboresAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModLaboresAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labores Athos',
                'verbose_name_plural': 'Labores Athos',
            },
        ),
        migrations.CreateModel(
            name='DescripcionLaboresAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_labor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Labor')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLDescaboresCalibres', to='menu.CentrosAthos')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoLaboresDesc', to='menu.cultivo')),
                ('anexo_tipolabor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLaboresDescLabot', to='maestras.LaboresAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDescLaboresAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDescLaboresAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desc. Labores Athos',
                'verbose_name_plural': 'Desc. Labores Athos',
            },
        ),
    ]
