# Generated by Django 2.2.6 on 2020-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0006_descripcionlaboresathos_laboresathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionlaboresathos',
            name='descripcion_labor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion Labor'),
        ),
    ]
