# Generated by Django 2.2.6 on 2020-10-29 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0142_auto_20200916_1654'),
        ('maestras', '0007_descripcionlaboresathos_descripcion_labor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaresCampoAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxiliar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Auxiliar Campo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxiliarEstado', to='menu.Estado')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxiliarFundo', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxiliaresZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionAuxiliarCampo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModAuxiliarCampo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auxiliar Campo Athos',
                'verbose_name_plural': 'Auxiliar Campo Athos',
            },
        ),
    ]
