# Generated by Django 2.2.6 on 2022-03-16 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0008_auxiliarescampoathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanquesAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tanque', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('fundo_tanque', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Fundo - Tanque')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTanqueFundo1', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTanquesZona1', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionTanquesAthos1', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModTanquesAthos1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanques Athos',
                'verbose_name_plural': 'Tanques Athos',
            },
        ),
    ]
