# Generated by Django 2.2.6 on 2022-03-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        ('maestras', '0009_tanquesathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Actividades Athos',
                'verbose_name_plural': 'Actividades Athos',
            },
        ),
        migrations.CreateModel(
            name='LaboresPlantaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo')),
                ('labor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Labor')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoLaboresPlantaAthos', to='menu.cultivo')),
                ('anexo_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProcesoLaboresPlantaAthos', to='maestras.ActividadesAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionLaboresPlantaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModLaboresPlantaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labores Planta Athos',
                'verbose_name_plural': 'Labores Planta Athos',
            },
        ),
    ]
