# Generated by Django 2.2.6 on 2022-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0010_actividadesathos_laboresplantaathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarescampoathos',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
