# Generated by Django 2.2.6 on 2022-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0011_auxiliarescampoathos_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliarescampoathos',
            name='dni',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='DNI'),
        ),
    ]
