# Generated by Django 2.2.6 on 2022-08-29 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('maestras', '0012_auto_20220412_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestraFundoCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoMaestraCultivo', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoMaestraCultivo', to='menu.fundo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMaestraFundoCultivo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMaestraFundoCultivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestra Fundo Cultivos',
                'verbose_name_plural': 'Maestra Fundo Cultivos',
            },
        ),
    ]
