# Generated by Django 2.2.6 on 2022-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0013_maestrafundocultivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestrafundocultivo',
            name='anexo_fundo',
        ),
        migrations.AddField(
            model_name='maestrafundocultivo',
            name='fundo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Fundo'),
        ),
    ]
