# Generated by Django 2.2.6 on 2022-10-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0014_auto_20220829_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAuxiliarCampoAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo Auxiliar Actividades Athos',
                'verbose_name_plural': 'Tipo Auxiliar Actividades Athos',
            },
        ),
        migrations.AddField(
            model_name='auxiliarescampoathos',
            name='anexo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoAuxiliar', to='maestras.TipoAuxiliarCampoAthos'),
        ),
    ]
