# Generated by Django 2.2.6 on 2022-04-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0010_actividadesathos_laboresplantaathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedoresEquipoPlantaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.BigIntegerField(blank=True, null=True)),
                ('razon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProveedoresEquipoPlantaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProveedoresEquipoPlantaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedores Equipo Planta Athos',
                'verbose_name_plural': 'Proveedores Equipo Planta Athos',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipoPlantaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoMantenimientoEquipoPlantaAthos', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoMantenimientoEquipoPlantaAthos', to='menu.fundo')),
                ('anexo_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProveedorMantenimientoEquipoPlantaAthos', to='mantenimiento.ProveedoresEquipoPlantaAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMantenimientoEquiposPlantaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMantenimientoEquiposPlantaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matenimiento Equipo Planta Athos',
                'verbose_name_plural': 'Matenimiento Equipo Planta Athos',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimientoEquipoPlantaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Mantenimiento')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('total_horas', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Horas')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetMantenimientoEquipoPlantaAthos', to='mantenimiento.MantenimientoEquipoPlantaAthos')),
                ('anexo_labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLaborMantenimientoEquipoPlantaAthos', to='maestras.LaboresPlantaAthos')),
                ('anexo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPepMantenimientoEquipoPlantaAthos', to='menu.ProgramaProduccion')),
                ('anexo_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProcesoMantenimientoEquipoPlantaAthos', to='maestras.ActividadesAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleMantenimientoEquipoPlantaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleMantenimientoEquipoPlantaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Mantenimiento Equipo Planta Athos',
                'verbose_name_plural': 'Detalle Mantenimiento Equipo Planta Athos',
            },
        ),
    ]
