# Generated by Django 2.2.6 on 2022-04-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_implementosequipoplantaathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemantenimientoequipoplantaathos',
            name='anexo_implemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoImplementosMantenimientoEquipoPlantaAthos', to='mantenimiento.ImplementosEquipoPlantaAthos'),
        ),
    ]
