# Generated by Django 2.2.6 on 2020-07-09 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0117_placasvehiculares_anexo_tipounidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvFenBrotesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('valvula', models.CharField(max_length=30, verbose_name='Valvula')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiEvBrotes', to='menu.UbicacionFundo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvFenBrotes', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvFenBrotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fenologia Brotes Arandanos ',
                'verbose_name_plural': 'Ev. Fenologia Brotes Arandanos',
            },
        ),
    ]
