# Generated by Django 2.2.6 on 2020-07-10 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlantaEvFenBrotesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_planta', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cant_ramas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvDetPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fenologia Brotes Arandanos ',
                'verbose_name_plural': 'Ev. Fenologia Brotes Arandanos',
            },
        ),
    ]
