# Generated by Django 2.2.6 on 2020-07-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_detalleplantaevfenbrotesarandanos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleplantaevfenbrotesarandanos',
            options={'verbose_name': 'Ev. Fen. Brote Detalle Planta Arandanos ', 'verbose_name_plural': 'Ev. Fen. Brotes Detalle Planta  Arandanos'},
        ),
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanos',
            name='anexo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalle', to='evaluaciones.EvFenBrotesArandanos'),
        ),
    ]
