# Generated by Django 2.2.6 on 2020-07-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0003_auto_20200710_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrotePlantaEvFenBrotesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('diametrobrote', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('nudos', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('hojas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('A1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('L1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('A2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('L2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('A3', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('L3', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('axilas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('yemas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('YM', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('YA', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('yhinchada', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('yescamosa', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('botonrosado', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('flor', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cuajado', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('verde1', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('verde2', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('verde3', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('envero', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('verderojo', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('rojoverde', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('rojoazul', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('azulrojo', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('maduro', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalleBrote', to='evaluaciones.DetallePlantaEvFenBrotesArandanos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionBrote', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvBrote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fen. Brote Detalle Planta Arandanos ',
                'verbose_name_plural': 'Ev. Fen. Brotes Detalle Planta  Arandanos',
            },
        ),
    ]
