# Generated by Django 2.2.6 on 2020-07-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_sectoresathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evfenbrotesarandanos',
            name='Sectores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSectoresEvFen', to='evaluaciones.SectoresAthos'),
        ),
    ]
