# Generated by Django 2.2.6 on 2020-07-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_nbrotes_ndiametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='anexo_brote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.NBrotes'),
        ),
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='anexo_diametro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.NDiametro'),
        ),
    ]
