# Generated by Django 2.2.6 on 2020-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_auto_20200714_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='ycargador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
