# Generated by Django 2.2.6 on 2020-07-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_broteplantaevfenbrotesarandanos_ycargador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broteplantaevfenbrotesarandanos',
            name='YA',
        ),
        migrations.RemoveField(
            model_name='broteplantaevfenbrotesarandanos',
            name='YM',
        ),
    ]
