# Generated by Django 2.2.6 on 2020-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0011_auto_20200714_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoyema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yema', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Yema',
                'verbose_name_plural': 'Tipo de Yemas',
            },
        ),
    ]
