# Generated by Django 2.2.6 on 2020-07-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0012_tipoyema'),
    ]

    operations = [
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='anexo_yema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.tipoyema'),
        ),
    ]
