# Generated by Django 2.2.6 on 2020-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0013_broteplantaevfenbrotesarandanos_anexo_yema'),
    ]

    operations = [
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='botonfloral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='verde4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
