# Generated by Django 2.2.6 on 2020-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0014_auto_20200717_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broteplantaevfenbrotesarandanos',
            name='envero',
        ),
        migrations.RemoveField(
            model_name='broteplantaevfenbrotesarandanos',
            name='yemas',
        ),
    ]
