# Generated by Django 2.2.6 on 2020-07-23 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0127_auto_20200721_1228'),
        ('evaluaciones', '0015_auto_20200722_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvFenRaicesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_planta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_cuadrante', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_molde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('zona', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Detalle Ev. Fenologia Raices Arandanos ',
                'verbose_name_plural': 'Detalle Ev. Fenologia  Raices Arandanos',
            },
        ),
        migrations.CreateModel(
            name='RaicesEvFenRaicesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField(blank=True, null=True)),
                ('re', models.IntegerField(blank=True, null=True)),
                ('rfs', models.IntegerField(blank=True, null=True)),
                ('rfj', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_raices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRaicesDetEvRaices', to='evaluaciones.DetalleEvFenRaicesArandanos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRaicesEvFenRaices', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRaicesEvFenRaices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raices Ev. Fenologia Raices Arandanos ',
                'verbose_name_plural': 'Raices Ev. Fenologia  Raices Arandanos',
            },
        ),
        migrations.CreateModel(
            name='EvFenRaicesArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('valvula', models.CharField(max_length=30, verbose_name='Valvula')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiEvRaices', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvFenRaices', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvFenRaices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fenologia Raices Arandanos ',
                'verbose_name_plural': 'Ev. Fenologia  Raices Arandanos',
            },
        ),
        migrations.AddField(
            model_name='detalleevfenraicesarandanos',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetEvRaices', to='evaluaciones.EvFenRaicesArandanos'),
        ),
        migrations.AddField(
            model_name='detalleevfenraicesarandanos',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvFenRaices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleevfenraicesarandanos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvFenRaices', to=settings.AUTH_USER_MODEL),
        ),
    ]
