# Generated by Django 2.2.6 on 2020-07-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0016_auto_20200723_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evfenbrotesarandanos',
            name='Sectores',
        ),
    ]
