# Generated by Django 2.2.6 on 2020-07-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0017_remove_evfenbrotesarandanos_sectores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevfenraicesarandanos',
            name='num_cuadrante',
        ),
        migrations.RemoveField(
            model_name='detalleevfenraicesarandanos',
            name='zona',
        ),
    ]
