# Generated by Django 2.2.6 on 2020-07-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0018_auto_20200723_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRaices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'zona ',
                'verbose_name_plural': 'zonas',
            },
        ),
        migrations.AddField(
            model_name='raicesevfenraicesarandanos',
            name='anexo_cuadrante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCuadranteRaices', to='evaluaciones.NDiametro'),
        ),
        migrations.AddField(
            model_name='raicesevfenraicesarandanos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaRaices', to='evaluaciones.ZonaRaices'),
        ),
    ]
