# Generated by Django 2.2.6 on 2020-08-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0019_auto_20200723_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evfenbrotesarandanos',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvBrotes', to='menu.ProgramaProduccion'),
        ),
    ]
