# Generated by Django 2.2.6 on 2020-08-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0131_auto_20200802_0949'),
        ('evaluaciones', '0020_auto_20200802_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='evfenbrotesarandanos',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEv', to='menu.fundo'),
        ),
        migrations.AddField(
            model_name='evfenbrotesarandanos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEv', to='menu.ejezona'),
        ),
    ]
