# Generated by Django 2.2.6 on 2020-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0022_auto_20200802_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='evfenraicesarandanos',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observacion'),
        ),
    ]
