# Generated by Django 2.2.6 on 2020-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0023_evfenraicesarandanos_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='broteplantaevfenbrotesarandanos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='raicesevfenraicesarandanos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='raicesevfenraicesarandanos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
