# Generated by Django 2.2.6 on 2020-09-16 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0001_initial'),
        ('menu', '0141_programaproduccion_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0024_auto_20200907_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trazabilidad', models.BigIntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lanzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCPT', to='menu.LPaletas')),
                ('anexo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductoCPT', to='maestras.PresentacionesAthos')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptTurno', to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreacionCPT', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModCPT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Producto Terminado',
                'verbose_name_plural': ' Control Producto Terminado',
            },
        ),
        migrations.CreateModel(
            name='SelectorAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'SelectorAthos ',
                'verbose_name_plural': 'SelectorAthos',
            },
        ),
        migrations.CreateModel(
            name='DetalleControlProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p11', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleCPT', to='evaluaciones.ControlProductoTerminado')),
                ('anexo_muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleMuestra', to='evaluaciones.SelectorAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetCPT', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetCPT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Detalle Control Producto Terminado',
                'verbose_name_plural': 'Detalle Control Producto Terminado',
            },
        ),
    ]
