# Generated by Django 2.2.6 on 2020-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0025_controlproductoterminado_detallecontrolproductoterminado_selectorathos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlproductoterminado',
            name='fecha_hora_creacion',
            field=models.DateField(verbose_name='Fecha y Hora de Creación'),
        ),
    ]
