# Generated by Django 2.2.6 on 2020-09-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0001_initial'),
        ('evaluaciones', '0026_auto_20200916_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproductoterminado',
            name='anexo_producto',
        ),
        migrations.RemoveField(
            model_name='controlproductoterminado',
            name='trazabilidad',
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductoCPT', to='maestras.PresentacionesAthos'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='trazabilidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
