# Generated by Django 2.2.6 on 2020-09-16 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0142_auto_20200916_1654'),
        ('evaluaciones', '0027_auto_20200916_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvFenBrotesArandanosSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('valvula', models.CharField(max_length=30, verbose_name='Valvula')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvSem', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEvSem', to='menu.ejezona')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvBrotesSem', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvFenBrotesSem1', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvFenBrotesSem1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sem-Ev. Fenologia Brotes Arandanos ',
                'verbose_name_plural': 'Sem-Ev. Fenologia Brotes Arandanos',
            },
        ),
        migrations.CreateModel(
            name='DetallePlantaEvFenBrotesArandanosSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_planta', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('verde4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verderojo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rojoverde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rojoazul', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('azulrojo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maduro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalleSem', to='evaluaciones.EvFenBrotesArandanosSem')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetPlantaSem', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvDetPlantaSem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sem-Ev. Fen. Brote Detalle Planta Arandanos ',
                'verbose_name_plural': 'Sem-Ev. Fen. Brotes Detalle Planta  Arandanos',
            },
        ),
        migrations.CreateModel(
            name='BrotePlantaEvFenBrotesArandanosSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verde4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verderojo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rojoverde', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rojoazul', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('azulrojo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maduro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalleBroteSem', to='evaluaciones.DetallePlantaEvFenBrotesArandanosSem')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionBroteSem1', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvBroteSem1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sem-Ev. Fen. Brote Detalle Planta Arandanos ',
                'verbose_name_plural': 'Sem-Ev. Fen. Brotes Detalle Planta  Arandanos',
            },
        ),
    ]
