# Generated by Django 2.2.6 on 2020-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0028_broteplantaevfenbrotesarandanossem_detalleplantaevfenbrotesarandanossem_evfenbrotesarandanossem'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
