# Generated by Django 2.2.6 on 2020-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0029_auto_20200917_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
