# Generated by Django 2.2.6 on 2020-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0030_auto_20200919_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='azulrojo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='maduro',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='rojoazul',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='rojoverde',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verde4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='verderojo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
