# Generated by Django 2.2.6 on 2020-09-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0002_auto_20200922_1202'),
        ('menu', '0142_auto_20200916_1654'),
        ('evaluaciones', '0031_auto_20200919_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecontrolproductoterminado',
            options={'verbose_name': 'CDet ontrol Producto Terminado', 'verbose_name_plural': 'Det  Control Producto Terminado'},
        ),
        migrations.RemoveField(
            model_name='detallecontrolproductoterminado',
            name='anexo_producto',
        ),
        migrations.RemoveField(
            model_name='detallecontrolproductoterminado',
            name='trazabilidad',
        ),
        migrations.AddField(
            model_name='controlproductoterminado',
            name='anexo_centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptCentros', to='menu.CentrosAthos'),
        ),
        migrations.AddField(
            model_name='controlproductoterminado',
            name='anexo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductoCPT', to='maestras.PresentacionesAthos'),
        ),
        migrations.AddField(
            model_name='controlproductoterminado',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='controlproductoterminado',
            name='trazabilidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_acomodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleAcomodo', to='maestras.AcomodoAthos'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_calibre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleCalibre', to='maestras.CalibresAthos'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleCliente', to='maestras.ClientesAthos'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleMaestraP', to='maestras.MaestraPresentacionesAthos'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleVariedad', to='menu.variedad'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='arana_fruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='bajo_calibre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='blando',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='cochinilla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='deforme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='desgarro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='deshidratacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='exudacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='firme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='heridas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='homogeneidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='inmadura_rojo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='inmadura_verde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='machucon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='material_extrano',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='micelio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='mosca_fruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='n1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='n2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='n3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='n4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='peso_neto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='polvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='presencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='pudricion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='restos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='russet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='sensitivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='tamano_pulpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlproductoterminado',
            name='fecha_hora_creacion',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Creación'),
        ),
    ]
