# Generated by Django 2.2.6 on 2020-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0032_auto_20200922_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproductoterminado',
            name='trazabilidad',
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='trazabilidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
