# Generated by Django 2.2.6 on 2020-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0033_auto_20200922_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecontrolproductoterminado',
            name='trazabilidad',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Trazabilidad'),
        ),
    ]
