# Generated by Django 2.2.6 on 2020-09-22 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0002_auto_20200922_1202'),
        ('evaluaciones', '0035_auto_20200922_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproductoterminado',
            name='anexo_producto',
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_presentaciong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPresentaciongCPT', to='maestras.PresentacionesAthos'),
        ),
    ]
