# Generated by Django 2.2.6 on 2020-09-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0004_lineaempaqueathos'),
        ('evaluaciones', '0036_auto_20200922_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproductoterminado',
            name='anexo_linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptLineaE', to='maestras.LineaEmpaqueAthos'),
        ),
    ]
