# Generated by Django 2.2.6 on 2020-09-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0038_auto_20200925_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproductoterminado',
            name='anexo_pagina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPaginaControl', to='evaluaciones.SelectorAthos'),
        ),
    ]
