# Generated by Django 2.2.6 on 2020-09-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0040_auto_20200928_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleplantaevfenbrotesarandanos',
            options={'verbose_name': 'Detalle-Ev. Fen. Brote Detalle Planta Arandanos ', 'verbose_name_plural': 'Detalle-Ev. Fen. Brotes Detalle Planta  Arandanos'},
        ),
    ]
