# Generated by Django 2.2.6 on 2020-09-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0041_auto_20200928_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesplagasarandanos',
            name='hoja_ancha_hojas2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
