# Generated by Django 2.2.6 on 2020-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0042_variablesplagasarandanos_hoja_ancha_hojas2'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesplagasarandanos',
            name='abejas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
