# Generated by Django 2.2.6 on 2020-10-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0044_auto_20201005_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evsanplagasarandanos',
            name='valvula',
        ),
    ]
