# Generated by Django 2.2.6 on 2020-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0045_remove_evsanplagasarandanos_valvula'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesplagasarandanos',
            name='criytola_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
