# Generated by Django 2.2.6 on 2020-10-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0046_variablesplagasarandanos_criytola_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablesplagasarandanos',
            old_name='criytola_num',
            new_name='cryptola_num',
        ),
    ]
