# Generated by Django 2.2.6 on 2020-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0047_auto_20201007_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='nbrotes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevfenbrotesarandanossem',
            name='nramas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
