# Generated by Django 2.2.6 on 2020-10-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0048_auto_20201009_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesplagasarandanos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='variablesplagasarandanos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
