# Generated by Django 2.2.6 on 2020-10-15 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0050_evfenfrutoarandanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorEvFrutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector EV Frutos ',
                'verbose_name_plural': 'Selector EV Frutos',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvFenFrutoArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbaya', models.IntegerField(blank=True, null=True)),
                ('calibre', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('observacion', models.CharField(max_length=300, verbose_name='Observacion')),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_selector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSelectorEvFruto', to='evaluaciones.SelectorEvFrutos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvFenFrutos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvFenFrutos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Det-Ev Fenologica Frutos',
                'verbose_name_plural': 'Det-Ev Fenologica Frutos',
            },
        ),
    ]
