# Generated by Django 2.2.6 on 2020-10-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0051_detalleevfenfrutoarandanos_selectorevfrutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevfenfrutoarandanos',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetEvFruto', to='evaluaciones.EvFenFrutoArandanos'),
        ),
    ]
