# Generated by Django 2.2.6 on 2020-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0052_detalleevfenfrutoarandanos_anexo_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevfenfrutoarandanos',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observacion'),
        ),
    ]
