# Generated by Django 2.2.6 on 2020-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0054_controlproductoterminado_anexo_pep'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproductoterminado',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
