# Generated by Django 2.2.6 on 2020-10-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0142_auto_20200916_1654'),
        ('evaluaciones', '0055_controlproductoterminado_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlproductoterminado',
            name='anexo_pep',
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCPTPP', to='menu.ProgramaProduccion'),
        ),
    ]
