# Generated by Django 2.2.6 on 2020-10-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0057_evfenplanasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorEvPlanasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector EV Planasa',
                'verbose_name_plural': 'Selector EV Planasa',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvFenPlanasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_planta', models.CharField(max_length=30, verbose_name='Codigo Planta')),
                ('altura_planta', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('longitud1', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('longitud2', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('diametro', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('nro_hojas', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('observacion', models.CharField(max_length=300, verbose_name='Observacion')),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvPlanasa', to='evaluaciones.EvFenPlanasa')),
                ('anexo_selector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSelectorEvPlanasa', to='evaluaciones.SelectorEvPlanasa')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvFenPlanasa', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvFenPlanasa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Ev. Fenologia Planasa',
                'verbose_name_plural': 'Detalle-Ev. Fenologia  Planasa',
            },
        ),
    ]
