# Generated by Django 2.2.6 on 2020-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0058_detalleevfenplanasa_selectorevplanasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevfenplanasa',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observacion'),
        ),
    ]
