# Generated by Django 2.2.6 on 2020-10-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0059_auto_20201020_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecontrolproductoterminado',
            name='anexo_pep',
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='npalet',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
