# Generated by Django 2.2.6 on 2020-10-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0060_auto_20201021_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorBroteEvPlanasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Brote EV Planasa',
                'verbose_name_plural': 'Selector  Brote EV Planasa',
            },
        ),
        migrations.AddField(
            model_name='detalleevfenplanasa',
            name='anexo_brote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSelBroteEvPlanasa', to='evaluaciones.SelectorBroteEvPlanasa'),
        ),
    ]
