# Generated by Django 2.2.6 on 2020-10-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0062_evcaldefectoscampo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcaldefectoscampo',
            name='valvula',
        ),
    ]
