# Generated by Django 2.2.6 on 2020-11-03 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0008_auxiliarescampoathos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0142_auto_20200916_1654'),
        ('evaluaciones', '0063_remove_evcaldefectoscampo_valvula'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorTipoCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Tipo Calidad-Ev. Calidad',
                'verbose_name_plural': 'Selector  Tipo Calidad -Ev. Calidad',
            },
        ),
        migrations.AddField(
            model_name='evcaldefectoscampo',
            name='valvula',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Valvula'),
        ),
        migrations.CreateModel(
            name='DetalleEvCalDefectosCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula', models.CharField(blank=True, max_length=300, null=True, verbose_name='Valvula')),
                ('densidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reingreso', models.IntegerField(blank=True, null=True)),
                ('muestra', models.IntegerField(blank=True, null=True)),
                ('remanente', models.IntegerField(blank=True, null=True)),
                ('desgarro', models.IntegerField(blank=True, null=True)),
                ('inmadurez', models.IntegerField(blank=True, null=True)),
                ('polvo', models.IntegerField(blank=True, null=True)),
                ('otros', models.IntegerField(blank=True, null=True)),
                ('bayas', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observacion')),
                ('dni', models.BigIntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_auxiliares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxiliarEvCal', to='maestras.AuxiliaresCampoAthos')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalCampo', to='evaluaciones.EvCalDefectosCampo')),
                ('anexo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDetalleRvCal', to='evaluaciones.SelectorTipoCalidad')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadEvCalCampo', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalCampo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalCampo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Ev. Calidad Defectos Campos ',
                'verbose_name_plural': 'Detalle-Ev. Calidad Defectos Campos',
            },
        ),
    ]
