# Generated by Django 2.2.6 on 2020-11-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0064_auto_20201103_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcaldefectoscampo',
            name='valvula',
        ),
    ]
