# Generated by Django 2.2.6 on 2020-11-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0065_remove_evcaldefectoscampo_valvula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='bayas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='densidad',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='desgarro',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='inmadurez',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='muestra',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='otros',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='polvo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='remanente',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
