# Generated by Django 2.2.6 on 2020-11-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0067_evcalacopioplanta_selectortipoprioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='exportable',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
