# Generated by Django 2.2.6 on 2020-11-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0068_detalleevcaldefectoscampo_exportable'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
