# Generated by Django 2.2.6 on 2020-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0069_evcalacopioplanta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalacopioplanta',
            name='idacopio',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
