# Generated by Django 2.2.6 on 2020-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0070_auto_20201109_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='tol_frutosr4_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
