# Generated by Django 2.2.6 on 2021-02-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0071_evcalacopioplanta_tol_frutosr4_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacionBr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo ev')),
            ],
            options={
                'verbose_name': 'Tipo EV ',
                'verbose_name_plural': 'Tipo EV',
            },
        ),
        migrations.AddField(
            model_name='evfenbrotesarandanos',
            name='anexo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEVBr', to='evaluaciones.TipoEvaluacionBr'),
        ),
    ]
