# Generated by Django 2.2.6 on 2021-03-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0073_evcartilladrenado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvCartillaDrenado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula', models.CharField(blank=True, max_length=300, null=True, verbose_name='Valvula')),
                ('ubicacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ubicacion')),
                ('tiempo_riego', models.TimeField(blank=True, null=True, verbose_name='Tiempo Riego')),
                ('volumen_drenado', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('caudal_real', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('pulso', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ce', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ph_gotero', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ce_gotero', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ph_sonda', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ce_sonda', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observacion')),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCartillaDrenado', to='evaluaciones.EvCartillaDrenado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCartillaDrenado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCartillaDrenado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Ev. Cartilla Drenado ',
                'verbose_name_plural': 'Detalle-Ev. Cartilla Drenado',
            },
        ),
    ]
