# Generated by Django 2.2.6 on 2021-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0074_detalleevcartilladrenado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcartilladrenado',
            name='m3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
