# Generated by Django 2.2.6 on 2021-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0075_evcartilladrenado_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcartilladrenado',
            name='tiempo_riego',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo Riego'),
        ),
    ]
