# Generated by Django 2.2.6 on 2021-03-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0076_auto_20210311_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ph',
        ),
    ]
