# Generated by Django 2.2.6 on 2021-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0077_remove_detalleevcartilladrenado_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcartilladrenado',
            name='m3',
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='m3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
