# Generated by Django 2.2.6 on 2021-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0078_auto_20210312_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorPulsoDetEvCartillaDrenado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pulso')),
            ],
            options={
                'verbose_name': 'Pulso-Detalle-Ev. Cartilla Drenado ',
                'verbose_name_plural': 'Pulso-Detalle-Ev. Cartilla Drenado',
            },
        ),
        migrations.CreateModel(
            name='SelectorUbiDetEvCartillaDrenado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Selector-Detalle-Ev. Cartilla Drenado ',
                'verbose_name_plural': 'Selector Detalle-Ev. Cartilla Drenado',
            },
        ),
    ]
