# Generated by Django 2.2.6 on 2021-03-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0080_auto_20210319_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcartilladrenado',
            name='pulso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPulsoDetEvCartillaDrenado', to='evaluaciones.SelectorPulsoDetEvCartillaDrenado'),
        ),
        migrations.AlterField(
            model_name='detalleevcartilladrenado',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiDetEvCartillaDrenado', to='evaluaciones.SelectorUbiDetEvCartillaDrenado'),
        ),
    ]
