# Generated by Django 2.2.6 on 2021-03-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0081_auto_20210319_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='pulso1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPulsoDetEvCartillaDrenado1', to='evaluaciones.SelectorPulsoDetEvCartillaDrenado'),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ubicacion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiDetEvCartillaDrenado1', to='evaluaciones.SelectorUbiDetEvCartillaDrenado'),
        ),
    ]
