# Generated by Django 2.2.6 on 2021-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0082_auto_20210319_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcartilladrenado',
            name='pulso',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valvua'),
        ),
        migrations.AlterField(
            model_name='detalleevcartilladrenado',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valva'),
        ),
    ]
