# Generated by Django 2.2.6 on 2021-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0083_auto_20210319_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='hola',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valvua'),
        ),
    ]
