# Generated by Django 2.2.6 on 2021-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0084_detalleevcartilladrenado_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='hola',
        ),
    ]
