# Generated by Django 2.2.6 on 2021-03-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0085_remove_detalleevcartilladrenado_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='pulso1',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='tiempo_riego',
        ),
    ]
