# Generated by Django 2.2.6 on 2021-04-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0086_auto_20210324_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ce_gotero',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ce_sonda',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ph_gotero',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ph_sonda',
        ),
    ]
