# Generated by Django 2.2.6 on 2021-04-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0087_auto_20210428_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='detalleevcartilladrenado',
            name='ubicacion1',
        ),
    ]
