# Generated by Django 2.2.6 on 2021-04-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0088_auto_20210428_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleevcartilladrenado',
            old_name='caudal_real',
            new_name='volumen_maceta',
        ),
    ]
