# Generated by Django 2.2.6 on 2021-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0089_auto_20210428_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_1f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_1m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_2f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_2i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_2m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_3f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_3i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_drenado_3m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_1f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_1m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_2f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_2i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_2m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_3f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_3i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='volumen_maceta_3m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
