# Generated by Django 2.2.6 on 2021-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0090_auto_20210428_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_1f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_1m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_2f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_2i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_2m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_3f',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_3i',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcartilladrenado',
            name='ce_3m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
