# Generated by Django 2.2.6 on 2021-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0091_auto_20210429_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorDistribucionPoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Distribucion')),
            ],
            options={
                'verbose_name': 'Selector Distribucion Ev. Cal Poda ',
                'verbose_name_plural': 'Selector Distribucion Ev. Cal Poda',
            },
        ),
        migrations.CreateModel(
            name='SelectorTCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='TCalidad')),
            ],
            options={
                'verbose_name': 'Selector TCalidad Ev. Cal Poda ',
                'verbose_name_plural': 'Selector TCalidad Ev. Cal Poda',
            },
        ),
        migrations.CreateModel(
            name='SelTipoTrabajadorEvCalPodaAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo Trabajador')),
            ],
            options={
                'verbose_name': 'Selector Tipo Trabajador Ev. Cal Poda ',
                'verbose_name_plural': 'Selector Tipo Trabajador Ev. Cal Poda',
            },
        ),
        migrations.CreateModel(
            name='SelTrabajadorEvCalPodaAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trabajador')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoTrabajadorEvCalPodaAr', to='evaluaciones.SelTipoTrabajadorEvCalPodaAr')),
            ],
            options={
                'verbose_name': 'Selector Trabajador Ev. Cal Poda ',
                'verbose_name_plural': 'Selector Trabajador Ev. Cal Poda',
            },
        ),
        migrations.CreateModel(
            name='EvCalPodaAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoEvCalPodaAr', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvCalPodaAr', to='menu.fundo')),
                ('anexo_trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTrabajadorEvCalPodaAr', to='evaluaciones.SelTrabajadorEvCalPodaAr')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEvCalPodaAr', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalPodaAr', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalPodaAr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Cal Poda Arandano',
                'verbose_name_plural': 'Ev. Cal Poda Arandano',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalPodaAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Detalle Ev Cal Poda')),
                ('dni', models.BigIntegerField(blank=True, null=True)),
                ('valvula', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valvula')),
                ('num_ramas', models.IntegerField(blank=True, null=True)),
                ('ramas_sinyema', models.IntegerField(blank=True, null=True)),
                ('ramas_cruzados', models.IntegerField(blank=True, null=True)),
                ('ramas_daniocorte', models.IntegerField(blank=True, null=True)),
                ('ramas_delgados5', models.IntegerField(blank=True, null=True)),
                ('ramas_delgados8', models.IntegerField(blank=True, null=True)),
                ('ramas_flujo3', models.IntegerField(blank=True, null=True)),
                ('corte_recto', models.IntegerField(blank=True, null=True)),
                ('altura_rama', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalPodaAr', to='evaluaciones.EvCalPodaAr')),
                ('anexo_distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDistribucionEvCalPodaAr', to='evaluaciones.SelectorDistribucionPoda')),
                ('anexo_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPProduccionEvCalPodaAr', to='menu.ProgramaProduccion')),
                ('anexo_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEvCalPodaAr', to='evaluaciones.SelTrabajadorEvCalPodaAr')),
                ('anexo_tcalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTCalidadEvCalPodaAr', to='evaluaciones.SelectorTCalidad')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadEvCalPodaAr', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleEvCalPodaAr', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleEvCalPodaAr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Cal Poda Arandano',
                'verbose_name_plural': 'Ev. Cal Poda Arandano',
            },
        ),
    ]
