# Generated by Django 2.2.6 on 2021-06-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0093_auto_20210602_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleevcalpodaar',
            options={'verbose_name': 'Detalle Ev. Cal Poda Arandano', 'verbose_name_plural': 'Detalle Ev. Cal Poda Arandano'},
        ),
    ]
