# Generated by Django 2.2.6 on 2021-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0094_auto_20210602_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalpodaar',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
