# Generated by Django 2.2.6 on 2021-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0095_evcalpodaar_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalpodaar',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
