# Generated by Django 2.2.6 on 2021-06-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0096_auto_20210602_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalpodaar',
            name='fecha',
        ),
    ]
