# Generated by Django 2.2.6 on 2021-08-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0098_evcalacopioplantaarcaraz2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcaldefectoscampo',
            name='otros',
        ),
    ]
