# Generated by Django 2.2.6 on 2021-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0099_remove_detalleevcaldefectoscampo_otros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcaldefectoscampo',
            name='observacion',
        ),
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='heridas',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='restos_florales',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
