# Generated by Django 2.2.6 on 2021-08-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0101_evcalacopioplantaarica2021_selectortipofirmeza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcalacopioplantaarica2021',
            name='fecha_hora_modificacion',
        ),
        migrations.RemoveField(
            model_name='evcalacopioplantaarica2021',
            name='usuario_modificacion',
        ),
    ]
