# Generated by Django 2.2.6 on 2021-09-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0102_auto_20210831_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorCasetaCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Caseta Calidad-Ev. Calidad',
                'verbose_name_plural': 'Selector  Caseta Calidad -Ev. Calidad',
            },
        ),
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='anexo_caseta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCasetaEvCal', to='evaluaciones.SelectorCasetaCalidad'),
        ),
    ]
