# Generated by Django 2.2.6 on 2021-09-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0103_auto_20210921_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorNroEvalCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Nro Eval Calidad-Ev. Calidad',
                'verbose_name_plural': 'Selector  Nro Eval Calidad -Ev. Calidad',
            },
        ),
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='anexo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoNroEvCal', to='evaluaciones.SelectorNroEvalCalidad'),
        ),
    ]
