# Generated by Django 2.2.6 on 2021-10-13 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0183_hitosfenologicos_anexo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0008_auxiliarescampoathos'),
        ('evaluaciones', '0104_auto_20210922_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalMuestreoCosechaHg2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoMuestreoCosechaHg2021', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaMuestreoCosechaHg2021', to='menu.ejezona')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvCalMuestreoCosechaHg2021', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalMuestreoCosechaHg2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalMuestreoCosechaHg2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Cosecha Higo 2021 ',
                'verbose_name_plural': 'Ev. Calidad Cosecha Higo 2021',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalMuestreoCosechaHg2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula', models.CharField(blank=True, max_length=300, null=True, verbose_name='Valvula')),
                ('dni', models.BigIntegerField(blank=True, null=True)),
                ('densidad', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reingreso', models.IntegerField(blank=True, null=True)),
                ('nfrutas', models.IntegerField(blank=True, null=True)),
                ('inmaduro', models.IntegerField(blank=True, null=True)),
                ('sobremaduro', models.IntegerField(blank=True, null=True)),
                ('mal_corte', models.IntegerField(blank=True, null=True)),
                ('danio_mecanico', models.IntegerField(blank=True, null=True)),
                ('latex', models.IntegerField(blank=True, null=True)),
                ('optimo', models.IntegerField(blank=True, null=True)),
                ('fruta_suelo', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_auxiliares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxiliarEvCalHg2021', to='maestras.AuxiliaresCampoAthos')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalHg2021', to='evaluaciones.EvCalMuestreoCosechaHg2021')),
                ('anexo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEvCalHg2021', to='evaluaciones.SelectorTipoCalidad')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadEvCalHg2021', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalHg2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalHg2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Ev.Calidad Muestreo Cosecha Higo 2021',
                'verbose_name_plural': 'Detalle Ev. Calidad Muestreo cosecha higo 2021',
            },
        ),
    ]
