# Generated by Django 2.2.6 on 2021-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0106_auto_20211022_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmuestreocosechahg2021',
            name='exportable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
