# Generated by Django 2.2.6 on 2021-11-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0108_detalleevcalmuestreoplantahgica2021_evcalmuestreoplantahgica2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalmuestreoplantahgica2021',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Ingreso'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgica2021',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
    ]
