# Generated by Django 2.2.6 on 2021-12-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0109_auto_20211123_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorEstadiosCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Estadios')),
            ],
            options={
                'verbose_name': 'Selector Estadios Calidad ',
                'verbose_name_plural': 'Selector Estadios Calidad',
            },
        ),
        migrations.CreateModel(
            name='SelectorFirmezaCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmeza')),
            ],
            options={
                'verbose_name': 'Selector Firmeza Calidad ',
                'verbose_name_plural': 'Selector Firmeza Calidad',
            },
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='brix1',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='brix2',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='brix3',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_brix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_brix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_brix3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1F', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadi2F', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_estadio_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3F', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1Firmeza', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2Firmeza', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreoplantahgica2021',
            name='anexo_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3Firmeza', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
    ]
