# Generated by Django 2.2.6 on 2021-12-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0184_auto_20211021_1332'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0110_auto_20211201_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalBrixGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Enfriado')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoBrixCUltivoGrIca2021', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoBrixGrIca2021', to='menu.fundo')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadMrixGrIca2021', to='menu.variedad')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaBrixGrIca2021', to='menu.ejezona')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvCalrixGrIca2021', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalBrixGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalBrixGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Brix Granada Ica 2021 ',
                'verbose_name_plural': 'Ev. Calidad Brix Granada Ica 2021',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalBrixGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('diametro', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('color_interno', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('color_externo', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('brix', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('gasto_naoh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('acidez', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('indice_madurez', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvcalBrixGrIca2021', to='evaluaciones.EvCalBrixGrIca2021')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalBrixGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalBrixGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Ev.Calidad Brix Gr- 2021',
                'verbose_name_plural': 'Detalle Ev. Calidad Brix Gr- 2021',
            },
        ),
    ]
