# Generated by Django 2.2.6 on 2021-12-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0184_auto_20211021_1332'),
        ('evaluaciones', '0111_detalleevcalbrixgrica2021_evcalbrixgrica2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_valvula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoValvulaEvCalPodaAr', to='menu.TurnoProgramaProduccion'),
        ),
    ]
