# Generated by Django 2.2.6 on 2021-12-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0112_detalleevcalpodaar_anexo_valvula'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='diametro_polar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
