# Generated by Django 2.2.6 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0113_detalleevcalbrixgrica2021_diametro_polar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorRespuestaEscalaCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta Escala')),
            ],
            options={
                'verbose_name': 'Selector Respuesta Escala Calidad ',
                'verbose_name_plural': 'Selector Respuesta Escala Calidad',
            },
        ),
        migrations.CreateModel(
            name='SelectorRespuestaSiNoCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta SiNO')),
            ],
            options={
                'verbose_name': 'Selector Respuesta SiNO Calidad ',
                'verbose_name_plural': 'Selector Respuesta SiNO Calidad',
            },
        ),
    ]
