# Generated by Django 2.2.6 on 2021-12-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0114_selectorrespuestaescalacalidad_selectorrespuestasinocalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_preg1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPREG1EvCalPodaAr', to='evaluaciones.SelectorRespuestaSiNoCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_preg2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPREG2EvCalPodaAr', to='evaluaciones.SelectorRespuestaEscalaCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_preg3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPREG3EvCalPodaAr', to='evaluaciones.SelectorRespuestaSiNoCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_preg4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPREG4EvCalPodaAr', to='evaluaciones.SelectorRespuestaEscalaCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='anexo_preg5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPREG5EvCalPodaAr', to='evaluaciones.SelectorRespuestaSiNoCalidad'),
        ),
    ]
