# Generated by Django 2.2.6 on 2021-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0115_auto_20211214_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='num_tirasavias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
