# Generated by Django 2.2.6 on 2021-12-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0116_detalleevcalpodaar_num_tirasavias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalpodaar',
            name='ramas_delgados8',
        ),
        migrations.RemoveField(
            model_name='detalleevcalpodaar',
            name='ramas_sinyema',
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='num_ramas_debajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='num_ramas_encima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
