# Generated by Django 2.2.6 on 2021-12-21 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0012_tipocalidadfruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0184_auto_20211021_1332'),
        ('evaluaciones', '0117_auto_20211220_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='anexo_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoPPEvCalrixGrIca2021', to='menu.TurnoProgramaProduccion'),
        ),
        migrations.CreateModel(
            name='EvCalMmppGrIca2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npalet', models.IntegerField(blank=True, null=True)),
                ('anexo_fundo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundo')),
                ('anexo_fecha_cosecha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fecha Cosecha')),
                ('anexo_nro_guia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nro Guia')),
                ('anexo_pep', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pep')),
                ('anexo_variedad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variedad')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluacion')),
                ('temperatura_pulpa', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('peso_muestra', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_tipocalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoMmppGrIca2021', to='granada.TipoCalidadFruta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalMmppGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalMmppGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Materia Prima Granada Ica 2021 ',
                'verbose_name_plural': 'Ev. Calidad Materia Prima Granada Ica 2021',
            },
        ),
    ]
