# Generated by Django 2.2.6 on 2021-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0118_auto_20211221_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector'),
        ),
    ]
