# Generated by Django 2.2.6 on 2022-01-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0120_detalleevcalmmppgrica2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='pudricion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
