# Generated by Django 2.2.6 on 2022-01-18 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0012_lineasplanta'),
        ('menu', '0185_auto_20220108_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0121_detalleevcaldefectoscampo_pudricion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalControlDescarteGrIca2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluacion')),
                ('controlador_prod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Controladora Produccion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLineasDescGrIca2021', to='granada_planta.LineasPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Control Descarte Granada Ica 2022 ',
                'verbose_name_plural': 'Ev. Calidad Control Descarte Granada Ica 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalControlDescarteGrIca2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inspeccion', models.TimeField(blank=True, null=True, verbose_name='Hora Inspeccion')),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('anexo_proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('cat1_exportable', models.IntegerField(blank=True, null=True)),
                ('cat2_exportable', models.IntegerField(blank=True, null=True)),
                ('catind_exportable', models.IntegerField(blank=True, null=True)),
                ('rajadas_ae', models.IntegerField(blank=True, null=True)),
                ('rajadas_golpe', models.IntegerField(blank=True, null=True)),
                ('insolacion_fuerte', models.IntegerField(blank=True, null=True)),
                ('danio_mecanico', models.IntegerField(blank=True, null=True)),
                ('bajo_peso', models.IntegerField(blank=True, null=True)),
                ('danio_roedor', models.IntegerField(blank=True, null=True)),
                ('alternaria', models.IntegerField(blank=True, null=True)),
                ('cochinilla', models.IntegerField(blank=True, null=True)),
                ('inmadures_verde', models.IntegerField(blank=True, null=True)),
                ('gelechi', models.IntegerField(blank=True, null=True)),
                ('pudricion', models.IntegerField(blank=True, null=True)),
                ('hongo_corona', models.IntegerField(blank=True, null=True)),
                ('quereza', models.IntegerField(blank=True, null=True)),
                ('golpe_fuerte', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='observacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleDescGrIca2021', to='evaluaciones.EvCalControlDescarteGrIca2022')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadDescGrIca2021', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalControlDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalControlDescarteGrIca2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev.Calidad Det Control Descarte Granada Ica 2022 ',
                'verbose_name_plural': 'Ev. Calidad Det Control Descarte Granada Ica 2022',
            },
        ),
    ]
