# Generated by Django 2.2.6 on 2022-01-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0123_auto_20220118_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='anexo_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaDescGrIca2021', to='menu.fundo'),
        ),
    ]
