# Generated by Django 2.2.6 on 2022-01-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0124_auto_20220118_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat1_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat1_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat1_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_cicatriz_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_cicatriz_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_cicatriz_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_danio_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_danio_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_danio_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deformes_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deformes_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deformes_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deshidratadol_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deshidratadol_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_deshidratadol_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_insolacion_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_insolacion_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_insolacion_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_manchas_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_manchas_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_manchas_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_palidas_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_palidas_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_palidas_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_pedunculo_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_pedunculo_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_pedunculo_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_rajadas_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_rajadas_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_rajadas_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_recuperable_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_recuperable_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_recuperable_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_russet_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_russet_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_russet_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_thrips_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_thrips_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cat2_thrips_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cati_rajada_sa_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cati_rajada_sa_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='cati_rajada_sa_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_botritis_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_botritis_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_botritis_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_cochinilla_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_cochinilla_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_cochinilla_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_deshisev_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_deshisev_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_deshisev_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_gelechi_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_gelechi_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_gelechi_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_hongosi_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_hongosi_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_hongosi_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_inmadurez_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_inmadurez_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_inmadurez_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_insolacion_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_insolacion_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_insolacion_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_magullado_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_magullado_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_magullado_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_moscaf_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_moscaf_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_moscaf_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pudricion_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pudricion_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pudricion_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_quereza_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_quereza_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_quereza_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_rajadasae_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_rajadasae_22',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_rajadasae_24',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
