# Generated by Django 2.2.6 on 2022-01-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0125_auto_20220120_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_10',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_12',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_14',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_16',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_18',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_20',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_22',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_24',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_5',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_6',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_7',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_8',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='desc_pesome_9',
        ),
    ]
