# Generated by Django 2.2.6 on 2022-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0126_auto_20220120_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleevcalmmppgrica2021',
            options={'verbose_name': 'Detalle Ev. Calidad Materia Prima Granada Ica 2022 ', 'verbose_name_plural': 'Detalle Ev. Calidad Materia Prima Granada Ica 2022'},
        ),
        migrations.AlterModelOptions(
            name='evcalmmppgrica2021',
            options={'verbose_name': 'Ev. Calidad Materia Prima Granada Ica 2022 ', 'verbose_name_plural': 'Ev. Calidad Materia Prima Granada Ica 2022'},
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='botrytis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='cicatriz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='corona_deshidratada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='danio_ave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='danio_mecanico_pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='deforme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='golpe_fuerte_pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='insolacion_leve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='manchas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='pudricion_corona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='rajada_severo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='rajadas_golpe_pl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='rajadas_hongos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartegrica2022',
            name='russet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
