# Generated by Django 2.2.6 on 2022-01-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0127_auto_20220120_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlveoloCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Desc de Material')),
            ],
            options={
                'verbose_name': 'Selector Tipo de Alveolo -Ev. Calidad',
                'verbose_name_plural': 'Selector Tipo de Alveolo  -Ev. Calidad',
            },
        ),
        migrations.CreateModel(
            name='TipoBolsaCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
            ],
            options={
                'verbose_name': 'Selector Tipo de Bolsa-Ev. Calidad',
                'verbose_name_plural': 'Selector  Tipo de Bolsa -Ev. Calidad',
            },
        ),
        migrations.CreateModel(
            name='MaterialesCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de Material')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_alveolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.TipoAlveoloCalidad')),
                ('anexo_bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.TipoBolsaCalidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMatEvCalidad2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMatEvCalidad2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materiales Calidad- Ev. Calidad',
                'verbose_name_plural': 'Materiales Calidad -Ev. Calidad',
            },
        ),
    ]
