# Generated by Django 2.2.6 on 2022-01-25 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0012_lineasplanta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0128_materialescalidad_tipoalveolocalidad_tipobolsacalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalControlPesosGrIca2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('supervisor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supervisor Linea')),
                ('inspector', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inspector Calidad')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granada_planta.LineasPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalControlPesoGrIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalControlPesoGrIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Control Pesos Gr Ica 2022',
                'verbose_name_plural': 'Ev. Calidad Control Pesos Gr Ica 2022',
            },
        ),
    ]
