# Generated by Django 2.2.6 on 2022-01-26 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0008_auxiliarescampoathos'),
        ('evaluaciones', '0129_evcalcontrolpesosgrica2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvCalControlPesosGrIca2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de la caja')),
                ('hora_evaluacion', models.TimeField(blank=True, null=True, verbose_name='Hora Evaluacion')),
                ('peso_neto1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto3', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto4', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto5', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto6', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto7', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto8', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto9', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('peso_neto10', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calibre1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal1EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal10EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal2EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal3EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal4EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal5EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal6EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal7EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal8EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_calibre9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCal9EvCalPeso2022', to='maestras.CalibresAthos')),
                ('anexo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestras.ClientesAthos')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.EvCalControlDescarteGrIca2022')),
                ('anexo_presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.MaterialesCalidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalControlPesoGrIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalControlPesoGrIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Det-Ev. Calidad Control Pesos Gr Ica 2022',
                'verbose_name_plural': 'Det-Ev. Calidad Control Pesos Gr Ica 2022',
            },
        ),
    ]
