# Generated by Django 2.2.6 on 2022-01-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0130_detalleevcalcontrolpesosgrica2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionMaterialCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
            ],
            options={
                'verbose_name': 'Selector Presentacio Material -Ev. Calidad',
                'verbose_name_plural': 'Selector  Presentacio Material  -Ev. Calidad',
            },
        ),
    ]
