# Generated by Django 2.2.6 on 2022-01-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0131_presentacionmaterialcalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='anexo_presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.PresentacionMaterialCalidad'),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.MaterialesCalidad'),
        ),
    ]
