# Generated by Django 2.2.6 on 2022-01-31 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0185_auto_20220108_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0132_auto_20220127_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvPlantonesPlNaz2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('hora_evaluacion', models.TimeField(blank=True, null=True, verbose_name='Hora Evaluacion')),
                ('supervisor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Supervisor Linea')),
                ('n_personas', models.CharField(blank=True, max_length=4, null=True, verbose_name='Personas Sembrando')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.fundo')),
                ('anexo_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ProgramaProduccion')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.TurnoProgramaProduccion')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvPlantPaltaIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvPlantPaltaIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Plantones de Palta Ica 2022',
                'verbose_name_plural': 'Ev. Plantones de Palta Ica 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvPlantonesPlNaz2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del Personal')),
                ('promedio_planta', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('observacion', models.CharField(blank=True, max_length=70, null=True, verbose_name='Observación')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.EvPlantonesPlNaz2022')),
                ('buen_siembra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buen_Siembra', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('presencia_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Presencia_Planta', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('presencia_suelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Presencia_Suelo', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('primera_ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Primera_Ausencia', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('segunda_ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Segunda_Ausencia', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('siembra_profunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Siembra_Profundo', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('tercera_ausencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tercera_Ausencia', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('tutor_posicionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tutor_Posicionado', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvPlantPaltaIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvPlantPaltaIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Det-Ev. Plantones de Palta Nazca 2022',
                'verbose_name_plural': 'Det-Ev. Plantones de Palta Nazca 2022',
            },
        ),
    ]
