# Generated by Django 2.2.6 on 2022-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0133_detalleevplantonesplnaz2022_evplantonesplnaz2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='fit_pulgon_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='fit_pulgon_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='fit_pulgon_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplanta',
            name='fit_pulgon_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
