# Generated by Django 2.2.6 on 2022-02-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0135_auto_20220201_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.EvCalControlPesosGrIca2022'),
        ),
    ]
