# Generated by Django 2.2.6 on 2022-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0136_auto_20220208_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_externa25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_externa35',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_interna25',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_interna35',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
