# Generated by Django 2.2.6 on 2022-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0137_auto_20220209_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='color_interna25',
        ),
        migrations.RemoveField(
            model_name='detalleevcalmmppgrica2021',
            name='color_interna35',
        ),
    ]
