# Generated by Django 2.2.6 on 2022-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0138_auto_20220210_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext1_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext1_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext1_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext1_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext1_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext25_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext25_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext25_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext25_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext25_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext2_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext2_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext2_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext2_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext2_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext35_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext35_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext35_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext35_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext35_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext3_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext3_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext3_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext3_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext3_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext4_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext4_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext4_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext4_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext4_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext5_int1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext5_int2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext5_int3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext5_int4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmmppgrica2021',
            name='color_ext5_int5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
