# Generated by Django 2.2.6 on 2022-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0139_auto_20220210_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto6',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto7',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto8',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontrolpesosgrica2022',
            name='peso_neto9',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
