# Generated by Django 2.2.6 on 2022-02-18 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0008_auxiliarescampoathos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0140_auto_20220210_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorCategoriaCalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta Categoria')),
            ],
            options={
                'verbose_name': 'Selector Respuesta Categoria Calidad ',
                'verbose_name_plural': 'Selector Respuesta Categoria Calidad',
            },
        ),
        migrations.CreateModel(
            name='EvMuestrasCajasEmpacadasGR2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('responsable', models.IntegerField(blank=True, null=True, verbose_name='Inspector / Supervisor')),
                ('npalet', models.IntegerField(blank=True, null=True, unique=True)),
                ('hora_inspeccion', models.TimeField(blank=True, null=True, verbose_name='Hora Inspeccion')),
                ('marca_caja', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca de Caja')),
                ('variedad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Variedad')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca / Tipo de Bolsa')),
                ('marca_sticker', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de Sticker')),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proveedor/Fundo')),
                ('fecha_cosecha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fecha de Cosecha')),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalibreCajasEmpacadasGrIca2022', to='maestras.CalibresAthos')),
                ('anexo_categoria', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.SelectorCategoriaCalidad')),
                ('anexo_corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCorteCajasEmpacadasGrIca2022', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('anexo_sobrepeso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSobrepesoCajasEmpacadasGrIca2022', to='evaluaciones.SelectorRespuestaSiNoCalidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvMuestrasCajasEmpacadasGR2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvMuestrasCajasEmpacadasGR2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Muestras de Cajas Empacadas Gr Ica 2022',
                'verbose_name_plural': 'Ev. Muestras de Cajas Empacadas Gr Ica 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvMuestrasCajasEmpacadasGR2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cicatriz_cat1', models.IntegerField(blank=True, null=True, verbose_name='Cicatrices')),
                ('danio_roce_cat1', models.IntegerField(blank=True, null=True, verbose_name='Daño por Roce')),
                ('deformes_cat1', models.IntegerField(blank=True, null=True, verbose_name='Deformes')),
                ('insolacion_leve_cat1', models.IntegerField(blank=True, null=True, verbose_name='Insolación Leve')),
                ('libre_defectos_cat1', models.IntegerField(blank=True, null=True, verbose_name='Libre de Defectos')),
                ('manchas_cat1', models.IntegerField(blank=True, null=True, verbose_name='Manchas')),
                ('rajaduras_cat1', models.IntegerField(blank=True, null=True, verbose_name='Rajaduras')),
                ('suma_cat1', models.IntegerField(blank=True, null=True, verbose_name='Total de Cat1')),
                ('insolacion_moderada_cat2', models.IntegerField(blank=True, null=True, verbose_name='Insolación Moderada')),
                ('cicatriz_cat2', models.IntegerField(blank=True, null=True, verbose_name='Cicatrices')),
                ('corona_deshidratada_cat2', models.IntegerField(blank=True, null=True, verbose_name='Corona Deshidratada Leve')),
                ('danio_mecanico_cat2', models.IntegerField(blank=True, null=True, verbose_name='Daño Mecanico')),
                ('danio_roce_cat2', models.IntegerField(blank=True, null=True, verbose_name='Daño por Roce')),
                ('golpe_leve_cat2', models.IntegerField(blank=True, null=True, verbose_name='Golpe Leve')),
                ('manchas_cat2', models.IntegerField(blank=True, null=True, verbose_name='Manchas')),
                ('rajaduras_cat2', models.IntegerField(blank=True, null=True, verbose_name='Rajaduras')),
                ('suma_cat2', models.IntegerField(blank=True, null=True, verbose_name='Total de Cat2')),
                ('cicatriz_industrial', models.IntegerField(blank=True, null=True, verbose_name='Cicatrices')),
                ('danio_roce_industrial', models.IntegerField(blank=True, null=True, verbose_name='Daño por Roce')),
                ('manchas_industrial', models.IntegerField(blank=True, null=True, verbose_name='Manchas')),
                ('rajaduras_industrial', models.IntegerField(blank=True, null=True, verbose_name='Rajaduras')),
                ('suma_industrial', models.IntegerField(blank=True, null=True, verbose_name='Total de Industrial')),
                ('arilo_expuesto_descarte', models.IntegerField(blank=True, null=True, verbose_name='Arilo Expuesto')),
                ('corona_deshidratada_descarte', models.IntegerField(blank=True, null=True, verbose_name='Corona Deshidratada')),
                ('danio_plagas_descarte', models.IntegerField(blank=True, null=True, verbose_name='Daño por Plagas')),
                ('golpe_fuerte_descarte', models.IntegerField(blank=True, null=True, verbose_name='Golpe Fuerte')),
                ('insolado_fuerte_descarte', models.IntegerField(blank=True, null=True, verbose_name='Insolado Fuerte')),
                ('pudricion_descarte', models.IntegerField(blank=True, null=True, verbose_name='Pudricion')),
                ('rajados_severos_descarte', models.IntegerField(blank=True, null=True, verbose_name='Rajados Severos')),
                ('suma_descarte', models.IntegerField(blank=True, null=True, verbose_name='Total de Descarte')),
                ('unidades_totales_muestreadas', models.IntegerField(blank=True, null=True, verbose_name='Unidades Totales Muestreadas')),
                ('porcentajes_totales_muestreados', models.CharField(blank=True, max_length=10, null=True, verbose_name='Porcentajes Totales Muestreados')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.EvMuestrasCajasEmpacadasGR2022')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleEvMuestrasCajasEmpacadasGR2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleEvMuestrasCajasEmpacadasGR2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Det-Ev. Muestras de Cajas Empacadas Gr Ica 2022',
                'verbose_name_plural': 'Det-Ev. Muestras de Cajas Empacadas Gr Ica 2022',
            },
        ),
    ]
