# Generated by Django 2.2.6 on 2022-02-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0186_programaproduccion_inicio_campana'),
        ('evaluaciones', '0141_detalleevmuestrascajasempacadasgr2022_evmuestrascajasempacadasgr2022_selectorcategoriacalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalcontrolpesosgrica2022',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.TurnoProgramaProduccion'),
        ),
    ]
