# Generated by Django 2.2.6 on 2022-02-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0142_evcalcontrolpesosgrica2022_anexo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalcontrolpesosgrica2022',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Turno'),
        ),
    ]
