# Generated by Django 2.2.6 on 2022-02-21 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0186_programaproduccion_inicio_campana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0143_auto_20220221_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvControlDescarteGR2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(blank=True, null=True, verbose_name='Fecha Proceso')),
                ('material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Material')),
                ('santiaguillo', models.IntegerField(blank=True, null=True, verbose_name='Santiaguillo')),
                ('santiago_apostol', models.IntegerField(blank=True, null=True, verbose_name='Santiago Apostol')),
                ('los_pobres', models.IntegerField(blank=True, null=True, verbose_name='Los Pobres')),
                ('macacara', models.IntegerField(blank=True, null=True, verbose_name='Macacara')),
                ('santa_filomena', models.IntegerField(blank=True, null=True, verbose_name='Santa Filomena')),
                ('parcelas', models.IntegerField(blank=True, null=True, verbose_name='Parcelas')),
                ('sojo', models.IntegerField(blank=True, null=True, verbose_name='Sojo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvControlDescarteGR2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvControlDescarteGR2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Control Descarte GR Ica 2022',
                'verbose_name_plural': 'Ev. Control Descarte GR Ica 2022',
            },
        ),
    ]
