# Generated by Django 2.2.6 on 2022-02-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0144_evcontroldescartegr2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='raicesevfenraicesarandanos',
            name='rfjb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
