# Generated by Django 2.2.6 on 2022-02-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0145_raicesevfenraicesarandanos_rfjb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MaterialMMPP'),
        ),
    ]
