# Generated by Django 2.2.6 on 2022-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0146_auto_20220222_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcontroldescartegr2022',
            name='total_descarte',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='los_pobres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Los Pobres'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='macacara',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Macacara'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='parcelas',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='santa_filomena',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Santa Filomena'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='santiago_apostol',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Santiago Apostol'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='santiaguillo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Santiaguillo'),
        ),
        migrations.AlterField(
            model_name='evcontroldescartegr2022',
            name='sojo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sojo'),
        ),
    ]
