# Generated by Django 2.2.6 on 2022-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0147_auto_20220223_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalmuestreocosechahg2021',
            name='valvula',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sector'),
        ),
    ]
