# Generated by Django 2.2.6 on 2022-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0149_auto_20220310_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
