# Generated by Django 2.2.6 on 2022-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0150_auto_20220319_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
