# Generated by Django 2.2.6 on 2022-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0151_auto_20220319_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
