# Generated by Django 2.2.6 on 2022-03-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0152_auto_20220319_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcaldefectoscampo',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
