# Generated by Django 2.2.6 on 2022-04-29 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        ('evaluaciones', '0154_auto_20220319_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamaPlantaEvFenRamasArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('num_ramas', models.IntegerField(blank=True, null=True)),
                ('primera_poda', models.IntegerField(blank=True, null=True)),
                ('segunda_poda', models.IntegerField(blank=True, null=True)),
                ('tercera_poda', models.IntegerField(blank=True, null=True)),
                ('cuarta_poda', models.IntegerField(blank=True, null=True)),
                ('quinta_poda', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalleRamas', to='evaluaciones.DetallePlantaEvFenBrotesArandanos')),
                ('anexo_diametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.NDiametro')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRamas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvRamas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fen. Ramas Detalle Planta Arandanos',
                'verbose_name_plural': 'Ev. Fen. Ramas Detalle Planta  Arandanos',
            },
        ),
        migrations.CreateModel(
            name='EvFenRamasArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Enfriado')),
                ('valvula', models.CharField(max_length=30, verbose_name='Valvula')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvRamas', to='menu.fundo')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEVRamas', to='evaluaciones.TipoEvaluacionBr')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEvRamas', to='menu.ejezona')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvRamas', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvFenRamas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvFenRamas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Fenologia Ramas Arandanos',
                'verbose_name_plural': 'Ev. Fenologia Ramas Arandanos',
            },
        ),
        migrations.CreateModel(
            name='DetallePlantaEvFenRamasArandanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_planta', models.IntegerField(blank=True, null=True)),
                ('cant_ramas', models.IntegerField(blank=True, null=True)),
                ('ramas_produccion', models.IntegerField(blank=True, null=True)),
                ('tira_savia', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalle', to='evaluaciones.EvFenRamasArandanos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetPlantaRamas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvDetPlantaRamas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Ev. Fen. Ramas Detalle Planta Arandanos ',
                'verbose_name_plural': 'Detalle-Ev. Fen. Ramas Detalle Planta  Arandanos',
            },
        ),
    ]
