# Generated by Django 2.2.6 on 2022-04-29 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0155_detalleplantaevfenramasarandanos_evfenramasarandanos_ramaplantaevfenramasarandanos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramaplantaevfenramasarandanos',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEVDetalleRamas', to='evaluaciones.DetallePlantaEvFenRamasArandanos'),
        ),
    ]
