# Generated by Django 2.2.6 on 2022-05-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0156_auto_20220429_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacionRm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo evaluacion ramas')),
            ],
            options={
                'verbose_name': 'Tipo EV. Ramas',
                'verbose_name_plural': 'Tipo EV. Ramas',
            },
        ),
        migrations.AlterField(
            model_name='evfenramasarandanos',
            name='anexo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEVRamas', to='evaluaciones.TipoEvaluacionRm'),
        ),
    ]
