# Generated by Django 2.2.6 on 2022-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0157_auto_20220502_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='bajo_calibre',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
