# Generated by Django 2.2.6 on 2022-06-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0158_detalleevcaldefectoscampo_bajo_calibre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorTipoEnvase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Tipo de Envase Calidad-Ev. Calidad',
                'verbose_name_plural': 'Selector  Tipo de Envase Calidad -Ev. Calidad',
            },
        ),
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='anexo_tipo_envase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEnvaseEvCal', to='evaluaciones.SelectorTipoEnvase'),
        ),
    ]
