# Generated by Django 2.2.6 on 2022-07-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0160_evcalacopioplantaarcaraz202202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorTipoEnvasePlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Tipo de Envase Calidad-Ev. Calidad Planta',
                'verbose_name_plural': 'Selector  Tipo de Envase Calidad -Ev. Calidad Planta',
            },
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_picadura_ave_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_picadura_ave_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_picadura_ave_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_picadura_ave_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='anexo_tipo_envase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEnvasePlantaEvCal', to='evaluaciones.SelectorTipoEnvasePlanta'),
        ),
    ]
