# Generated by Django 2.2.6 on 2022-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0162_evcalacopioplantaarica202202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m10_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m10_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m10_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m10_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m11_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m11_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m11_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m11_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m12_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m12_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m12_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m12_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m13_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m13_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m13_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m13_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m14_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m14_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m14_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m14_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m15_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m15_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m15_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m15_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m1_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m1_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m1_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m1_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m2_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m2_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m2_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m2_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m3_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m3_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m3_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m3_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m4_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m4_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m4_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m4_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m5_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m5_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m5_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m5_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m6_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m6_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m6_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m6_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m7_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m7_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m7_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m7_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m8_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m8_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m8_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m8_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m9_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m9_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m9_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evcalacopioplantaarica202202',
            name='fir_m9_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
