# Generated by Django 2.2.6 on 2022-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0163_auto_20220716_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcontroldescartegr2022',
            name='las_dunas',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Las Dunas'),
        ),
    ]
