# Generated by Django 2.2.6 on 2022-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0164_evcontroldescartegr2022_las_dunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='cochinilla',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
