# Generated by Django 2.2.6 on 2022-08-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0165_detalleevcaldefectoscampo_cochinilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacionAr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo ev')),
            ],
            options={
                'verbose_name': 'Tipo EV Arandano',
                'verbose_name_plural': 'Tipo EV Arandano',
            },
        ),
        migrations.CreateModel(
            name='EvCalControlDescarteAr2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluacion')),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('cantidad_muestra', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvDescarteAr2022', to='menu.fundo')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEvDescarteAr2022', to='evaluaciones.TipoEvaluacionAr')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoDescarteAr2022', to='menu.Turno')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadDescarteAr2022', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalDescarteArIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalDescarteArIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Control Descarte Arandano Ica 2022 ',
                'verbose_name_plural': 'Ev. Calidad Control Descarte Arandano Ica 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalControlDescarteAr2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportable1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('exportable2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('exportable3', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('exportable4', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion3', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion4', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion5', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion6', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion7', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion8', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion9', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion10', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion11', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion12', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('condicion13', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad3', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad4', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad5', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad6', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad7', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad8', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad9', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad10', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad11', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calidad12', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fitosanitario1', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fitosanitario2', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fitosanitario3', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fitosanitario4', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fitosanitario5', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleDescArIca2022', to='evaluaciones.EvCalControlDescarteAr2022')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalControlDescarteArIca2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalControlDescarteArIca2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev.Calidad Det Control Descarte Arandano Ica 2022 ',
                'verbose_name_plural': 'Ev. Calidad Det Control Descarte Arandano Ica 2022',
            },
        ),
    ]
