# Generated by Django 2.2.6 on 2022-08-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0166_detalleevcalcontroldescartear2022_evcalcontroldescartear2022_tipoevaluacionar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='exportable1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='exportable2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='exportable3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='exportable4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='fitosanitario1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='fitosanitario2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='fitosanitario3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='fitosanitario4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartear2022',
            name='fitosanitario5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evcalcontroldescartear2022',
            name='cantidad_muestra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
