# Generated by Django 2.2.6 on 2022-08-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0167_auto_20220826_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion13',
        ),
    ]
