# Generated by Django 2.2.6 on 2022-08-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0168_remove_detalleevcalcontroldescartear2022_condicion13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalcontroldescartear2022',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvDescarteAr2022', to='maestras.MaestraFundoCultivo'),
        ),
    ]
