# Generated by Django 2.2.6 on 2022-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0169_auto_20220829_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalcontroldescartear2022',
            name='cantidad_muestra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
