# Generated by Django 2.2.6 on 2022-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0170_auto_20220902_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcontroldescartear2022',
            name='exportable2_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
