# Generated by Django 2.2.6 on 2022-09-06 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('maestras', '0014_auto_20220829_0910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0171_detalleevcalcontroldescartear2022_exportable2_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvControlDescarteAr2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvControlDescarteAr2022', to='maestras.MaestraFundoCultivo')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoControlTipoEvDescarteAr2022', to='evaluaciones.TipoEvaluacionAr')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoControlTurnoDescarteAr2022', to='menu.Turno')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoControlVariedadDescarteAr2022', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvDescarteAr2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvDescarteAr2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Control Descarte Arandano 2022 ',
                'verbose_name_plural': 'Ev. Control Descarte Arandano 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvControlDescarteAr2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acopio1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('seleccion1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('seleccion2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibrado1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibrado2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibrado3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calibrado4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empaque1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empaque2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empaque3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empaque4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empaque5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calidad1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleDescArIca2022', to='evaluaciones.EvControlDescarteAr2022')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvControlDescarteAr2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvControlDescarteAr2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Det Control Descarte Arandano 2022',
                'verbose_name_plural': 'Ev. Det Control Descarte Arandano 2022',
            },
        ),
    ]
