# Generated by Django 2.2.6 on 2022-09-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0172_detalleevcontroldescartear2022_evcontroldescartear2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcontroldescartear2022',
            name='anexo_tipo',
        ),
    ]
