# Generated by Django 2.2.6 on 2022-09-07 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0173_remove_evcontroldescartear2022_anexo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('sub_lote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Lote')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('muestra', models.IntegerField(blank=True, null=True)),
                ('frutos_infestados', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.fundo')),
                ('anexo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCamarasHumedas2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCamarasHumedas2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Camaras Humedas 2022',
                'verbose_name_plural': 'Ev. Camaras Humedas 2022',
            },
        ),
    ]
