# Generated by Django 2.2.6 on 2022-09-08 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0174_evcamarashumedas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcamarashumedas',
            name='fecha_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evcamarashumedas',
            name='frutos_infestados',
        ),
        migrations.CreateModel(
            name='DetallePlantaEvCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('frutos_infestados', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCamarasHumedas2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCamarasHumedas2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Ev. Camaras Humedas 2022',
                'verbose_name_plural': 'Detalle Ev. Camaras Humedas 2022',
            },
        ),
    ]
