# Generated by Django 2.2.6 on 2022-09-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0175_auto_20220908_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='alternaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='apergillus_niger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='botrytis_cinerea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='cladosporium_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='penicillum_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='pestalotiopsis_sp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='rhyzopus_spp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='sin_esporular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
