# Generated by Django 2.2.6 on 2022-09-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0176_auto_20220908_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundoEvCamarasHumedas2022', to='menu.fundo'),
        ),
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PEPEvCamarasHumedas2022', to='menu.ProgramaProduccion'),
        ),
    ]
