# Generated by Django 2.2.6 on 2022-09-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0177_auto_20220908_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplantaevcamarashumedas',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetEvCamarasHumedas2022', to='menu.fundo'),
        ),
    ]
