# Generated by Django 2.2.6 on 2022-09-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0178_detalleplantaevcamarashumedas_anexo_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplantaevcamarashumedas',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetEvCamarasHumedas2022', to='evaluaciones.EvCamarasHumedas'),
        ),
    ]
