# Generated by Django 2.2.6 on 2022-09-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0179_auto_20220908_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ZonaEvCamarasHumedas2022', to='menu.ejezona'),
        ),
    ]
