# Generated by Django 2.2.6 on 2022-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0180_evcamarashumedas_anexo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='anexo_pep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PEP'),
        ),
    ]
