# Generated by Django 2.2.6 on 2022-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0182_auto_20220908_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='anexo_fundo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fundo'),
        ),
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='anexo_pep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PEP'),
        ),
    ]
