# Generated by Django 2.2.6 on 2022-09-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0094_auto_20220426_0857'),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0186_auto_20220908_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCondicionCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo condicion')),
            ],
            options={
                'verbose_name': 'Tipo Condicion Camaras Humedas',
                'verbose_name_plural': 'Tipo Condicion Camaras Humedas',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganoCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo condicion')),
            ],
            options={
                'verbose_name': 'Tipo Organo Camaras Humedas',
                'verbose_name_plural': 'Tipo Organo Camaras Humedas',
            },
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductoCamarasHumedas2022', to='sanidad.ProductosAutorizados'),
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadCamarasHumedas2022', to='menu.variedad'),
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCondicionCamarasHumedas2022', to='evaluaciones.TipoCondicionCamarasHumedas'),
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_organo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOrganoCamarasHumedas2022', to='evaluaciones.TipoOrganoCamarasHumedas'),
        ),
    ]
