# Generated by Django 2.2.6 on 2022-09-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0187_auto_20220917_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUbicacionCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo Ubicacion')),
            ],
            options={
                'verbose_name': 'Tipo Ubicacion Camaras Humedas',
                'verbose_name_plural': 'Tipo Ubicacion Camaras Humedas',
            },
        ),
        migrations.AlterField(
            model_name='evcamarashumedas',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionCamarasHumedas2022', to='evaluaciones.TipoUbicacionCamarasHumedas'),
        ),
        migrations.AlterField(
            model_name='tipocondicioncamarashumedas',
            name='desc',
            field=models.CharField(max_length=30, verbose_name='Tipo Condicion'),
        ),
        migrations.AlterField(
            model_name='tipoorganocamarashumedas',
            name='desc',
            field=models.CharField(max_length=30, verbose_name='Tipo Organo'),
        ),
    ]
