# Generated by Django 2.2.6 on 2022-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0188_auto_20220917_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcamarashumedas',
            old_name='ubicacion',
            new_name='anexo_ubicacion',
        ),
    ]
