# Generated by Django 2.2.6 on 2022-09-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0189_auto_20220917_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_tipo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEvaluacionCamarasHumedas2022', to='evaluaciones.TipoEvaluacionAr'),
        ),
    ]
