# Generated by Django 2.2.6 on 2022-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0190_evcamarashumedas_anexo_tipo_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcontroldescartear2022',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cosecha'),
        ),
    ]
