# Generated by Django 2.2.6 on 2022-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0191_detalleevcalcontroldescartear2022_fecha_cosecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleevcalcontroldescartear2022',
            name='fecha_cosecha',
        ),
        migrations.AddField(
            model_name='detalleevcontroldescartear2022',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cosecha'),
        ),
    ]
