# Generated by Django 2.2.6 on 2022-09-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0192_auto_20220919_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProductoCamarasHumedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo Producto')),
            ],
            options={
                'verbose_name': 'Tipo Producto Camaras Humedas',
                'verbose_name_plural': 'Tipo Producto Camaras Humedas',
            },
        ),
        migrations.AddField(
            model_name='evcamarashumedas',
            name='anexo_producto2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductoCamarasHumedas2022', to='evaluaciones.TipoProductoCamarasHumedas'),
        ),
    ]
