# Generated by Django 2.2.6 on 2022-09-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0194_detalleevcontroldescartear202202_evcontroldescartear202202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcontroldescartear202202',
            name='anexo_turno',
        ),
        migrations.AddField(
            model_name='detalleevcontroldescartear202202',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoControlTurnoDescarteAr202202', to='menu.Turno'),
        ),
    ]
