# Generated by Django 2.2.6 on 2022-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0195_auto_20220920_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcontroldescartear202202',
            name='acopio2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcontroldescartear202202',
            name='empaque6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcontroldescartear202202',
            name='empaque7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
