# Generated by Django 2.2.6 on 2022-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0197_evcalmuestreoplantahgica2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcamarashumedas',
            name='dias_aplicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
