# Generated by Django 2.2.6 on 2022-09-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0199_evcalmuestreoplantahgnep2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcalmuestreoplantahgica2022',
            old_name='estadio_valor',
            new_name='brix1',
        ),
        migrations.RenameField(
            model_name='evcalmuestreoplantahgnep2022',
            old_name='estadio_valor',
            new_name='brix1',
        ),
        migrations.RemoveField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_estadio',
        ),
        migrations.RemoveField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_estadio',
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_estadio_brix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1ICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_estadio_brix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2ICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_estadio_brix3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3ICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1FirmezaICA', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2FirmezaICA', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3FirmezaICA', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='brix2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='brix3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='valor_firmeza1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='valor_firmeza2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgica2022',
            name='valor_firmeza3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_estadio_brix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1NEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_estadio_brix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2NEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_estadio_brix3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3NEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1FirmezaNEP', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2FirmezaNEP', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3FirmezaNEP', to='evaluaciones.SelectorFirmezaCalidad'),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='brix2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='brix3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='valor_firmeza1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='valor_firmeza2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep2022',
            name='valor_firmeza3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
