# Generated by Django 2.2.6 on 2022-09-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0200_auto_20220922_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1FirmezaICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2FirmezaICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgica2022',
            name='anexo_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3FirmezaICA', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio1FirmezaNEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio2FirmezaNEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
        migrations.AlterField(
            model_name='evcalmuestreoplantahgnep2022',
            name='anexo_firmeza3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalEstadio3FirmezaNEP', to='evaluaciones.SelectorEstadiosCalidad'),
        ),
    ]
