# Generated by Django 2.2.6 on 2022-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0202_auto_20220927_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_decoloracion_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_decoloracion_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_decoloracion_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_decoloracion_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
