# Generated by Django 2.2.6 on 2022-09-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0203_auto_20220928_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcalacopioplantaarcaraz202202',
            old_name='cd_decoloracion_1',
            new_name='cal_decoloracion_1',
        ),
        migrations.RenameField(
            model_name='evcalacopioplantaarcaraz202202',
            old_name='cd_decoloracion_2',
            new_name='cal_decoloracion_2',
        ),
        migrations.RenameField(
            model_name='evcalacopioplantaarcaraz202202',
            old_name='cd_decoloracion_3',
            new_name='cal_decoloracion_3',
        ),
        migrations.RenameField(
            model_name='evcalacopioplantaarcaraz202202',
            old_name='cd_decoloracion_4',
            new_name='cal_decoloracion_4',
        ),
    ]
