# Generated by Django 2.2.6 on 2022-09-30 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('maestras', '0014_auto_20220829_0910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0204_auto_20220928_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalControlDescarteHg2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proceso', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluacion')),
                ('ticket', models.IntegerField(blank=True, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('cantidad_muestra', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvDescarteHg2022', to='maestras.MaestraFundoCultivo')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoEvDescarteHg2022', to='evaluaciones.TipoEvaluacionAr')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoDescarteHg2022', to='menu.Turno')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadDescarteHg2022', to='menu.variedad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalDescarteHg2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalDescarteHg2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Control Descarte Higo 2022',
                'verbose_name_plural': 'Ev. Calidad Control Descarte Higo 2022',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalControlDescarteHg2022',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportable1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exportable8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion11', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion13', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion14', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condicion16', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleDescArIca2022', to='evaluaciones.EvCalControlDescarteHg2022')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalControlDescarteHg2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalControlDescarteHg2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev.Calidad Det Control Descarte Higo 2022 ',
                'verbose_name_plural': 'Ev. Calidad Det Control Descarte Higo 2022',
            },
        ),
    ]
