# Generated by Django 2.2.6 on 2022-09-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0205_detalleevcalcontroldescartehg2022_evcalcontroldescartehg2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion1',
            new_name='descarte1',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion10',
            new_name='descarte10',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion11',
            new_name='descarte11',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion12',
            new_name='descarte12',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion13',
            new_name='descarte13',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion14',
            new_name='descarte14',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion15',
            new_name='descarte15',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion16',
            new_name='descarte16',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion2',
            new_name='descarte2',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion3',
            new_name='descarte3',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion4',
            new_name='descarte4',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion5',
            new_name='descarte5',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion6',
            new_name='descarte6',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion7',
            new_name='descarte7',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion8',
            new_name='descarte8',
        ),
        migrations.RenameField(
            model_name='detalleevcalcontroldescartehg2022',
            old_name='condicion9',
            new_name='descarte9',
        ),
    ]
