# Generated by Django 2.2.6 on 2022-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0206_auto_20220930_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcontroldescartear2022',
            name='calidad13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
