# Generated by Django 2.2.6 on 2022-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0207_auto_20221001_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte15',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte16',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='detalleevcalcontroldescartehg2022',
            name='exportable8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
