# Generated by Django 2.2.6 on 2022-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0208_auto_20221003_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcontroldescartegr2022',
            name='caylan',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Caylan'),
        ),
        migrations.AddField(
            model_name='evcontroldescartegr2022',
            name='lindero',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Lindero'),
        ),
    ]
