# Generated by Django 2.2.6 on 2022-10-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0209_auto_20221004_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcontroldescartehg2022',
            name='descarte17',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
