# Generated by Django 2.2.6 on 2022-10-10 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('maestras', '0015_auto_20221004_1405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0211_evcalmuestreoplantahgnep202202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProductoTerminadoHg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptCentrosCPTHg', to='menu.CentrosAthos')),
                ('anexo_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptLineaECPTHg', to='maestras.LineaEmpaqueAthos')),
                ('anexo_pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPaginaControlCPTHg', to='evaluaciones.SelectorAthos')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptTurnoCPTHg', to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreacionCPTHg', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModCPTHg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Producto Terminado Hg',
                'verbose_name_plural': ' Control Producto Terminado Hg',
            },
        ),
        migrations.CreateModel(
            name='DetalleControlProductoTerminadoHg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trazabilidad', models.CharField(blank=True, max_length=250, null=True, verbose_name='Trazabilidad')),
                ('npalet', models.IntegerField(blank=True, null=True, unique=True)),
                ('tamano_pulpa', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('peso6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion11', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_acomodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleAcomodoCPTHg', to='maestras.AcomodoAthos')),
                ('anexo_calibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleCalibreCPTHg', to='maestras.CalibresAthos')),
                ('anexo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleClienteCPTHg', to='maestras.ClientesAthos')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleCPTHg', to='evaluaciones.ControlProductoTerminadoHg')),
                ('anexo_presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleMaestraPCPTHg', to='maestras.MaestraPresentacionesAthos')),
                ('anexo_presentaciong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPresentaciongCPTHg', to='maestras.PresentacionesAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetCPTHg', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetCPTHg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Det Control Producto Terminado Hg',
                'verbose_name_plural': 'Det Control Producto Terminado Hg',
            },
        ),
    ]
