# Generated by Django 2.2.6 on 2022-10-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0212_controlproductoterminadohg_detallecontrolproductoterminadohg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecontrolproductoterminadohg',
            name='anexo_presentaciong',
        ),
    ]
