# Generated by Django 2.2.6 on 2022-10-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0213_remove_detallecontrolproductoterminadohg_anexo_presentaciong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecontrolproductoterminadohg',
            name='fitosanitario4',
        ),
    ]
