# Generated by Django 2.2.6 on 2022-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0214_remove_detallecontrolproductoterminadohg_fitosanitario4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlproductoterminadohg',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación'),
        ),
    ]
