# Generated by Django 2.2.6 on 2022-10-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0015_auto_20221004_1405'),
        ('evaluaciones', '0215_auto_20221010_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='anexo_presentaciong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPresentaciongCPTHg', to='maestras.PresentacionesAthos'),
        ),
    ]
