# Generated by Django 2.2.6 on 2022-10-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0216_detallecontrolproductoterminadohg_anexo_presentaciong'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproductoterminadohg',
            name='anexo_lanzado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCPTHg', to='menu.LPaletas'),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
