# Generated by Django 2.2.6 on 2022-10-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0217_auto_20221011_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminadohg',
            name='p12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
