# Generated by Django 2.2.6 on 2022-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0218_auto_20221011_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_fruta_hinchada_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_fruta_hinchada_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_fruta_hinchada_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_fruta_hinchada_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
