# Generated by Django 2.2.6 on 2022-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0219_auto_20221011_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_globito_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_globito_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_globito_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cd_globito_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
