# Generated by Django 2.2.6 on 2022-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0220_auto_20221017_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_cicatriz_1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_cicatriz_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_cicatriz_3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='evcalacopioplantaarcaraz202202',
            name='cal_cicatriz_4',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
