# Generated by Django 2.2.6 on 2022-10-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0221_auto_20221017_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='decoloracion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='fruta_hinchada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detallecontrolproductoterminado',
            name='globito',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
