# Generated by Django 2.2.6 on 2022-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0222_auto_20221017_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcontroldescartear2022',
            name='condicion14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
