# Generated by Django 2.2.6 on 2022-10-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0223_detalleevcalcontroldescartear2022_condicion14'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalmuestreoplantahgnep202202',
            name='anexo_planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMuestreoPlantaHg2022', to='menu.Planta'),
        ),
    ]
