# Generated by Django 2.2.6 on 2022-10-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0224_evcalmuestreoplantahgnep202202_anexo_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmuestreocosechahg2021',
            name='anexo_caseta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCasetaEvCalMuestreoCosechaHG2021', to='evaluaciones.SelectorCasetaCalidad'),
        ),
    ]
