# Generated by Django 2.2.6 on 2022-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0225_detalleevcalmuestreocosechahg2021_anexo_caseta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcaldefectoscampo',
            name='fruta_decolorada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
