# Generated by Django 2.2.6 on 2022-10-20 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0226_detalleevcaldefectoscampo_fruta_decolorada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvEficienciaSeleccionCalibrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npalet', models.IntegerField(blank=True, null=True, unique=True)),
                ('calibre1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calibre2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calibre3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calibre4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('firmeza_10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bloom_1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bloom_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bloom_3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bloom_4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('condicion11', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calidad11', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fitosanitario3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p7', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p8', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p9', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p10', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p11', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('p12', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEvEficienciaSC2022', to='menu.Planta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvEficienciaSC2022', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvEficienciaSC2022', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de Eficiencia - Selección y Calibrado 2022',
                'verbose_name_plural': 'Evaluación de Eficiencia - Selección y Calibrado 2022',
            },
        ),
    ]
