# Generated by Django 2.2.6 on 2022-10-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0227_eveficienciaseleccioncalibrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCalibreAnalisisEficiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo Ubicacion')),
            ],
            options={
                'verbose_name': 'Tipo Ubicacion Camaras Humedas',
                'verbose_name_plural': 'Tipo Ubicacion Camaras Humedas',
            },
        ),
        migrations.RenameField(
            model_name='eveficienciaseleccioncalibrado',
            old_name='calibre1',
            new_name='calidad12',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='calibre2',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='calibre3',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='calibre4',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='condicion11',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_10',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_4',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_5',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_6',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_7',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_8',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='firmeza_9',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p10',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p11',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p12',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p8',
        ),
        migrations.RemoveField(
            model_name='eveficienciaseleccioncalibrado',
            name='p9',
        ),
        migrations.AddField(
            model_name='eveficienciaseleccioncalibrado',
            name='anexo_calibre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoCalibreSC2022', to='evaluaciones.TipoCalibreAnalisisEficiencia'),
        ),
    ]
