# Generated by Django 2.2.6 on 2022-10-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0228_auto_20221021_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocalibreanalisiseficiencia',
            options={'verbose_name': 'Tipo Calibre Analisis Eficiencia 2022', 'verbose_name_plural': 'Tipo Calibre Analisis Eficiencia 2022'},
        ),
    ]
