# Generated by Django 2.2.6 on 2022-10-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0015_auto_20221004_1405'),
        ('evaluaciones', '0229_auto_20221021_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnvaseAnalisisEficiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo Envase')),
            ],
            options={
                'verbose_name': 'Tipo Envase Analisis Eficiencia 2022',
                'verbose_name_plural': 'Tipo Envase Analisis Eficiencia 2022',
            },
        ),
        migrations.AddField(
            model_name='eveficienciaseleccioncalibrado',
            name='anexo_linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLineaEmpaqueSC2022', to='maestras.LineaEmpaqueAthos'),
        ),
        migrations.AlterField(
            model_name='tipocalibreanalisiseficiencia',
            name='desc',
            field=models.CharField(max_length=30, verbose_name='Tipo Calibre'),
        ),
        migrations.AddField(
            model_name='eveficienciaseleccioncalibrado',
            name='anexo_envase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnvaseSC2022', to='evaluaciones.TipoEnvaseAnalisisEficiencia'),
        ),
    ]
