# Generated by Django 2.2.6 on 2022-10-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0015_auto_20221004_1405'),
        ('evaluaciones', '0230_auto_20221021_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveficienciaseleccioncalibrado',
            name='anexo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoClienteSC2022', to='maestras.ClientesAthos'),
        ),
    ]
