# Generated by Django 2.2.6 on 2022-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0231_eveficienciaseleccioncalibrado_anexo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalmuestreocosechahg2021',
            name='estadio_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalmuestreocosechahg2021',
            name='excremento_ave',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
