# Generated by Django 2.2.6 on 2022-11-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        ('evaluaciones', '0232_auto_20221104_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveficienciaseleccioncalibrado',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCptTurnoSC2022', to='menu.Turno'),
        ),
        migrations.AlterField(
            model_name='eveficienciaseleccioncalibrado',
            name='npalet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
