# Generated by Django 2.2.6 on 2022-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0234_detalleevproductoterminadodespacho_evproductoterminadodespacho_tipoinspeccionvisualconformidad_tipoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnvioPTDespacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo Envio P.T. Despacho 2022',
                'verbose_name_plural': 'Tipo Envio P.T. Despacho 2022',
            },
        ),
    ]
