# Generated by Django 2.2.6 on 2022-11-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0235_tipoenvioptdespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnvioEvPTDespacho2022', to='evaluaciones.TipoEnvioPTDespacho'),
        ),
    ]
