# Generated by Django 2.2.6 on 2022-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0236_auto_20221123_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo2_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo3_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo4_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='firmeza_clo5_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj02_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj03_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj04_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m01',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m02',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m03',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m04',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m05',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m06',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m07',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m08',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m09',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='peso_cj05_m12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
