# Generated by Django 2.2.6 on 2022-11-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0237_auto_20221124_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_bloom2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInspeccionVisual2EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualEstado'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_bloom3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInspeccionVisual3EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualEstado'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_bloom4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInspeccionVisual4EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualEstado'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_bloom5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInspeccionVisual5EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualEstado'),
        ),
    ]
