# Generated by Django 2.2.6 on 2022-11-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0238_auto_20221124_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_arte_caja2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoArteCaja2EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_arte_caja3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoArteCaja3EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_arte_caja4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoArteCaja4EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_arte_caja5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoArteCaja5EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_embolsado2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEmbolsado2EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_embolsado3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEmbolsado3EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_embolsado4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEmbolsado4EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_embolsado5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEmbolsado5EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_etiquetado2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEtiquetado2EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_etiquetado3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEtiquetado3EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_etiquetado4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEtiquetado4EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
        migrations.AddField(
            model_name='detalleevproductoterminadodespacho',
            name='anexo_etiquetado5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEtiquetado5EvPTDespacho2022', to='evaluaciones.TipoInspeccionVisualConformidad'),
        ),
    ]
