# Generated by Django 2.2.6 on 2022-12-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0191_auto_20221121_1025'),
        ('evaluaciones', '0239_auto_20221128_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='num_ramas_16mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalpodaar',
            name='num_ramas_5mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evcalpodaar',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPEPEvCalPodaAr', to='menu.ProgramaProduccion'),
        ),
    ]
