# Generated by Django 2.2.6 on 2023-01-31 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0240_auto_20221212_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorLlenadoArilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Desc de llenado arilo')),
            ],
            options={
                'verbose_name': 'Selector Llenado Arilo',
                'verbose_name_plural': 'Selector  Llenado Arilo',
            },
        ),
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='peso_arilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='peso_cascara',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalbrixgrica2021',
            name='anexo_llenado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.SelectorLlenadoArilo'),
        ),
    ]
