# Generated by Django 2.2.5 on 2019-09-25 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(max_length=20, verbose_name='Codigo de item')),
                ('nom_item', models.CharField(max_length=30, verbose_name='Nombre de Item')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Menu')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de Rol')),
                ('estado', models.CharField(blank=True, choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, null=True, verbose_name='Estado Rol')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion7', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion7', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, null=True, verbose_name='Estado Rol')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('asignar_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignar_usuario', to=settings.AUTH_USER_MODEL)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='menu.rol')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion8', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion8', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuario-Roles',
            },
        ),
        migrations.CreateModel(
            name='sub_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subitem', models.CharField(max_length=20, verbose_name='Codigo de Sub-Item')),
                ('nom_SubItem', models.CharField(max_length=30, verbose_name='Nombre de Sub-Item')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Sub-Item')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion4', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='perfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo de Usuario')),
                ('celular', models.CharField(max_length=30, verbose_name='Celular')),
                ('estado', models.CharField(blank=True, choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, null=True, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='menu_principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_menu', models.CharField(max_length=20, verbose_name='Codigo de menu')),
                ('nom_menu', models.CharField(max_length=30, verbose_name='Nombre de menu')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('suspendido', 'suspendido')], max_length=15, verbose_name='Estado de Menu')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'menu principal',
                'verbose_name_plural': 'menu principal',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_principal'),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion2', to=settings.AUTH_USER_MODEL),
        ),
    ]
