# Generated by Django 2.2.5 on 2019-09-30 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestra_Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fundo', models.CharField(max_length=30, verbose_name='Nombre de Fundo')),
                ('modulo', models.CharField(max_length=30, verbose_name='Modulo')),
                ('lote', models.CharField(max_length=30, verbose_name='lote')),
                ('longitud', models.CharField(max_length=30, verbose_name='longitud')),
                ('latitud', models.CharField(max_length=30, verbose_name='latitud')),
                ('cod_alterno1', models.CharField(max_length=30, verbose_name='Codigo Alterno 1')),
                ('cod_alterno2', models.CharField(max_length=30, verbose_name='Codigo Alterno 2')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion9', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestra Capmpo',
                'verbose_name_plural': 'Maestra Campo',
            },
        ),
    ]
