# Generated by Django 2.2.5 on 2019-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_maestra_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestra_campo',
            name='eje',
            field=models.CharField(blank=True, choices=[('ICA', 'ICA'), ('NO-SE', 'NO-SE')], max_length=15, null=True, verbose_name='Estado Rol'),
        ),
    ]
