# Generated by Django 2.2.5 on 2019-09-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_maestra_campo_eje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestra_campo',
            options={'verbose_name': 'Maestra Campo', 'verbose_name_plural': 'Maestra Campo'},
        ),
    ]
