# Generated by Django 2.2.5 on 2019-09-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190930_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='fenologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_feno', models.CharField(max_length=30, verbose_name='Fenología')),
                ('id_variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='menu.variedad')),
            ],
            options={
                'verbose_name': 'Fenología',
                'verbose_name_plural': 'Fenologías',
            },
        ),
    ]
