# Generated by Django 2.2.5 on 2019-10-02 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0009_auto_20191002_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanas',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='campanas',
            name='usuario_creacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion13', to=settings.AUTH_USER_MODEL),
        ),
    ]
