# Generated by Django 2.2.5 on 2019-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20191003_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eje_desarrollo',
            name='Eje',
            field=models.CharField(max_length=15, verbose_name='Eje'),
        ),
    ]
