# Generated by Django 2.2.5 on 2019-10-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20191003_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eje_desarrollo',
            old_name='Eje',
            new_name='nom_eje',
        ),
    ]
