# Generated by Django 2.2.5 on 2019-10-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20191003_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestra_campo',
            name='eje',
        ),
    ]
