# Generated by Django 2.2.5 on 2019-10-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_maestra_campo_eje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestra_campo',
            name='eje',
        ),
        migrations.DeleteModel(
            name='Eje_Desarrollo',
        ),
    ]
