# Generated by Django 2.2.5 on 2019-10-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_remove_maestra_campo_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestra_campo',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejezona', to='menu.ejezona'),
        ),
    ]
