# Generated by Django 2.2.5 on 2019-10-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_auto_20191004_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variedad',
            old_name='id_cultivo',
            new_name='cul',
        ),
    ]
