# Generated by Django 2.2.5 on 2019-10-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20191004_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, verbose_name='Area')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('an_camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas1', to='menu.campanas')),
                ('an_feno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feno1', to='menu.fenologia')),
                ('an_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote1', to='menu.lote')),
                ('an_variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedad1', to='menu.variedad')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado10', to='menu.Estado')),
            ],
            options={
                'verbose_name': 'Programa Produccion',
                'verbose_name_plural': 'Programas de Produccion',
            },
        ),
    ]
