# Generated by Django 2.2.5 on 2019-10-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_programaproduccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaproduccion',
            old_name='an_camp',
            new_name='anexo_campana',
        ),
        migrations.RenameField(
            model_name='programaproduccion',
            old_name='an_feno',
            new_name='anexo_fenologia',
        ),
        migrations.RenameField(
            model_name='programaproduccion',
            old_name='an_lote',
            new_name='anexo_lote',
        ),
        migrations.RenameField(
            model_name='programaproduccion',
            old_name='an_variedad',
            new_name='anexo_variedad',
        ),
    ]
