# Generated by Django 2.2.5 on 2019-10-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_auto_20191004_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fenologia',
            name='id_variedad',
        ),
        migrations.AddField(
            model_name='fenologia',
            name='id_cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivo', to='menu.cultivo'),
        ),
        migrations.AlterField(
            model_name='programaproduccion',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha y Hora de Creación'),
        ),
    ]
