# Generated by Django 2.2.6 on 2019-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0039_cultivo_abreviatura_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedad',
            name='abreviatura_variedad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Abreviatura de Variedad'),
        ),
    ]
