# Generated by Django 2.2.6 on 2019-10-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0040_variedad_abreviatura_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenologia',
            name='indice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Indice'),
        ),
    ]
