# Generated by Django 2.2.6 on 2019-10-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0042_estadocampana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocampana',
            options={'verbose_name': 'Estado Campaña', 'verbose_name_plural': 'Estados Campañas'},
        ),
        migrations.AlterField(
            model_name='programaproduccion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado10', to='menu.EstadoCampana'),
        ),
    ]
