# Generated by Django 2.2.6 on 2019-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0047_auto_20191031_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanas',
            name='camp',
            field=models.CharField(max_length=30, null=True, verbose_name='Campaña'),
        ),
    ]
