# Generated by Django 2.2.6 on 2019-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0051_auto_20191107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cod_alterno1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo Alterno 1'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cod_alterno2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo Alterno 2'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='latitud',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='longitud',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Longitud'),
        ),
    ]
