# Generated by Django 2.2.6 on 2021-02-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion Grupo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGruposPP', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModGruposPP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupos-Hitos',
                'verbose_name_plural': 'Grupos-Hitos',
            },
        ),
        migrations.CreateModel(
            name='Hitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion SubGrupo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Hitos',
                'verbose_name_plural': 'Hitos',
            },
        ),
        migrations.CreateModel(
            name='SubHitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion SubGrupo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoHitosPP', to='programaproduccion.Hitos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionSubHitosPP', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModSubHitosPP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubGrupos-Hitos',
                'verbose_name_plural': 'SubGrupos-Hitos',
            },
        ),
        migrations.CreateModel(
            name='SubGrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion SubGrupo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGruposPP', to='programaproduccion.Grupos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionSubGruposPP', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModSubGruposPP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubGrupos-Hitos',
                'verbose_name_plural': 'SubGrupos-Hitos',
            },
        ),
        migrations.AddField(
            model_name='hitos',
            name='anexo_subgrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSubGruposPP', to='programaproduccion.SubGrupos'),
        ),
        migrations.AddField(
            model_name='hitos',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionHitosPP', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hitos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModHitosPP', to=settings.AUTH_USER_MODEL),
        ),
    ]
