# Generated by Django 2.2.6 on 2021-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFertilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Fertilizacion')),
            ],
            options={
                'verbose_name': 'Plan Fertilizacion',
                'verbose_name_plural': 'Plan Fertilizacion',
            },
        ),
        migrations.CreateModel(
            name='PlanManoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Mano de Obra')),
            ],
            options={
                'verbose_name': 'Plan Mano de Obra',
                'verbose_name_plural': 'Plan Mano de Obra',
            },
        ),
        migrations.CreateModel(
            name='PlanRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Riego')),
            ],
            options={
                'verbose_name': 'Plan Riego',
                'verbose_name_plural': 'Plan Riego',
            },
        ),
        migrations.CreateModel(
            name='PlanSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Sanidad')),
            ],
            options={
                'verbose_name': 'Plan Sanidad',
                'verbose_name_plural': 'Plan Sanidad',
            },
        ),
    ]
