# Generated by Django 2.2.6 on 2021-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0002_planfertilizacion_planmanoobra_planriego_plansanidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area Athos')),
            ],
            options={
                'verbose_name': 'Area Athos',
                'verbose_name_plural': 'Area Athos',
            },
        ),
    ]
