# Generated by Django 2.2.6 on 2021-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0003_areaathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hitos Athos')),
            ],
            options={
                'verbose_name': 'tipo de hitos Athos',
                'verbose_name_plural': 'tipo de hitos Athos',
            },
        ),
    ]
