# Generated by Django 2.2.6 on 2022-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higo_planta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzadopaletashgnep2021',
            name='npalet',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, unique=True),
        ),
    ]
