# Generated by Django 2.2.6 on 2021-07-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infopaletarcaraz2021',
            old_name='cant_jabas',
            new_name='cant_clamshell',
        ),
    ]
