# Generated by Django 2.2.6 on 2021-07-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0180_auto_20210713_0823'),
        ('arandano', '0002_auto_20210721_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopaletarcaraz2021',
            name='anexo_envase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMatEnvaseArCaraz2021', to='menu.MaterialTransporte'),
        ),
        migrations.AddField(
            model_name='infopaletarcaraz2021',
            name='cant_jabas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
