# Generated by Django 2.2.6 on 2022-01-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0016_auto_20220119_1605'),
        ('arandano', '0005_auto_20210916_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopaletarcaraz2021',
            name='anexo_tipocalidadfruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTIpoCalFrutaArCaraz2021', to='granada.TipoCalidadFruta'),
        ),
    ]
