# Generated by Django 2.2.6 on 2022-06-06 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        ('granada', '0027_auto_20220406_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arandano', '0007_guiaathosarcaraz202102_guiadetallesathosarcaraz202102_infopaletarcaraz202102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAthosArCaraz202202',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('nroprecinto', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaGuiaAthosArCaraz202202', to='menu.AlmacenesAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferesGuiaAthosArCaraz202202', to='menu.ChoferesVehiculos')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoGuiaAthosArCaraz202202', to='menu.fundo')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosGuiaAthosArCaraz202202', to='menu.DatosEmpresa')),
                ('anexo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculosGuiaAthosArCaraz202202', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuiaAthosArCaraz202202', to='menu.ejezona')),
                ('ubic_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbi2GuiaAthosArCaraz202202', to='menu.LugarAthos')),
                ('ubic_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbi1GuiaAthosArCaraz202202', to='menu.LugarAthos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuiaAthosArCaraz202202', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaAthosArCaraz202202', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Athos-Caraz Arandanos 2022-02',
                'verbose_name_plural': 'Guias Athos-Caraz Arandanos 2022-02',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthosArCaraz202202',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadMArCaraz202202', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosArCaraz202202', to='arandano.GuiaAthosArCaraz202202')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioArCaraz202202', to='menu.MaterialAcopio')),
                ('anexo_ubi_mmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundoAthosArCaraz202202', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaDArCaraz202202', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDArCaraz202202', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos-Caraz Arandanos 2022-02',
                'verbose_name_plural': 'Guias  Detalles Athos-Caraz  Arandanos 2022-02',
            },
        ),
        migrations.CreateModel(
            name='InfoPaletArCaraz202202',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_clamshell', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cant_jabas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacenArCaraz202202', to='menu.AlmacenesAthos')),
                ('anexo_envase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMatEnvaseArCaraz202202', to='menu.MaterialTransporte')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosArCaraz202202', to='arandano.GuiaDetallesAthosArCaraz202202')),
                ('anexo_tipocalidadfruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTIpoCalFrutaArCaraz202202', to='granada.TipoCalidadFruta')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuelaArCaraz202202', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPaletsArCaraz202202', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPaletsArCaraz202202', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet-Arandanos Caraz 2022-02',
                'verbose_name_plural': 'Info Palets-Arandanos Caraz 2022-02',
            },
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='anexo_calidad',
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='anexo_guia',
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='anexo_material',
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='anexo_ubi_mmpp',
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='guiadetallesathosarcaraz202102',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='anexo_almacen',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='anexo_envase',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='anexo_guiad',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='anexo_tipocalidadfruta',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='anexo_tipoparihuela',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='infopaletarcaraz202102',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='GuiaAthosArCaraz202102',
        ),
        migrations.DeleteModel(
            name='GuiaDetallesAthosArCaraz202102',
        ),
        migrations.DeleteModel(
            name='InfoPaletArCaraz202102',
        ),
    ]
