# Generated by Django 2.2.6 on 2022-06-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0012_auto_20220412_1217'),
        ('arandano', '0009_guiaathosarica202202_guiadetallesathosarica202202_infopaletarica202202'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadetallesathosarica202202',
            name='anexo_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSupervisorAthosArIca202202', to='maestras.AuxiliaresCampoAthos'),
        ),
        migrations.AddField(
            model_name='guiadetallesathosarica202202',
            name='sub_lote',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Sub Lote'),
        ),
    ]
