# Generated by Django 2.2.6 on 2022-06-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0010_auto_20220615_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiadetallesathosarica202202',
            name='anexo_supervisor',
        ),
    ]
