# Generated by Django 2.2.6 on 2022-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0011_remove_guiadetallesathosarica202202_anexo_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetallesathosarica202202',
            name='sub_lote',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sub Lote'),
        ),
    ]
