# Generated by Django 2.2.6 on 2022-06-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada', '0027_auto_20220406_1624'),
        ('arandano', '0012_auto_20220616_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopaletarica202202',
            name='anexo_tipocalidadfruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTIpoCalFrutaArIca202202', to='granada.TipoCalidadFruta'),
        ),
    ]
