# Generated by Django 2.2.6 on 2022-06-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arandano', '0013_infopaletarica202202_anexo_tipocalidadfruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiadetallesathosarica202202',
            name='sub_lote',
        ),
    ]
