# Generated by Django 2.2.6 on 2022-06-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0012_auto_20220412_1217'),
        ('arandano', '0014_remove_guiadetallesathosarica202202_sub_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGuiaAthosArIca202202',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_lote', models.CharField(blank=True, max_length=10, null=True, verbose_name='SUB LOTE')),
                ('cant_envases', models.IntegerField(blank=True, null=True)),
                ('anexo_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAuxCampoAthosArIca202202', to='maestras.AuxiliaresCampoAthos')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoGuiaAthosArIca202202', to='arandano.GuiaAthosArIca202202')),
            ],
            options={
                'verbose_name': 'Info Guia Athos-Ica Arandano 2022 - 02',
                'verbose_name_plural': 'Infos de Guias Athos-Ica Arandanos 2022 - 02',
            },
        ),
    ]
