# Generated by Django 2.2.6 on 2022-06-28 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arandano', '0015_infoguiaathosarica202202'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoguiaathosarica202202',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='infoguiaathosarica202202',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='infoguiaathosarica202202',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioInfoGuiaArIca202202', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infoguiaathosarica202202',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionInfoGuiaArIca202202', to=settings.AUTH_USER_MODEL),
        ),
    ]
