# Generated by Django 2.2.6 on 2022-07-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0189_auto_20220609_0915'),
        ('arandano', '0016_auto_20220628_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoguiaathosarica202202',
            name='anexo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioInfoGuiaArIca202202', to='menu.MaterialAcopio'),
        ),
    ]
