# Generated by Django 2.2.6 on 2020-12-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0002_ingredientessanidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicologiaSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toxico', models.CharField(max_length=50, verbose_name='Toxicologia')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionToxicologiaSanidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModToxicologiaSanidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toxicologia Sanidad',
                'verbose_name_plural': 'Toxicologia Sanidad',
            },
        ),
    ]
