# Generated by Django 2.2.6 on 2020-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0004_plagasenfermedadessanidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagasenfermedadessanidad',
            name='plagas',
        ),
        migrations.AddField(
            model_name='plagasenfermedadessanidad',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Comun'),
        ),
        migrations.AddField(
            model_name='plagasenfermedadessanidad',
            name='nombre_especifico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Especifico'),
        ),
    ]
