# Generated by Django 2.2.6 on 2020-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0007_equipossanidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productossanidad',
            name='partidarc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partida RC'),
        ),
        migrations.AddField(
            model_name='productossanidad',
            name='subgrupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SubGrupo'),
        ),
        migrations.AlterField(
            model_name='productossanidad',
            name='producto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Familia'),
        ),
    ]
