# Generated by Django 2.2.6 on 2020-12-07 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0009_tipodosissanidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugaresAplicacionSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Lugar')),
                ('lugar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lugar')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionLugarAplicacionanidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModLugarAplicacionSanidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lugar Aplicacion Sanidad',
                'verbose_name_plural': 'Lugar Aplicacion Sanidad',
            },
        ),
    ]
