# Generated by Django 2.2.6 on 2020-12-07 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0011_auto_20201207_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tractoresathos',
            options={'verbose_name': 'Tractores Athos', 'verbose_name_plural': 'Tractores Athos'},
        ),
        migrations.CreateModel(
            name='BoquillasSanidadAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
                ('boquilla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boquilla')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionBoquillasAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModBoquillasAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boquillas Athos',
                'verbose_name_plural': 'Boquillas Athos',
            },
        ),
    ]
