# Generated by Django 2.2.6 on 2020-12-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0150_auto_20201204_1425'),
        ('sanidad', '0012_auto_20201207_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractoresathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTractorZona', to='menu.ejezona'),
        ),
    ]
