# Generated by Django 2.2.6 on 2020-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0013_tractoresathos_anexo_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipossanidad',
            name='anexo_cultivo',
        ),
        migrations.AddField(
            model_name='equipossanidad',
            name='tequipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Equipo'),
        ),
    ]
