# Generated by Django 2.2.6 on 2020-12-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0014_auto_20201207_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagasenfermedadessanidad',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
