# Generated by Django 2.2.6 on 2020-12-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0015_plagasenfermedadessanidad_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plagasenfermedadessanidad',
            old_name='nombre_especifico',
            new_name='nombre_cientifico',
        ),
    ]
