# Generated by Django 2.2.6 on 2020-12-15 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0017_operadoressanidadathos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitidoSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Permitido Sanidad',
                'verbose_name_plural': 'Permitido Sanidad',
            },
        ),
        migrations.CreateModel(
            name='UbicacionProductosAutorizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionCultivoPr', to='menu.cultivo')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaUbicacionPr', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionUbicacionPrAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModUbicacionPrAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicacion Productos Sanidad Athos',
                'verbose_name_plural': 'Ubicacion Productos Sanidad Athos',
            },
        ),
        migrations.CreateModel(
            name='ProductosAutorizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.IntegerField(blank=True, null=True)),
                ('nom_comercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Comercial')),
                ('um', models.CharField(blank=True, max_length=100, null=True, verbose_name='UM')),
                ('pr', models.IntegerField(blank=True, null=True)),
                ('uac', models.IntegerField(blank=True, null=True)),
                ('kglmin', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('kglmax', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('por_concentracion_min', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('por_concentracion_max', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('kgl200', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('nroaplicaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro Aplicaciones')),
                ('objetivo_aplicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Objetivo Aplicacion')),
                ('concentracion_ia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentracion IA')),
                ('formulacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentracion IA')),
                ('pc', models.IntegerField(blank=True, null=True)),
                ('lmr', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionProductos', to='sanidad.UbicacionProductosAutorizados')),
                ('anexo_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoIngredientesProductos', to='sanidad.IngredientesSanidad')),
                ('anexo_permitido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPermitidoSanidad', to='sanidad.PermitidoSanidad')),
                ('anexo_plagas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlagasProductosAutorizados', to='sanidad.PlagasEnfermedadesSanidad')),
                ('anexo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPrProductosAutorizados', to='sanidad.ProductosSanidad')),
                ('anexo_toxico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoToxicologiaProductos', to='sanidad.ToxicologiaSanidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProductosAutorizadosAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProductosAutorizadosAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productos Sanidad Athos',
                'verbose_name_plural': 'Productos Sanidad Athos',
            },
        ),
    ]
