# Generated by Django 2.2.6 on 2020-12-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0018_permitidosanidad_productosautorizados_ubicacionproductosautorizados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionproductosautorizados',
            name='anexo_zona',
        ),
    ]
