# Generated by Django 2.2.6 on 2020-12-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        ('sanidad', '0019_remove_ubicacionproductosautorizados_anexo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosautorizados',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPrEstadoSanidad', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='productosautorizados',
            name='anexo_versiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPrVersionSanidad', to='menu.VersionAgronomica'),
        ),
        migrations.AlterField(
            model_name='productosautorizados',
            name='anexo_permitido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPermitidoSanidad', to='sanidad.PermitidoSanidad'),
        ),
    ]
