# Generated by Django 2.2.6 on 2020-12-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        ('sanidad', '0020_auto_20201216_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagasenfermedadessanidad',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoPlagasEnfSanidad', to='menu.cultivo'),
        ),
    ]
