# Generated by Django 2.2.6 on 2020-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0021_plagasenfermedadessanidad_anexo_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipossanidad',
            name='equipo_sap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipos SAP'),
        ),
    ]
