# Generated by Django 2.2.6 on 2020-12-17 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0153_auto_20201214_1146'),
        ('sanidad', '0022_equipossanidad_equipo_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionRegistroAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoRegistroAplicacion', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacion', to='menu.fundo')),
                ('anexo_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacion', to='menu.ProgramaProduccion')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeRegistroAplicacion', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionUbiRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModUbiRegAplicacioAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicacion Registro Aplicacion Athos',
                'verbose_name_plural': 'Ubicacion Registro Aplicacion Athos',
            },
        ),
    ]
