# Generated by Django 2.2.6 on 2020-12-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0023_ubicacionregistroaplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosautorizados',
            name='objetivo_aplicacion',
        ),
    ]
