# Generated by Django 2.2.6 on 2020-12-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0024_remove_productosautorizados_objetivo_aplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosautorizados',
            name='anexo_plagas',
        ),
    ]
