# Generated by Django 2.2.6 on 2020-12-17 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0025_remove_productosautorizados_anexo_plagas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestraLMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino')),
                ('ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMLMRAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMLMRAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestra LMR',
                'verbose_name_plural': 'Maestra LMR',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosAutorizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleProductosAutorizados', to='sanidad.ProductosAutorizados')),
                ('anexo_lmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLMRDetProductosAutorizados', to='sanidad.MaestraLMR')),
                ('anexo_plagas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlagasProductosAutorizados', to='sanidad.PlagasEnfermedadesSanidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleProductosAutorizadosAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleProductosAutorizadosAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Productos Sanidad Athos',
                'verbose_name_plural': 'Detalle-Productos Sanidad Athos',
            },
        ),
    ]
