# Generated by Django 2.2.6 on 2020-12-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0026_detalleproductosautorizados_maestralmr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_aplicacion', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('total_producto', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('kgl200', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('kgl', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('vol', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('cod_aplicador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Aplicador')),
                ('nroorden', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegistroAplicacion', to='sanidad.UbicacionRegistroAplicacion')),
                ('anexo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEquiposRegAplicacion', to='sanidad.EquiposSanidad')),
                ('anexo_listas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductosRegistroAplicacion', to='sanidad.ProductosAutorizados')),
                ('anexo_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoMetRegAplicacion', to='sanidad.TipoMetodoSanidad')),
                ('anexo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDRegAplicacion', to='sanidad.TipoDosisSanidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Aplicacion',
                'verbose_name_plural': 'Registro Aplicacion',
            },
        ),
    ]
