# Generated by Django 2.2.6 on 2020-12-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0027_registroaplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestralmr',
            name='ppm',
        ),
    ]
