# Generated by Django 2.2.6 on 2020-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0028_remove_maestralmr_ppm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosautorizados',
            name='kgl200',
        ),
        migrations.RemoveField(
            model_name='productosautorizados',
            name='kglmax',
        ),
        migrations.RemoveField(
            model_name='productosautorizados',
            name='kglmin',
        ),
        migrations.RemoveField(
            model_name='productosautorizados',
            name='por_concentracion_max',
        ),
        migrations.RemoveField(
            model_name='productosautorizados',
            name='por_concentracion_min',
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kglmax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kglmin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='por_concentracion_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='por_concentracion_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
