# Generated by Django 2.2.6 on 2020-12-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0029_auto_20201221_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='anexo_lmr',
        ),
    ]
