# Generated by Django 2.2.6 on 2020-12-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0031_detallelmrpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelmrpa',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductosLmrAutorizados', to='sanidad.ProductosAutorizados'),
        ),
    ]
