# Generated by Django 2.2.6 on 2020-12-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0032_auto_20201221_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosautorizados',
            name='lmr',
        ),
        migrations.AddField(
            model_name='productosautorizados',
            name='codigo_senasa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concentracion IA'),
        ),
    ]
