# Generated by Django 2.2.6 on 2021-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0033_auto_20201221_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
