# Generated by Django 2.2.6 on 2021-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0034_ubicacionregistroaplicacion_anexo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='nroreserva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
