# Generated by Django 2.2.6 on 2021-01-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0035_ubicacionregistroaplicacion_nroreserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_equipo',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_metodo',
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiEquiposRegAplicacion', to='sanidad.EquiposSanidad'),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiTipoMetRegAplicacion', to='sanidad.TipoMetodoSanidad'),
        ),
    ]
