# Generated by Django 2.2.6 on 2021-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0036_auto_20210104_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='codigo',
        ),
        migrations.AddField(
            model_name='registroaplicacion',
            name='dosis',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
