# Generated by Django 2.2.6 on 2021-01-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0037_auto_20210104_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosautorizados',
            options={'verbose_name': 'Productos Permitidos Sanidad Athos', 'verbose_name_plural': 'Productos Permitidos Sanidad Athos'},
        ),
        migrations.AlterModelOptions(
            name='productossanidad',
            options={'verbose_name': 'Grupos-Productos Sanidad', 'verbose_name_plural': 'Grupos-Productos Sanidad'},
        ),
        migrations.AlterModelOptions(
            name='registroaplicacion',
            options={'verbose_name': 'det1-Registro Aplicacion Sanidad', 'verbose_name_plural': 'det1-Registro Aplicacion Sanidad'},
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='kgl',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='kgl200',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='porcentaje',
        ),
    ]
