# Generated by Django 2.2.6 on 2021-01-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0038_auto_20210105_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='nroorden',
        ),
    ]
