# Generated by Django 2.2.6 on 2021-01-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0039_remove_registroaplicacion_nroorden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproductosautorizados',
            old_name='kgl200',
            new_name='kgl200max',
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroaplicacion',
            name='anexo_objetivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleProductosARegAplicacion', to='sanidad.DetalleProductosAutorizados'),
            preserve_default=False,
        ),
    ]
