# Generated by Django 2.2.6 on 2021-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0040_auto_20210105_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kgl200max',
        ),
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kgl200min',
        ),
    ]
