# Generated by Django 2.2.6 on 2021-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0041_auto_20210105_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
