# Generated by Django 2.2.6 on 2021-01-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0042_detalleproductosautorizados_kgl200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kgl200',
        ),
    ]
