# Generated by Django 2.2.6 on 2021-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0043_remove_detalleproductosautorizados_kgl200'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='kgl200min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
