# Generated by Django 2.2.6 on 2021-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0044_auto_20210105_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='area_aplicada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='numero_cilindros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='vol_agua',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
