# Generated by Django 2.2.6 on 2021-01-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0045_auto_20210105_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='areas_aplicacion',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='vol',
        ),
    ]
