# Generated by Django 2.2.6 on 2021-01-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0046_auto_20210105_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_objetivo',
        ),
    ]
