# Generated by Django 2.2.6 on 2021-01-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0047_remove_registroaplicacion_anexo_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaplicacion',
            name='anexo_objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleProductosARegAplicacion', to='sanidad.DetalleProductosAutorizados'),
        ),
    ]
