# Generated by Django 2.2.6 on 2021-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0048_registroaplicacion_anexo_objetivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_objetivo',
        ),
    ]
