# Generated by Django 2.2.6 on 2021-01-11 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0049_remove_registroaplicacion_anexo_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRegistroAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('cod_aplicador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Aplicador')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegistroAplicacion', to='sanidad.RegistroAplicacion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'detalle-Registro Aplicacion Sanidad',
                'verbose_name_plural': 'detalle -Registro Aplicacion Sanidad',
            },
        ),
    ]
