# Generated by Django 2.2.6 on 2021-01-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0050_detalleregistroaplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='anexo_objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleObjRegistroAplicacion', to='sanidad.PlagasEnfermedadesSanidad'),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='hr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='vv',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
