# Generated by Django 2.2.6 on 2021-01-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0051_auto_20210113_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='anexo_objetivo',
        ),
        migrations.AddField(
            model_name='registroaplicacion',
            name='anexo_objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleObjRegistroAplicacion', to='sanidad.PlagasEnfermedadesSanidad'),
        ),
    ]
