# Generated by Django 2.2.6 on 2021-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0052_auto_20210119_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='consumo_detalle',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
