# Generated by Django 2.2.6 on 2021-01-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0053_detalleregistroaplicacion_consumo_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacionregistroaplicacion',
            old_name='numero_cilindros',
            new_name='numero_tanque',
        ),
    ]
