# Generated by Django 2.2.6 on 2021-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0054_auto_20210120_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='capacidad_tanque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='codigo_boquilla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Boquilla'),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='num_boquilla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='presion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
