# Generated by Django 2.2.6 on 2021-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0055_auto_20210120_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='numero_tanque',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
