# Generated by Django 2.2.6 on 2021-02-02 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0164_variedad_tipo_fruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0056_auto_20210120_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProyeccionSemanalSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Detalle-Proyeccion Semanal Sanidad',
                'verbose_name_plural': 'Detalle-Proyeccion Semanal Sanidad',
            },
        ),
        migrations.CreateModel(
            name='RegistroProyeccionSemanalSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem2', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem3', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem4', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegDetProyeccionCultivoSanidad', to='sanidad.DetalleProyeccionSemanalSanidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRegProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRegProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Semanal-Proyeccion Semanal Sanidad',
                'verbose_name_plural': 'Detalle Semanal-Proyeccion Semanal Sanidad',
            },
        ),
        migrations.CreateModel(
            name='ProyeccionSemanalSanidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('semana', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionCultivoSanidad', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionFundoSanidad', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionZonaSanidad', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyeccion Semanal Sanidad',
                'verbose_name_plural': 'Proyeccion Semanal Sanidad',
            },
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalsanidad',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProyeccionCultivoSanidad', to='sanidad.ProyeccionSemanalSanidad'),
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalsanidad',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalsanidad',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetProyeccionSemanalSanidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
