# Generated by Django 2.2.6 on 2021-02-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0057_auto_20210202_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientessanidad',
            name='ingrediente',
            field=models.CharField(max_length=200, verbose_name='Ingredientes'),
        ),
    ]
