# Generated by Django 2.2.6 on 2021-02-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0058_auto_20210202_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionsemanalsanidad',
            name='anexo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProyec', to='sanidad.ProductosAutorizados'),
        ),
    ]
