# Generated by Django 2.2.6 on 2021-02-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0059_detalleproyeccionsemanalsanidad_anexo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_permitido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPermitidosUbiRegAplicacion', to='sanidad.PermitidoSanidad'),
        ),
    ]
