# Generated by Django 2.2.6 on 2021-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0060_ubicacionregistroaplicacion_anexo_permitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaplicacion',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
