# Generated by Django 2.2.6 on 2021-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0061_registroaplicacion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosautorizados',
            name='equivalencia',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
