# Generated by Django 2.2.6 on 2021-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0062_productosautorizados_equivalencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='ce_antes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='ce_despues',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='fecha_consumo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Consumo'),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='ph_antes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='ph_despues',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
