# Generated by Django 2.2.6 on 2021-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0063_auto_20210213_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Obs'),
        ),
    ]
