# Generated by Django 2.2.6 on 2021-02-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0167_turnoprogramaproduccion_anexo_suelo'),
        ('sanidad', '0064_detalleregistroaplicacion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadoressanidadathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOperadorZona', to='menu.ejezona'),
        ),
        migrations.AddField(
            model_name='operadoressanidadathos',
            name='codigo_sap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
