# Generated by Django 2.2.6 on 2021-02-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0066_auto_20210215_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_lugar',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='anexo_operario',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='fecha_aplicacion',
        ),
        migrations.RemoveField(
            model_name='registroaplicacion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLugRegistroAplicacion', to='sanidad.LugaresAplicacionSanidad'),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOpeRegistroAplicacion', to='sanidad.OperadoresSanidadAthos'),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacion'),
        ),
    ]
