# Generated by Django 2.2.6 on 2021-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0067_auto_20210216_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleregistroaplicacion',
            name='fecha_consumo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Consumo'),
        ),
    ]
