# Generated by Django 2.2.6 on 2021-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0068_auto_20210216_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='numero_tanque',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
    ]
