# Generated by Django 2.2.6 on 2021-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0069_auto_20210218_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaplicacion',
            name='total_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
