# Generated by Django 2.2.6 on 2021-02-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0070_auto_20210218_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipossanidad',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
    ]
