# Generated by Django 2.2.6 on 2021-03-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0071_equipossanidad_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleregistroaplicacion',
            options={'verbose_name': 'Capa3-detalle-Registro Aplicacion Sanidad', 'verbose_name_plural': 'Capa3-detalle -Registro Aplicacion Sanidad'},
        ),
        migrations.AlterModelOptions(
            name='registroaplicacion',
            options={'verbose_name': 'Capa2-Registro Aplicacion Sanidad', 'verbose_name_plural': 'Capa2-Registro Aplicacion Sanidad'},
        ),
        migrations.AlterModelOptions(
            name='ubicacionregistroaplicacion',
            options={'verbose_name': 'Capa1-Ubicacion Registro Aplicacion Athos', 'verbose_name_plural': 'Capa1-Ubicacion Registro Aplicacion Athos'},
        ),
    ]
