# Generated by Django 2.2.6 on 2021-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0072_auto_20210305_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleregistroaplicacion',
            name='cod_aplicador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cod Aplicador'),
        ),
    ]
