# Generated by Django 2.2.6 on 2021-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0073_auto_20210309_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='numero_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
