# Generated by Django 2.2.6 on 2021-03-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0074_auto_20210317_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTractorRegistroAplicacion', to='sanidad.TractoresAthos'),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='marcha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='rpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='velocidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoRegistroAplicacion', to='menu.cultivo'),
        ),
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacion', to='menu.fundo'),
        ),
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacion', to='menu.ProgramaProduccion'),
        ),
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeRegistroAplicacion', to='menu.ejezona'),
        ),
    ]
