# Generated by Django 2.2.6 on 2021-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0075_auto_20210317_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='rpm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
    ]
