# Generated by Django 2.2.6 on 2021-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0076_auto_20210317_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='marcha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='ubicacionregistroaplicacion',
            name='rpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
