# Generated by Django 2.2.6 on 2021-03-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0170_auto_20210323_1459'),
        ('sanidad', '0077_auto_20210320_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='boquillassanidadathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaBoquilla', to='menu.ejezona'),
        ),
    ]
