# Generated by Django 2.2.6 on 2021-03-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0078_boquillassanidadathos_anexo_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproductosautorizados',
            old_name='kgl200',
            new_name='dosis_max',
        ),
        migrations.RenameField(
            model_name='detalleproductosautorizados',
            old_name='kgl200max',
            new_name='dosis_min',
        ),
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kgl200min',
        ),
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kglmax',
        ),
        migrations.RemoveField(
            model_name='detalleproductosautorizados',
            name='kglmin',
        ),
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='anexo_dosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDosisProductosAutorizados', to='sanidad.TipoDosisSanidad'),
        ),
    ]
