# Generated by Django 2.2.6 on 2021-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0079_auto_20210329_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductosautorizados',
            name='factor_premezcla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
