# Generated by Django 2.2.6 on 2021-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0080_detalleproductosautorizados_factor_premezcla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='idequipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo'),
        ),
    ]
