# Generated by Django 2.2.6 on 2021-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0081_ubicacionregistroaplicacion_idequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='idoperario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operario'),
        ),
    ]
