# Generated by Django 2.2.6 on 2021-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0082_ubicacionregistroaplicacion_idoperario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='idtractor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tractor'),
        ),
    ]
