# Generated by Django 2.2.6 on 2021-04-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0083_ubicacionregistroaplicacion_idtractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='anexo_aplicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetOperarioAplicacion', to='sanidad.OperadoresSanidadAthos'),
        ),
    ]
