# Generated by Django 2.2.6 on 2021-07-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0084_detalleregistroaplicacion_anexo_aplicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='fecha_premezcla',
            field=models.DateField(blank=True, null=True),
        ),
    ]
