# Generated by Django 2.2.6 on 2021-07-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0085_ubicacionregistroaplicacion_fecha_premezcla'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptaMezcla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mezcla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rpta Mezcla')),
            ],
            options={
                'verbose_name': 'Rpta-Mezcla',
                'verbose_name_plural': 'Rpta-Mezcla',
            },
        ),
        migrations.AddField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_rpta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaMezclaUbiRegAplicacion', to='sanidad.RptaMezcla'),
        ),
    ]
