# Generated by Django 2.2.6 on 2021-07-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0086_auto_20210719_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacion',
            name='anexo_rpta',
        ),
    ]
