# Generated by Django 2.2.6 on 2021-07-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0087_remove_ubicacionregistroaplicacion_anexo_rpta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroaplicacion',
            name='anexo_rpta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRplaMezclaAplicacion', to='sanidad.RptaMezcla'),
        ),
    ]
