# Generated by Django 2.2.6 on 2021-07-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0088_detalleregistroaplicacion_anexo_rpta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='anexo_rpta',
        ),
        migrations.AddField(
            model_name='registroaplicacion',
            name='anexo_rpta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRplaMezclaAplicacion1', to='sanidad.RptaMezcla'),
        ),
    ]
