# Generated by Django 2.2.6 on 2021-09-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0089_auto_20210727_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaplicacion',
            name='dosis_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroaplicacion',
            name='tipo_dosis_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDRegAplicacionReal', to='sanidad.TipoDosisSanidad'),
        ),
    ]
