# Generated by Django 2.2.6 on 2021-09-07 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanidad', '0090_auto_20210903_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='anexo_aplicador',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='ce_antes',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='ce_despues',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='cod_aplicador',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='ph_antes',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='ph_despues',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacion',
            name='vv',
        ),
        migrations.CreateModel(
            name='ConfirmativaRegistroAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('cod_aplicador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cod Aplicador')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('hr', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('vv', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_antes', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_antes', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_despues', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_despues', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Obs')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_aplicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoConfirOperarioAplicacion', to='sanidad.OperadoresSanidadAthos')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoConfirRegistroAplicacion', to='sanidad.UbicacionRegistroAplicacion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModConfirRegAplicacionAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa1-Confirmativa-Registro Aplicacion Sanidad',
                'verbose_name_plural': 'Capa1-Confirmativa -Registro Aplicacion Sanidad',
            },
        ),
    ]
