# Generated by Django 2.2.6 on 2022-03-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0091_auto_20210907_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroaplicacion',
            name='anexo_listas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductosRegistroAplicacion', to='sanidad.ProductosAutorizados'),
        ),
        migrations.AlterField(
            model_name='registroaplicacion',
            name='anexo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDRegAplicacion', to='sanidad.TipoDosisSanidad'),
        ),
    ]
