# Generated by Django 2.2.6 on 2022-04-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        ('sanidad', '0092_auto_20220302_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionRegistroAplicacionNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroreserva', models.IntegerField(blank=True, null=True)),
                ('anexo_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('area_aplicada', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('vol_agua', models.IntegerField(blank=True, null=True)),
                ('numero_tanque', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('codigo_boquilla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Boquilla')),
                ('num_boquilla', models.IntegerField(blank=True, null=True)),
                ('presion', models.IntegerField(blank=True, null=True)),
                ('capacidad_tanque', models.IntegerField(blank=True, null=True)),
                ('marcha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa')),
                ('rpm', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('fecha_premezcla', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
                ('idequipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo')),
                ('idoperario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operario')),
                ('idtractor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tractor')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoRegistroAplicacionNE', to='menu.cultivo')),
                ('anexo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiEquiposRegAplicacionNE', to='sanidad.EquiposSanidad')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacionNE', to='menu.fundo')),
                ('anexo_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLugRegistroAplicacionNE', to='sanidad.LugaresAplicacionSanidad')),
                ('anexo_metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiTipoMetRegAplicacionNE', to='sanidad.TipoMetodoSanidad')),
                ('anexo_operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOpeRegistroAplicacionNE', to='sanidad.OperadoresSanidadAthos')),
                ('anexo_permitido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPermitidosUbiRegAplicacionNE', to='sanidad.PermitidoSanidad')),
                ('anexo_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRegistroAplicacionNE', to='menu.ProgramaProduccion')),
                ('anexo_tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTractorRegistroAplicacionNE', to='sanidad.TractoresAthos')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeRegistroAplicacionNE', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionUbiRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModUbiRegAplicacioAthosNE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa1-Ubicacion Registro Aplicacion Athos NE',
                'verbose_name_plural': 'Capa1-Ubicacion Registro Aplicacion Athos NE',
            },
        ),
        migrations.CreateModel(
            name='RegistroAplicacionNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('dosis_real', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('total_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('factor', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('cod_aplicador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Aplicador')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegistroAplicacionNE', to='sanidad.UbicacionRegistroAplicacion')),
                ('anexo_listas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductosRegistroAplicacionNE', to='sanidad.ProductosAutorizados')),
                ('anexo_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleObjRegistroAplicacionNE', to='sanidad.PlagasEnfermedadesSanidad')),
                ('anexo_rpta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRplaMezclaAplicacion1NE', to='sanidad.RptaMezcla')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDRegAplicacionNE', to='sanidad.TipoDosisSanidad')),
                ('tipo_dosis_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoDRegAplicacionRealNE', to='sanidad.TipoDosisSanidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa2-Registro Aplicacion Sanidad NE',
                'verbose_name_plural': 'Capa2-Registro Aplicacion Sanidad NE',
            },
        ),
        migrations.CreateModel(
            name='DetalleRegistroAplicacionNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_detalle', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_consumo', models.DateField(blank=True, null=True, verbose_name='Fecha Consumo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegistroAplicacionNE', to='sanidad.RegistroAplicacion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa3-detalle-Registro Aplicacion Sanidad NE',
                'verbose_name_plural': 'Capa3-detalle -Registro Aplicacion Sanidad NE',
            },
        ),
        migrations.CreateModel(
            name='ConfirmativaRegistroAplicacionNE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('cod_aplicador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cod Aplicador')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('hr', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('vv', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_antes', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_antes', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_despues', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_despues', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Obs')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_aplicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoConfirOperarioAplicacionNE', to='sanidad.OperadoresSanidadAthos')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoConfirRegistroAplicacionNE', to='sanidad.UbicacionRegistroAplicacion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConfirRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModConfirRegAplicacionAthosNE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa1-Confirmativa-Registro Aplicacion Sanidad NE',
                'verbose_name_plural': 'Capa1-Confirmativa -Registro Aplicacion Sanidad NE',
            },
        ),
    ]
