# Generated by Django 2.2.6 on 2022-04-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0093_confirmativaregistroaplicacionne_detalleregistroaplicacionne_registroaplicacionne_ubicacionregistroa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroaplicacionne',
            name='anexo_detalle',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacionne',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='detalleregistroaplicacionne',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='anexo_detalle',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='anexo_listas',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='anexo_objetivo',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='anexo_rpta',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='anexo_tipo',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='tipo_dosis_real',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='registroaplicacionne',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_cultivo',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_equipo',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_fundo',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_lugar',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_metodo',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_operario',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_permitido',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_produccion',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_tractor',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='anexo_zona',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='ubicacionregistroaplicacionne',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='ConfirmativaRegistroAplicacionNE',
        ),
        migrations.DeleteModel(
            name='DetalleRegistroAplicacionNE',
        ),
        migrations.DeleteModel(
            name='RegistroAplicacionNE',
        ),
        migrations.DeleteModel(
            name='UbicacionRegistroAplicacionNE',
        ),
    ]
