# Generated by Django 2.2.6 on 2021-03-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0169_auto_20210310_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalCosechaGr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Evaluacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoEvCalCosechaGr', to='menu.fundo')),
                ('anexo_pep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPEvCalCosechaGr', to='menu.ProgramaProduccion')),
                ('anexo_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoPPEv', to='menu.TurnoProgramaProduccion')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaEvCalCosechaGr', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEvCalCosechaGr', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEvCalCosechaGr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Cosecha Granada ',
                'verbose_name_plural': 'Ev. Calidad Cosecha Granada',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalCosechaGrDescarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fruta', models.IntegerField(blank=True, null=True)),
                ('fruta_cat1', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalCosechaGrDesc', to='calidadagricola.EvCalCosechaGr')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionetalleEvCalCosechaGrDesc', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModetalleEvCalCosechaGrDesc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle3-Categoria Descarte ',
                'verbose_name_plural': 'Detalle3-Categoria Descarte',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalCosechaGrCat2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fruta', models.IntegerField(blank=True, null=True)),
                ('fruta_cat1', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalCosechaGrCat2', to='calidadagricola.EvCalCosechaGr')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleEvCalCosechaGrCat2', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleEvCalCosechaGrCat2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle2-Categoria2 ',
                'verbose_name_plural': 'Detalle2-Categoria2',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalCosechaGrCat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fruta', models.IntegerField(blank=True, null=True)),
                ('fruta_rajada', models.IntegerField(blank=True, null=True)),
                ('fruta_clara2', models.IntegerField(blank=True, null=True)),
                ('fruta_clara3', models.IntegerField(blank=True, null=True)),
                ('fruta_descarte', models.IntegerField(blank=True, null=True)),
                ('dano_tijera', models.IntegerField(blank=True, null=True)),
                ('sin_pedunculo', models.IntegerField(blank=True, null=True)),
                ('fruta_deforme', models.IntegerField(blank=True, null=True)),
                ('fruta_deshidratada', models.IntegerField(blank=True, null=True)),
                ('fruta_pquemada', models.IntegerField(blank=True, null=True)),
                ('queresa', models.IntegerField(blank=True, null=True)),
                ('fruta_hojas', models.IntegerField(blank=True, null=True)),
                ('fruta_sana', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalCosechaGrCat1', to='calidadagricola.EvCalCosechaGr')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleEvCalCosechaGrCat1', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleEvCalCosechaGrCat1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle1-Categoria1 ',
                'verbose_name_plural': 'Detalle1-Categoria1',
            },
        ),
        migrations.CreateModel(
            name='DetalleEvCalCosechaGrCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajados', models.IntegerField(blank=True, null=True)),
                ('r3', models.IntegerField(blank=True, null=True)),
                ('r35', models.IntegerField(blank=True, null=True)),
                ('r4', models.IntegerField(blank=True, null=True)),
                ('r5', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleEvCalCosechaGrCampo', to='calidadagricola.EvCalCosechaGr')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionetalleEvCalCosechaGrCampo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModetalleEvCalCosechaGrCampo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle4-Categoria Campo ',
                'verbose_name_plural': 'Detalle4-Categoria Campo',
            },
        ),
    ]
