# Generated by Django 2.2.6 on 2021-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcampo',
            name='qrevaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Evaluador'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='qrevaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Evaluador'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat2',
            name='qrevaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Evaluador'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrdescarte',
            name='qrevaluador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Evaluador'),
        ),
        migrations.AddField(
            model_name='evcalcosechagr',
            name='qrsupervisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Supervisor'),
        ),
    ]
