# Generated by Django 2.2.6 on 2021-04-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidadagricola', '0002_auto_20210315_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCalidadMuestreoPlantaGr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrpalet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qr Palet')),
                ('num_palet', models.IntegerField(blank=True, null=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variedad')),
                ('guia_remision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guia Remision')),
                ('cal_material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calidad Material')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionetalleEvCalMuestroGrPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModetalleEvCalMuestroGrPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ev. Calidad Muestreo  Planta -Granada ',
                'verbose_name_plural': 'Ev. Calidad Muestreo  Planta -Granada',
            },
        ),
    ]
