# Generated by Django 2.2.6 on 2021-04-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0003_evcalidadmuestreoplantagr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcalidadmuestreoplantagr',
            name='cal_material',
        ),
    ]
