# Generated by Django 2.2.6 on 2021-04-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calidadagricola', '0004_remove_evcalidadmuestreoplantagr_cal_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvCalidadMuestreoPlantaGr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_calibre', models.IntegerField(blank=True, null=True)),
                ('cat1', models.IntegerField(blank=True, null=True)),
                ('cat2_cicatrizm25', models.IntegerField(blank=True, null=True)),
                ('cat2_manchasm25', models.IntegerField(blank=True, null=True)),
                ('cat2_pedunculo', models.IntegerField(blank=True, null=True)),
                ('cat2_rajadas', models.IntegerField(blank=True, null=True)),
                ('cat2_russel', models.IntegerField(blank=True, null=True)),
                ('cat2_danio', models.IntegerField(blank=True, null=True)),
                ('cat2_levinsolacion', models.IntegerField(blank=True, null=True)),
                ('cat2_manchasverdes', models.IntegerField(blank=True, null=True)),
                ('cat2_deformes', models.IntegerField(blank=True, null=True)),
                ('cat2_palidas', models.IntegerField(blank=True, null=True)),
                ('cat2_corona', models.IntegerField(blank=True, null=True)),
                ('cat2_recuperables', models.IntegerField(blank=True, null=True)),
                ('cattin_rajada_sa', models.IntegerField(blank=True, null=True)),
                ('desc_insolada', models.IntegerField(blank=True, null=True)),
                ('desc_queresa', models.IntegerField(blank=True, null=True)),
                ('desc_golpe', models.IntegerField(blank=True, null=True)),
                ('desc_botrytis', models.IntegerField(blank=True, null=True)),
                ('desc_rajadas_ae', models.IntegerField(blank=True, null=True)),
                ('desc_inmadurez', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetEvCalMuestroGrPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetEvCalMuestroGrPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Ev. Calidad Muestreo  Planta -Granada ',
                'verbose_name_plural': 'Detalle Ev. Calidad Muestreo  Planta -Granada',
            },
        ),
    ]
