# Generated by Django 2.2.6 on 2022-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0005_detalleevcalidadmuestreoplantagr'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='fruta_cosechable_c3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
