# Generated by Django 2.2.6 on 2022-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0006_detalleevcalcosechagrcat1_fruta_cosechable_c3'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='corona_deshidratada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
