# Generated by Django 2.2.6 on 2022-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0007_detalleevcalcosechagrcat1_corona_deshidratada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='corona_botritis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
