# Generated by Django 2.2.6 on 2022-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0008_detalleevcalcosechagrcat1_corona_botritis'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat2',
            name='fruta_verde2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
