# Generated by Django 2.2.6 on 2022-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0009_detalleevcalcosechagrcat2_fruta_verde2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcampo',
            name='fruta_verde_pl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
