# Generated by Django 2.2.6 on 2022-01-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0185_auto_20220108_1224'),
        ('calidadagricola', '0010_detalleevcalcosechagrcampo_fruta_verde_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalcosechagr',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoVariedadEvCalCosechagrica2021', to='menu.variedad'),
        ),
    ]
