# Generated by Django 2.2.6 on 2022-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0011_evcalcosechagr_anexo_variedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='con_pedunculo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
