# Generated by Django 2.2.6 on 2022-01-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0008_auxiliarescampoathos'),
        ('calidadagricola', '0012_detalleevcalcosechagrcat1_con_pedunculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalcosechagr',
            name='anexo_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSupervisorEvCalCosechaGr', to='maestras.AuxiliaresCampoAthos'),
        ),
    ]
