# Generated by Django 2.2.6 on 2022-01-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0132_auto_20220127_1418'),
        ('calidadagricola', '0013_evcalcosechagr_anexo_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='anexo_guantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CalidadGuantes', to='evaluaciones.SelectorRespuestaEscalaCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='anexo_jabas_burbupack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CalidadJabasB', to='evaluaciones.SelectorRespuestaSiNoCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='anexo_jabas_sinb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CalidadJabasSB', to='evaluaciones.SelectorRespuestaSiNoCalidad'),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='anexo_tijeras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CalidadTijeras', to='evaluaciones.SelectorRespuestaEscalaCalidad'),
        ),
    ]
