# Generated by Django 2.2.6 on 2022-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0014_auto_20220131_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='cochinilla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleevcalcosechagrcat1',
            name='color25',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
