# Generated by Django 2.2.6 on 2022-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0015_auto_20220201_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcalcosechagr',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
    ]
