# Generated by Django 2.2.6 on 2022-02-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidadagricola', '0016_evcalcosechagr_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcalcosechagr',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoPPEv', to='menu.TurnoProgramaProduccion'),
        ),
    ]
