# Generated by Django 2.2.6 on 2021-11-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higo', '0002_almacenacopiohgnepena2021_guiaathoshgnepena2021_guiadetallesathoshgnepena2021_infopalethgnepena2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenacopiohgnepena2021',
            options={'verbose_name': 'Almacen Acopio-HIGO-NEPEÑA-2021', 'verbose_name_plural': 'Almacen Acopio-HIGO-NEPEÑA-2021'},
        ),
        migrations.AlterModelOptions(
            name='almacenacopiohgpisco2021',
            options={'verbose_name': 'Almacen Acopio-HIGO-PIS-2021', 'verbose_name_plural': 'Almacen Acopio-HIGO-PIS-2021'},
        ),
        migrations.AlterModelOptions(
            name='guiaathoshgnepena2021',
            options={'verbose_name': 'Guia Athos-HIGO-NEPEÑA-2021', 'verbose_name_plural': 'Guias Athos-HIGO-NEPEÑA-2021'},
        ),
        migrations.AlterModelOptions(
            name='guiaathoshgpisco2021',
            options={'verbose_name': 'Guia Athos-HIGO-PIS-2021', 'verbose_name_plural': 'Guias Athos-HIGO-PIS-2021'},
        ),
        migrations.AlterModelOptions(
            name='guiadetallesathoshgnepena2021',
            options={'verbose_name': 'Guia Detalle Athos-HIGO-NEPEÑA-2021', 'verbose_name_plural': 'Guias  Detalles Athos- HIGO-NEPEÑA-2021'},
        ),
        migrations.AlterModelOptions(
            name='guiadetallesathoshgpisco2021',
            options={'verbose_name': 'Guia Detalle Athos-HIGO-PIS-2021', 'verbose_name_plural': 'Guias  Detalles Athos-HIGO-PIS-2021'},
        ),
        migrations.AlterModelOptions(
            name='infopalethgnepena2021',
            options={'verbose_name': 'Info Palet-HIGO-NEPEÑA-2021', 'verbose_name_plural': 'Info Palets-HIGO-NEPEÑA-2021'},
        ),
        migrations.AlterModelOptions(
            name='infopalethgpisco2021',
            options={'verbose_name': 'Info Palet-HIGO-PIS-2021', 'verbose_name_plural': 'Info Palets-HIGO-PIS-2021'},
        ),
    ]
