# Generated by Django 2.2.6 on 2021-03-01 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0168_auto_20210218_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAthosDt2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('nroprecinto', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaAthosDt2020', to='menu.AlmacenesAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferesDt2020', to='menu.ChoferesVehiculos')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoGuiaDt2020', to='menu.fundo')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosEmpDt2020', to='menu.DatosEmpresa')),
                ('anexo_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculosDt2020', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuiaDt2020', to='menu.ejezona')),
                ('ubic_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaLLDt2020', to='menu.LugarAthos')),
                ('ubic_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaPDt2020', to='menu.LugarAthos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuiaDt2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDt2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Athos-DATIL 2021',
                'verbose_name_plural': 'Guias Athos-DATIL 2021',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthosDt2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadMDt2020', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosDt2020', to='datil.GuiaAthosDt2021')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopioDt2020', to='menu.MaterialAcopio')),
                ('anexo_ubi_mmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundoAthosDt2020Athos', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaDDt2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaDDt2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos-Datil 2021',
                'verbose_name_plural': 'Guias  Detalles Athos- Datil 2021',
            },
        ),
        migrations.CreateModel(
            name='InfoPaletGr2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacenDt2020', to='menu.AlmacenesAthos')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosDt2020', to='datil.GuiaDetallesAthosDt2021')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuelaDt2020', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPaletsDt2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPaletsDt2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet-DATIL 2021',
                'verbose_name_plural': 'Info Palets-DATIL 2021',
            },
        ),
    ]
