# Generated by Django 2.2.6 on 2021-03-01 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0168_auto_20210218_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoPaletGr2021',
            new_name='InfoPaletDt2021',
        ),
    ]
