# Generated by Django 2.2.6 on 2022-03-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datil', '0003_guiaathosdtica2022_guiadetallesathosdtica2022_infopaletdtica2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetallesathosdtica2022',
            name='anexo_guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDetAthosDtIca2022', to='datil.GuiaAthosDtIca2022'),
        ),
        migrations.AlterField(
            model_name='infopaletdtica2022',
            name='anexo_guiad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthosDtIca2022', to='datil.GuiaDetallesAthosDtIca2022'),
        ),
    ]
