# Generated by Django 2.2.5 on 2019-09-30 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_auto_20190930_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cultivo', models.CharField(max_length=30, verbose_name='Nombre de Fundo')),
                ('estadoe', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACIVO')], max_length=15, null=True, verbose_name='Estado Rol')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion10', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cultivo',
                'verbose_name_plural': 'cultivos',
            },
        ),
        migrations.CreateModel(
            name='variedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_variedad', models.CharField(max_length=30, verbose_name='Nombre de Variedad')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutivo1', to='menu.cultivo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion11', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'variedad',
                'verbose_name_plural': 'variedades',
            },
        ),
    ]
