# Generated by Django 2.2.5 on 2019-09-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_cultivo_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='estadoe',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACIVO')], max_length=15, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nom_cultivo',
            field=models.CharField(max_length=30, verbose_name='Nombre del cultivo'),
        ),
    ]
