# Generated by Django 2.2.5 on 2019-09-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_fenologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenologia',
            name='id_variedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedad', to='menu.variedad'),
        ),
        migrations.CreateModel(
            name='campanas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], max_length=15, null=True, verbose_name='Campaña')),
                ('id_variedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedad1', to='menu.variedad')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
            },
        ),
    ]
