# Generated by Django 2.2.5 on 2019-10-02 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0008_auto_20190930_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenologia',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='fenologia',
            name='usuario_creacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion12', to=settings.AUTH_USER_MODEL),
        ),
    ]
