# Generated by Django 2.2.5 on 2019-10-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje_Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje', models.CharField(max_length=15, verbose_name='eje')),
            ],
            options={
                'verbose_name': 'Eje Desarrollo',
                'verbose_name_plural': 'Ejes de Desarrollo',
            },
        ),
        migrations.AddField(
            model_name='campanas',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado4', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='fenologia',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado3', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='maestra_campo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado5', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='variedad',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado2', to='menu.Estado'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado1', to='menu.Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nom_estado',
            field=models.CharField(max_length=15, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='maestra_campo',
            name='eje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eje1', to='menu.Eje_Desarrollo'),
        ),
    ]
