# Generated by Django 2.2.5 on 2019-10-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20191003_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eje_desarrollo',
            old_name='eje',
            new_name='Eje',
        ),
    ]
