# Generated by Django 2.2.5 on 2019-10-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_remove_maestra_campo_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestra_campo',
            name='eje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eje2', to='menu.Eje_Desarrollo'),
        ),
    ]
