# Generated by Django 2.2.5 on 2019-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20191003_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejezona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eje', models.CharField(max_length=15, verbose_name='Nombre del Eje')),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
            },
        ),
    ]
