# Generated by Django 2.2.5 on 2019-10-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_maestra_campo_eje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestra_campo',
            name='eje',
        ),
    ]
