# Generated by Django 2.2.5 on 2019-10-04 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0022_maestra_campo_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fundo', models.CharField(max_length=30, verbose_name='Nombre de Fundo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado5', to='menu.Estado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion9', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejezona', to='menu.ejezona')),
            ],
            options={
                'verbose_name': 'Maestra Campo',
                'verbose_name_plural': 'Maestra Campo',
            },
        ),
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lote', models.CharField(max_length=30, verbose_name='Nombre del lote')),
                ('longitud', models.CharField(max_length=30, verbose_name='Longitud')),
                ('latitud', models.CharField(max_length=30, verbose_name='Latitud')),
                ('cod_alterno1', models.CharField(max_length=30, verbose_name='Codigo Alterno 1')),
                ('cod_alterno2', models.CharField(max_length=30, verbose_name='Codigo Alterno 2')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado7', to='menu.Estado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(max_length=30, verbose_name='Modulo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado9', to='menu.Estado')),
                ('id_fundo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundo', to='menu.fundo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion21', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.RemoveField(
            model_name='campanas',
            name='campana',
        ),
        migrations.RemoveField(
            model_name='campanas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='campanas',
            name='id_variedad',
        ),
        migrations.AddField(
            model_name='campanas',
            name='camp',
            field=models.CharField(max_length=30, null=True, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='campanas',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion22', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Maestra_Campo',
        ),
        migrations.AddField(
            model_name='lote',
            name='mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundo', to='menu.modulo'),
        ),
        migrations.AddField(
            model_name='lote',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion20', to=settings.AUTH_USER_MODEL),
        ),
    ]
