# Generated by Django 2.2.5 on 2019-10-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_auto_20191004_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundo',
            options={'verbose_name': 'Fundo', 'verbose_name_plural': 'Fundos'},
        ),
    ]
