# Generated by Django 2.2.5 on 2019-10-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_auto_20191004_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id_fundo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundo1', to='menu.fundo'),
        ),
    ]
