# Generated by Django 2.2.5 on 2019-10-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0028_auto_20191004_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='id_fundo',
            new_name='idfundo',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='nombre_modulo',
            new_name='nombremodulo',
        ),
    ]
