# Generated by Django 2.2.5 on 2019-10-08 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_auto_20191008_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaproduccion',
            name='anexo_fenologia',
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='anexo_fundo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundo3', to='menu.fundo'),
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='anexo_modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote1', to='menu.modulo'),
        ),
    ]
