# Generated by Django 2.2.5 on 2019-10-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0031_auto_20191008_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaproduccion',
            name='fecha',
        ),
        migrations.CreateModel(
            name='ProgramaProduccionFeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha y Hora de Creación')),
                ('anexo_fenologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenologia1', to='menu.fenologia')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado30', to='menu.Estado')),
                ('programa_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Programa', to='menu.ProgramaProduccion')),
            ],
            options={
                'verbose_name': 'Produccion Fenologias',
                'verbose_name_plural': 'Produccion Fenologias',
            },
        ),
    ]
