# Generated by Django 2.2.5 on 2019-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_acciones_flujo_procesos_solicitud_tiporespuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programaproduccion',
            options={'verbose_name_plural': 'Programas de Produccion'},
        ),
        migrations.RemoveField(
            model_name='usuario_roles',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='ano_campana',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
