# Generated by Django 2.2.5 on 2019-10-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0034_auto_20191017_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_roles',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion47', to=settings.AUTH_USER_MODEL),
        ),
    ]
