# Generated by Django 2.2.5 on 2019-10-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_usuario_roles_usuario_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='programaproduccion',
            name='ano_campana',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Año Campaña'),
        ),
    ]
