# Generated by Django 2.2.5 on 2019-10-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0036_auto_20191017_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='cierre_campana',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Cierre de Campaña'),
        ),
    ]
