# Generated by Django 2.2.6 on 2019-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0037_programaproduccion_cierre_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='nom_zona',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la zona'),
        ),
    ]
