# Generated by Django 2.2.6 on 2019-10-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0038_fundo_nom_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='abreviatura_cultivo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Abreviatura Cultivo'),
        ),
    ]
