# Generated by Django 2.2.6 on 2019-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0041_fenologia_indice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCampana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado', models.CharField(max_length=15, null=True, verbose_name='Estado Campaña')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
    ]
