# Generated by Django 2.2.6 on 2019-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0043_auto_20191030_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='elementoPEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementopep', models.CharField(blank=True, max_length=30, null=True, verbose_name='Elemento PEP')),
            ],
            options={
                'verbose_name': 'Elemento PEP',
                'verbose_name_plural': 'Elementos PEP',
            },
        ),
    ]
