# Generated by Django 2.2.6 on 2019-10-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0044_elementopep'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopep',
            name='programa_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programa1', to='menu.ProgramaProduccion'),
        ),
    ]
