# Generated by Django 2.2.6 on 2019-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0045_elementopep_programa_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanas',
            name='camp',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='abreviatura_cultivo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Abreviatura Cultivo'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='nom_cultivo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre del cultivo'),
        ),
        migrations.AlterField(
            model_name='elementopep',
            name='programa_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programa1', to='menu.ProgramaProduccion', unique=True),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='nom_fundo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre de Fundo'),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='abreviatura_variedad',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Abreviatura de Variedad'),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='nom_variedad',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre de Variedad'),
        ),
    ]
