# Generated by Django 2.2.6 on 2019-10-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0046_auto_20191031_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='elementopep',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Elemento PEP'),
        ),
        migrations.AlterField(
            model_name='elementopep',
            name='programa_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programa1', to='menu.ProgramaProduccion'),
        ),
    ]
