# Generated by Django 2.2.6 on 2019-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0048_auto_20191031_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='elementopep',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Elemento PEP'),
        ),
    ]
