# Generated by Django 2.2.6 on 2019-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0050_auto_20191031_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedad',
            name='nom_variedad',
            field=models.CharField(max_length=30, verbose_name='Nombre de Variedad'),
        ),
    ]
