# Generated by Django 2.2.6 on 2019-12-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0052_auto_20191112_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Apellidos')),
                ('Nombres', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nombres')),
                ('DNI', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'Registro de Personal',
                'verbose_name_plural': 'Registros de Personal',
            },
        ),
    ]
