# Generated by Django 2.2.6 on 2020-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0053_registropersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='datos')),
            ],
            options={
                'verbose_name': 'dato',
                'verbose_name_plural': 'datos',
            },
        ),
        migrations.DeleteModel(
            name='RegistroPersonal',
        ),
        migrations.AddField(
            model_name='programaproduccionfeno',
            name='indice',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Indice'),
        ),
    ]
