# Generated by Django 2.2.6 on 2020-01-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0054_auto_20200108_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
