# Generated by Django 2.2.6 on 2020-01-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0055_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionAgronomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='N° de Version')),
            ],
            options={
                'verbose_name': 'Version Agronomica',
                'verbose_name_plural': 'Version Agronomica',
            },
        ),
        migrations.CreateModel(
            name='VariableAgronomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Indice')),
                ('Variable', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Variable Agronomica')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fen', to='menu.cultivo')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado39', to='menu.Estado')),
            ],
            options={
                'verbose_name': 'Variable Agronomica',
                'verbose_name_plural': 'Variable Agronomica',
            },
        ),
        migrations.CreateModel(
            name='PproduccionVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('anexo_campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cam', to='menu.campanas')),
                ('anexo_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.VariableAgronomica')),
                ('anexo_versiones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='menu.VersionAgronomica')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado71', to='menu.Estado')),
                ('programa_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programa3', to='menu.ProgramaProduccion')),
            ],
            options={
                'verbose_name': 'PP-variable',
                'verbose_name_plural': 'PP-variable',
            },
        ),
    ]
