# Generated by Django 2.2.6 on 2020-01-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0056_pproduccionvariable_variableagronomica_versionagronomica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableagronomica',
            name='indice',
        ),
    ]
