# Generated by Django 2.2.6 on 2020-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0058_auto_20200131_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzadopaletasreal',
            name='Codigoqr',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='QR'),
        ),
    ]
