# Generated by Django 2.2.6 on 2020-01-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0059_auto_20200131_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzadopaletasreal',
            name='anexo_lanzado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea5', to='menu.LanzadoPaletas'),
        ),
        migrations.AlterField(
            model_name='lanzadopaletasreal',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea6', to='menu.Linea'),
        ),
    ]
