# Generated by Django 2.2.6 on 2020-01-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0060_auto_20200131_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanzadopaletasreal',
            name='anexo_lanzado',
        ),
        migrations.RemoveField(
            model_name='lanzadopaletasreal',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='lanzadopaletasreal',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='lanzadopaletasreal',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='LanzadoPaletas',
        ),
        migrations.DeleteModel(
            name='LanzadoPaletasReal',
        ),
    ]
