# Generated by Django 2.2.6 on 2020-01-31 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0061_auto_20200131_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanzadoPaletas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave4', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta4', to='menu.Planta')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona22', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion78', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion78', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lanzado Paleta',
                'verbose_name_plural': 'Lanzado Paletas',
            },
        ),
        migrations.CreateModel(
            name='LanzadoPaletasReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigoqr', models.TextField(blank=True, max_length=1000, null=True, verbose_name='QR')),
                ('njavas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lanzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea5', to='menu.LanzadoPaletas')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea6', to='menu.Linea')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion79', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion79', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lanzado Paleta Real',
                'verbose_name_plural': 'Lanzado Paletas Real',
            },
        ),
    ]
