# Generated by Django 2.2.6 on 2020-01-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0064_lanzadopaletas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanzadopaletas',
            name='anexo_nave',
        ),
        migrations.RemoveField(
            model_name='lanzadopaletas',
            name='anexo_planta',
        ),
        migrations.RemoveField(
            model_name='lanzadopaletas',
            name='anexo_zona',
        ),
    ]
