# Generated by Django 2.2.6 on 2020-01-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0065_auto_20200131_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzadopaletas',
            name='anexo_nave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave3', to='menu.Nave'),
        ),
        migrations.AddField(
            model_name='lanzadopaletas',
            name='anexo_planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planta4', to='menu.Planta'),
        ),
        migrations.AddField(
            model_name='lanzadopaletas',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejezona22', to='menu.ejezona'),
        ),
    ]
