# Generated by Django 2.2.6 on 2020-01-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0066_auto_20200131_0548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanzadoPaletas',
        ),
    ]
