# Generated by Django 2.2.6 on 2020-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0068_lanzadopaletas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanzadoPaletas',
        ),
    ]
