# Generated by Django 2.2.6 on 2020-01-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0070_auto_20200131_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATLanzadoPaletas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'AT Lanzado Paleta',
                'verbose_name_plural': 'AT Lanzado Paletas',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_linea', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Linea')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Linea',
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nave', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nave')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Nave',
                'verbose_name_plural': 'Nave',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_planta', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Planta')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('nom_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona20', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion74', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion74', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Planta',
            },
        ),
        migrations.CreateModel(
            name='PersonalPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trab_empa', models.DecimalField(decimal_places=0, max_digits=5)),
                ('trab_term', models.DecimalField(decimal_places=0, max_digits=5)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave1', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta2', to='menu.Planta')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona21', to='menu.ejezona')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea1', to='menu.Linea')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion76', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion76', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Planta',
                'verbose_name_plural': 'Personal Planta',
            },
        ),
        migrations.AddField(
            model_name='nave',
            name='anexo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Planta', to='menu.Planta'),
        ),
        migrations.AddField(
            model_name='nave',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion75', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nave',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion75', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linea',
            name='anexo_nave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave2', to='menu.Nave'),
        ),
        migrations.AddField(
            model_name='linea',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion77', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linea',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion77', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ATLanzadoPaletasReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigoqr', models.TextField(blank=True, null=True, unique=True, verbose_name='QR')),
                ('njavas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lanzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea4', to='menu.ATLanzadoPaletas')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea4', to='menu.Linea')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion79', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion79', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AT Lanzado Paleta Real',
                'verbose_name_plural': ' AT Lanzado Paletas Real',
            },
        ),
        migrations.AddField(
            model_name='atlanzadopaletas',
            name='anexo_nave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave3', to='menu.Nave'),
        ),
        migrations.AddField(
            model_name='atlanzadopaletas',
            name='anexo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta4', to='menu.Planta'),
        ),
        migrations.AddField(
            model_name='atlanzadopaletas',
            name='anexo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona22', to='menu.ejezona'),
        ),
        migrations.AddField(
            model_name='atlanzadopaletas',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion78', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atlanzadopaletas',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion78', to=settings.AUTH_USER_MODEL),
        ),
    ]
