# Generated by Django 2.2.6 on 2020-01-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0071_auto_20200131_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlanzadopaletasreal',
            name='Codigoqr',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='QR'),
        ),
    ]
