# Generated by Django 2.2.6 on 2020-01-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0072_auto_20200131_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlanzadopaletasreal',
            name='anexo_lanzado',
        ),
        migrations.RemoveField(
            model_name='atlanzadopaletasreal',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='atlanzadopaletasreal',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='atlanzadopaletasreal',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='ATLanzadoPaletas',
        ),
        migrations.DeleteModel(
            name='ATLanzadoPaletasReal',
        ),
    ]
