# Generated by Django 2.2.6 on 2020-01-31 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0073_auto_20200131_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATHOSLanzadoPaletas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave4', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta5', to='menu.Planta')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona23', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion80', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion80', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATHOS Lanzado Paleta',
                'verbose_name_plural': 'ATHOS Lanzado Paletas',
            },
        ),
        migrations.CreateModel(
            name='ATHOSLanzadoPaletasReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigoqr', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR')),
                ('njavas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lanzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea6', to='menu.ATHOSLanzadoPaletas')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea7', to='menu.Linea')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion81', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion81', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATHOS Lanzado Paleta Real',
                'verbose_name_plural': ' ATHOS Lanzado Paletas Real',
            },
        ),
    ]
