# Generated by Django 2.2.6 on 2020-01-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0074_athoslanzadopaletas_athoslanzadopaletasreal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athoslanzadopaletasreal',
            name='anexo_lanzado',
        ),
        migrations.RemoveField(
            model_name='athoslanzadopaletasreal',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='athoslanzadopaletasreal',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='athoslanzadopaletasreal',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='anexo_nave',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='linea',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='nave',
            name='anexo_planta',
        ),
        migrations.RemoveField(
            model_name='nave',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='nave',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='anexo_nave',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='anexo_planta',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='anexo_zona',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='personalplanta',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='nom_zona',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='ATHOSLanzadoPaletas',
        ),
        migrations.DeleteModel(
            name='ATHOSLanzadoPaletasReal',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
        migrations.DeleteModel(
            name='Nave',
        ),
        migrations.DeleteModel(
            name='PersonalPlanta',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
