# Generated by Django 2.2.6 on 2020-01-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0076_auto_20200131_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athoslanzadopaletasreal',
            name='Codigoqr',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='QR'),
        ),
    ]
