# Generated by Django 2.2.6 on 2020-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0077_auto_20200131_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athoslanzadopaletasreal',
            name='Codigoqr',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR'),
        ),
    ]
