# Generated by Django 2.2.6 on 2020-01-31 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0078_auto_20200131_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPaletasReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leerqr', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR')),
                ('njavas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'ATHOS Lanzado Paleta Real',
                'verbose_name_plural': ' ATHOS Lanzado Paletas Real',
            },
        ),
        migrations.RenameModel(
            old_name='ATHOSLanzadoPaletas',
            new_name='LPaletas',
        ),
        migrations.DeleteModel(
            name='ATHOSLanzadoPaletasReal',
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='anexo_lanzado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea6', to='menu.LPaletas'),
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea7', to='menu.Linea'),
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion81', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion81', to=settings.AUTH_USER_MODEL),
        ),
    ]
