# Generated by Django 2.2.6 on 2020-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0079_auto_20200131_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpaletasreal',
            name='leerqr',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='QR'),
        ),
    ]
