# Generated by Django 2.2.6 on 2020-01-31 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0080_auto_20200131_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpaletasreal',
            options={'verbose_name': 'Lanzado', 'verbose_name_plural': ' Lanzado'},
        ),
        migrations.AlterField(
            model_name='lpaletas',
            name='anexo_nave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave5', to='menu.Nave'),
        ),
        migrations.AlterField(
            model_name='lpaletas',
            name='anexo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta6', to='menu.Planta'),
        ),
        migrations.AlterField(
            model_name='lpaletas',
            name='anexo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona24', to='menu.ejezona'),
        ),
        migrations.AlterField(
            model_name='lpaletas',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion83', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lpaletas',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion83', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='anexo_lanzado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea7', to='menu.LPaletas'),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='leerqr',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='leer qr'),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea8', to='menu.Linea'),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion84', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion84', to=settings.AUTH_USER_MODEL),
        ),
    ]
