# Generated by Django 2.2.6 on 2020-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0081_auto_20200131_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpaletasreal',
            name='leerqr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='leer qr'),
        ),
    ]
