# Generated by Django 2.2.6 on 2020-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0082_auto_20200131_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado', models.CharField(max_length=15, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado Planta',
                'verbose_name_plural': 'Estados Plantas',
            },
        ),
    ]
