# Generated by Django 2.2.6 on 2020-02-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0083_estadoplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpaletasreal',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado101', to='menu.EstadoPlanta'),
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='npalet',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lpaletasreal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lpaletasreal',
            name='njavas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
