# Generated by Django 2.2.6 on 2020-02-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0084_auto_20200210_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='codigo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='descripcion')),
                ('codigosap', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='codigo sap')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eplanta1', to='menu.EstadoPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion82', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion82', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materiales',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
