# Generated by Django 2.2.6 on 2020-02-10 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0086_ordenpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPedidoMaterialf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion2', to='menu.Materiales')),
                ('anexo_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden3', to='menu.OrdenPedido')),
                ('cod_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material9', to='menu.Materiales')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado97', to='menu.Estado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion90', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion90', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Pedido Material',
                'verbose_name_plural': 'Orden Pedido Material',
            },
        ),
    ]
