# Generated by Django 2.2.6 on 2020-02-10 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0087_ordenpedidomaterialf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPaletizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nave7', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta7', to='menu.Planta')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejezona31', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion186', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion186', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zona Paletizado',
                'verbose_name_plural': 'Zona Paletizado',
            },
        ),
    ]
