# Generated by Django 2.2.6 on 2020-02-10 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0088_zonapaletizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paletizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npalet', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trazabilidad', models.CharField(max_length=200, verbose_name='trazabilidad')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('calibre', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigo3', to='menu.OrdenPedidoMaterialf')),
                ('anexo_descripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material6', to='menu.OrdenPedidoMaterialf')),
                ('anexo_lanzado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linea8', to='menu.ZonaPaletizado')),
                ('anexo_ordenpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden6', to='menu.OrdenPedido')),
                ('anexo_qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanzado2', to='menu.LPaletasReal')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eplanta4', to='menu.EstadoPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion185', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion185', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paletizado',
                'verbose_name_plural': 'Paletizados',
            },
        ),
    ]
