# Generated by Django 2.2.6 on 2020-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0089_paletizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpaletasreal',
            name='linea',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linea'),
        ),
    ]
