# Generated by Django 2.2.6 on 2020-03-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0091_descarteplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_turno', models.CharField(max_length=15, null=True, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='ConfigurarDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin')),
                ('Turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Turno_Configuracion', to='menu.Turno')),
                ('anexo_ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ubicacion_Configuracion', to='menu.LPaletas')),
            ],
            options={
                'verbose_name': 'Configurar Dia',
                'verbose_name_plural': 'Configurar Dias',
            },
        ),
    ]
