# Generated by Django 2.2.6 on 2020-03-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0092_configurardia_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40, null=True, verbose_name='Area Planta')),
                ('labor', models.CharField(max_length=40, null=True, verbose_name='Labor Planta')),
            ],
            options={
                'verbose_name': 'Area Planta',
                'verbose_name_plural': 'Area Planta',
            },
        ),
        migrations.CreateModel(
            name='ConfAsistenciaPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_areaplanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConfAreaPlanta', to='menu.AreaPlanta')),
                ('anexo_configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConfAsistencia', to='menu.ConfigurarDia')),
            ],
            options={
                'verbose_name': 'Configurar Asistencia Planta',
                'verbose_name_plural': 'Configurar Asistencia Planta',
            },
        ),
        migrations.CreateModel(
            name='SalidaAsistenciaPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=40, null=True, verbose_name='DniAsistencia')),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('anexo_asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsistenciaSalida', to='menu.ConfAsistenciaPlanta')),
            ],
            options={
                'verbose_name': 'Salida Asistencia Planta',
                'verbose_name_plural': 'Salida Asistencia Planta',
            },
        ),
        migrations.CreateModel(
            name='IngresoAsistenciaPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=40, null=True, verbose_name='DniAsistencia')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Inicio')),
                ('anexo_asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AsistenciaIngreso', to='menu.ConfAsistenciaPlanta')),
            ],
            options={
                'verbose_name': 'Ingreso Asistencia Planta',
                'verbose_name_plural': 'Ingreso Asistencia Planta',
            },
        ),
    ]
