# Generated by Django 2.2.6 on 2020-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0093_areaplanta_confasistenciaplanta_ingresoasistenciaplanta_salidaasistenciaplanta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurardia',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
