# Generated by Django 2.2.6 on 2020-04-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0094_auto_20200319_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_alcance', models.CharField(max_length=40, null=True, verbose_name='Alcance')),
            ],
            options={
                'verbose_name': 'Alcance Capacitacion',
                'verbose_name_plural': 'Alcance Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='AreaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_area', models.CharField(max_length=40, null=True, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area Capacitacion',
                'verbose_name_plural': 'Area Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='CompetenciaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, null=True, verbose_name='Codigos')),
                ('nom_capacitacion', models.CharField(max_length=50, null=True, verbose_name='Competencias')),
                ('anexo_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Area_Competencia', to='menu.AreaCapacitacion')),
            ],
            options={
                'verbose_name': 'Competencia Capacitacion',
                'verbose_name_plural': 'Competencia Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=40, null=True, verbose_name='razon_social')),
                ('ruc', models.CharField(max_length=40, null=True, verbose_name='ruc')),
                ('domicilio', models.CharField(max_length=150, null=True, verbose_name='domicilio')),
            ],
            options={
                'verbose_name': 'Datos empresa',
                'verbose_name_plural': 'Datos Empresa',
            },
        ),
        migrations.CreateModel(
            name='ParticipantesCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_participantes', models.CharField(max_length=40, null=True, verbose_name='Tipo_Participantes')),
            ],
            options={
                'verbose_name': 'Participantes Capacitacion',
                'verbose_name_plural': 'Participantes Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_capacitacion', models.CharField(max_length=40, null=True, verbose_name='tipo_capacitacion')),
            ],
            options={
                'verbose_name': 'Tipo Capacitacion',
                'verbose_name_plural': 'Tipo Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='TemaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, null=True, verbose_name='Codigos')),
                ('nom_tema', models.CharField(max_length=100, null=True, verbose_name='Tema')),
                ('anexo_competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Competencia_Tema', to='menu.CompetenciaCapacitacion')),
            ],
            options={
                'verbose_name': 'Tema Capacitacion',
                'verbose_name_plural': 'Tema Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoacta', models.CharField(max_length=40, null=True, verbose_name='Codigo Acta')),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Inicio')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('anexo_alcance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alcance_CapacitacionA', to='menu.AlcanceCapacitacion')),
                ('anexo_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Area_CapacitacionA', to='menu.AreaCapacitacion')),
                ('anexo_competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Competencia_CapacitacionA', to='menu.CompetenciaCapacitacion')),
                ('anexo_datos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Datos_Empresa', to='menu.DatosEmpresa')),
                ('anexo_tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tema_CapacitacionA', to='menu.TemaCapacitacion')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Zona_Capacitacion', to='menu.ejezona')),
                ('tipo_capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Capacitacion', to='menu.TipoCapacitacion')),
                ('tipo_participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Participantes_Capacitacion', to='menu.ParticipantesCapacitacion')),
            ],
            options={
                'verbose_name': ' Capacitacion',
                'verbose_name_plural': ' Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=40, null=True, verbose_name='DNI')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Inicio')),
                ('anexo_capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Da', to='menu.CapacitacionCapacitacion')),
            ],
            options={
                'verbose_name': 'Asistencia Capacitacion',
                'verbose_name_plural': 'Asistencia Capacitacion',
            },
        ),
    ]
