# Generated by Django 2.2.6 on 2020-04-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0095_alcancecapacitacion_areacapacitacion_asistenciacapacitacion_capacitacioncapacitacion_competenciacapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.CharField(max_length=40, null=True, verbose_name='Labor Planta Configurar')),
            ],
            options={
                'verbose_name': 'Labor Planta',
                'verbose_name_plural': 'LaborPlanta',
            },
        ),
    ]
