# Generated by Django 2.2.6 on 2020-04-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0096_laborplanta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaplanta',
            name='labor',
        ),
        migrations.AddField(
            model_name='areaplanta',
            name='anexo_labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_labor', to='menu.LaborPlanta'),
        ),
    ]
