# Generated by Django 2.2.6 on 2020-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0097_auto_20200406_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacioncapacitacion',
            name='anexo_tema',
        ),
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='anexo_tema',
            field=models.ManyToManyField(to='menu.TemaCapacitacion'),
        ),
    ]
