# Generated by Django 2.2.6 on 2020-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0098_auto_20200414_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCapacitacioncapacitacionAnexoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'menu_capacitacioncapacitacion_anexo_tema',
                'managed': False,
            },
        ),
    ]
