# Generated by Django 2.2.6 on 2020-04-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0099_menucapacitacioncapacitacionanexotema'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_nave', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='planta',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uestado_planta', to='menu.Estado'),
        ),
    ]
