# Generated by Django 2.2.6 on 2020-04-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0100_auto_20200420_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='expositor',
            field=models.CharField(max_length=50, null=True, verbose_name='Expositor'),
        ),
    ]
