# Generated by Django 2.2.6 on 2020-05-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0101_capacitacioncapacitacion_expositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='imagen_acta',
            field=models.ImageField(blank=True, null=True, upload_to='foto_acta_capacitacion/'),
        ),
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='imagen_capacitacion',
            field=models.ImageField(blank=True, null=True, upload_to='foto_capacitacion/'),
        ),
    ]
