# Generated by Django 2.2.6 on 2020-05-29 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0102_auto_20200529_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='anio_cosecha',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Año Cosecha'),
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='etapa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='var_pep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Variedad_PEP'),
        ),
        migrations.CreateModel(
            name='siembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolsiembra', models.CharField(max_length=30, null=True, verbose_name='Siembra')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreacionSiembra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siembra',
                'verbose_name_plural': 'Siembras',
            },
        ),
        migrations.AddField(
            model_name='programaproduccion',
            name='anexo_siembra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSiembra', to='menu.siembra'),
        ),
    ]
