# Generated by Django 2.2.6 on 2020-06-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0103_auto_20200529_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaproduccionfeno',
            name='estado',
        ),
    ]
