# Generated by Django 2.2.6 on 2020-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0104_remove_programaproduccionfeno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='elementopep',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Elemento PEP'),
        ),
    ]
