# Generated by Django 2.2.6 on 2020-06-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0105_auto_20200602_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopep',
            name='anexo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoElementoPEP', to='menu.Estado'),
        ),
    ]
