# Generated by Django 2.2.6 on 2020-06-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0106_elementopep_anexo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementopep',
            old_name='anexo_id',
            new_name='anexo_estado',
        ),
    ]
