# Generated by Django 2.2.6 on 2020-06-15 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0107_auto_20200602_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenesAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(blank=True, max_length=30, null=True, verbose_name='Almacen')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Almacenes Athos',
                'verbose_name_plural': 'Almacenes Athos',
            },
        ),
        migrations.CreateModel(
            name='CalidadProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Calidad Producto')),
            ],
            options={
                'verbose_name': 'Calidad Producto',
                'verbose_name_plural': 'Calidad Producto',
            },
        ),
        migrations.CreateModel(
            name='CentrosAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Centros Athos')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaCentros', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionCEN', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionCEN', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centros Athos',
                'verbose_name_plural': 'Centros Athos',
            },
        ),
        migrations.CreateModel(
            name='ChoferesVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPat', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('ApellidoMat', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Materno ')),
                ('Nombres', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres ')),
                ('Dni', models.CharField(blank=True, max_length=30, null=True, verbose_name='DNI ')),
                ('Brevete', models.CharField(blank=True, max_length=30, null=True, verbose_name='N° BREVETE ')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoChoferes', to='menu.Estado')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaCH', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionCH', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionCH', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Choferes',
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='estadomaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_material', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Material')),
            ],
            options={
                'verbose_name': 'Estado Material',
                'verbose_name_plural': 'Estado Material',
            },
        ),
        migrations.CreateModel(
            name='GuiaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoqr', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codigo QR')),
                ('NroGuia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nro Guia')),
                ('fecha_transporte', models.DateField(blank=True, null=True, verbose_name='Fecha trasnporte')),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmaAthos', to='menu.AlmacenesAthos')),
                ('anexo_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoACen', to='menu.CentrosAthos')),
                ('anexo_chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaChoferes', to='menu.ChoferesVehiculos')),
                ('anexo_sociedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDatosEmp', to='menu.DatosEmpresa')),
            ],
            options={
                'verbose_name': 'Guia Athos',
                'verbose_name_plural': 'Guias Athos',
            },
        ),
        migrations.CreateModel(
            name='GuiaDetallesAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('peso_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_calidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCalidadM', to='menu.CalidadProducto')),
                ('anexo_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaAthos', to='menu.GuiaAthos')),
            ],
            options={
                'verbose_name': 'Guia Detalle Athos',
                'verbose_name_plural': 'Guias  Detalles Athos',
            },
        ),
        migrations.CreateModel(
            name='LugarAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fundo')),
                ('longitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoLugar', to='menu.Estado')),
            ],
            options={
                'verbose_name': 'Lugar Athos',
                'verbose_name_plural': 'Lugar Athos',
            },
        ),
        migrations.CreateModel(
            name='PlacasVehiculares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placas Vehiculares ')),
                ('placas2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Placas Vehiculares Tolba ')),
                ('capacidad_jabas', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'Placas Vehiculares',
                'verbose_name_plural': 'Placas Vehiculares',
            },
        ),
        migrations.CreateModel(
            name='TipoLugarAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='TipoLugar')),
            ],
            options={
                'verbose_name': 'Tipo Lugar Athos',
                'verbose_name_plural': 'Tipo Lugar Athos',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=15, null=True, verbose_name='Tipo de Vehiculo')),
            ],
            options={
                'verbose_name': 'Tipo Vehiculo',
                'verbose_name_plural': 'Tipos Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidad de Medida',
            },
        ),
        migrations.AlterModelOptions(
            name='programaproduccion',
            options={'ordering': ['anexo_variedad'], 'verbose_name': 'Programa Produccion', 'verbose_name_plural': 'Programas de Produccion'},
        ),
        migrations.AlterModelOptions(
            name='variedad',
            options={'ordering': ['cul'], 'verbose_name': 'variedad', 'verbose_name_plural': 'variedades'},
        ),
        migrations.CreateModel(
            name='UnidadVehicular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoChofer', to='menu.ChoferesVehiculos')),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoUVehicular', to='menu.Estado')),
                ('anexo_placas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlacas', to='menu.PlacasVehiculares')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionUV', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionUV', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Vehicular',
                'verbose_name_plural': 'Unidades Vehiculares',
            },
        ),
        migrations.CreateModel(
            name='UbicacionFundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiProgramaProduccion', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionUbiFU', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionUbiFU', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicacion Fundo',
                'verbose_name_plural': 'UUbicacion Fundo',
            },
        ),
        migrations.CreateModel(
            name='UbicacionesAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoUbi', to='menu.LugarAthos')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaAco', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionUbiAco', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionUbiAco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicacion Fundo',
                'verbose_name_plural': 'Ubicacion Fundo',
            },
        ),
        migrations.CreateModel(
            name='TipoParihuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parihuela', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripcion Parihuela ')),
                ('peso_parihuela', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoMaterialParihuela', to='menu.estadomaterial')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreaciontipoparihuela', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificaciontipoparihuela', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parihuelas',
                'verbose_name_plural': 'Parihuelas',
            },
        ),
        migrations.AddField(
            model_name='placasvehiculares',
            name='anexo_tipovehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlacaTipoVehiculo', to='menu.TipoVehiculo'),
        ),
        migrations.AddField(
            model_name='placasvehiculares',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreacionplacas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placasvehiculares',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificacionplacas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaterialTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo SAP')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoMaterialTrans', to='menu.estadomaterial')),
                ('anexo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUnidadMedidaTrans', to='menu.UnidadMedida')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreacionmaterialTrans', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificacionmaterialTrans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materiales Acopio Transporte',
                'verbose_name_plural': 'Materiales Acopio Transporte',
            },
        ),
        migrations.CreateModel(
            name='MaterialMMPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo SAP')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoMaterialMMPP', to='menu.estadomaterial')),
                ('anexo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUnidadMedidaMPPP', to='menu.UnidadMedida')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreacionmaterialMMPP', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificacionmaterialMMPP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materiales Acopio MMPP',
                'verbose_name_plural': 'Materiales Acopio MMPP',
            },
        ),
        migrations.CreateModel(
            name='MaterialAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesommpp_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoMaterial', to='menu.estadomaterial')),
                ('anexo_matmmpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMatMMPP', to='menu.MaterialMMPP')),
                ('anexo_mattransporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMatTransporte', to='menu.MaterialTransporte')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreacionmaterial', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificacionmaterial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materiales Acopio',
                'verbose_name_plural': 'Materiales Acopio',
            },
        ),
        migrations.AddField(
            model_name='lugarathos',
            name='anexo_tipolugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoLug', to='menu.TipoLugarAthos'),
        ),
        migrations.AddField(
            model_name='lugarathos',
            name='anexo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaLug', to='menu.ejezona'),
        ),
        migrations.CreateModel(
            name='InfoPalet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_jabas', models.DecimalField(decimal_places=0, max_digits=5)),
                ('pesobr_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesova_jabas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pesonet_palet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_guiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaDAthos', to='menu.GuiaDetallesAthos')),
                ('anexo_tipoparihuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialParihuela', to='menu.TipoParihuela')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioPalets', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPalets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Palet',
                'verbose_name_plural': 'Info Palets',
            },
        ),
        migrations.AddField(
            model_name='guiadetallesathos',
            name='anexo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialAcopio', to='menu.MaterialAcopio'),
        ),
        migrations.AddField(
            model_name='guiadetallesathos',
            name='anexo_ubi_mmpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiFundo', to='menu.UbicacionFundo'),
        ),
        migrations.AddField(
            model_name='guiadetallesathos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacioGuiaD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiadetallesathos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuiaD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='anexo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoGuiaVehiculos', to='menu.PlacasVehiculares'),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeGuia', to='menu.ejezona'),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='ubic_llegada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaLL', to='menu.LugarAthos'),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='ubic_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGuiaP', to='menu.LugarAthos'),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGuia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guiaathos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGuia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='almacenesathos',
            name='anexo_centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAlmacenCen', to='menu.CentrosAthos'),
        ),
        migrations.AddField(
            model_name='almacenesathos',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoAlmacen', to='menu.Estado'),
        ),
        migrations.AddField(
            model_name='almacenesathos',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionAlmaCEN', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='almacenesathos',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionAlmaCEN', to=settings.AUTH_USER_MODEL),
        ),
    ]
