# Generated by Django 2.2.6 on 2020-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0108_auto_20200615_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaathos',
            name='NroGuia',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nro Guia'),
        ),
    ]
