# Generated by Django 2.2.6 on 2020-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0109_auto_20200617_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenesathos',
            name='desc_almacen',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripcion Almacen'),
        ),
        migrations.AddField(
            model_name='centrosathos',
            name='desc_centro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripcion Centro'),
        ),
    ]
