# Generated by Django 2.2.6 on 2020-06-29 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0110_auto_20200623_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaritaAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcampo', models.CharField(max_length=50, null=True, verbose_name='QR Campo')),
                ('qrplaca', models.CharField(blank=True, max_length=50, null=True, verbose_name='QR Placas')),
                ('longitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('cantpasajeros', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('observacion', models.TextField(blank=True, max_length=300, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionGarita', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionGarita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garita Athos',
                'verbose_name_plural': 'Garita Athos',
            },
        ),
    ]
