# Generated by Django 2.2.6 on 2020-06-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0111_garitaathos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaathos',
            name='anexo_centro',
        ),
    ]
