# Generated by Django 2.2.6 on 2020-06-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0112_remove_guiaathos_anexo_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='garitaathos',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiGarita', to='menu.LugarAthos'),
        ),
    ]
