# Generated by Django 2.2.6 on 2020-06-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0113_garitaathos_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(max_length=15, null=True, verbose_name='Tipo de Transporte')),
            ],
            options={
                'verbose_name': 'Tipo Transporte',
                'verbose_name_plural': 'Tipos de Transporte',
            },
        ),
    ]
