# Generated by Django 2.2.6 on 2020-06-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0114_tipotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='placasvehiculares',
            name='anexo_tipotransporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlacaTipoTransporte', to='menu.TipoTransporte'),
        ),
    ]
