# Generated by Django 2.2.6 on 2020-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0115_placasvehiculares_anexo_tipotransporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_unidad', models.CharField(max_length=15, null=True, verbose_name='Tipo de Unidad')),
            ],
            options={
                'verbose_name': 'Tipo Unidad',
                'verbose_name_plural': 'Tipos de Unidades',
            },
        ),
    ]
