# Generated by Django 2.2.6 on 2020-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0117_placasvehiculares_anexo_tipounidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garitaathos',
            name='qrcampo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QR Campo'),
        ),
    ]
