# Generated by Django 2.2.6 on 2020-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0118_auto_20200710_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garitaathos',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
