# Generated by Django 2.2.6 on 2020-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0119_auto_20200711_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='placasvehiculares',
            name='n_soat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Soat '),
        ),
        migrations.AddField(
            model_name='placasvehiculares',
            name='vencimiento_rtecnica',
            field=models.DateField(blank=True, null=True, verbose_name='Vc. Revision Tecnica'),
        ),
        migrations.AddField(
            model_name='placasvehiculares',
            name='vencimiento_soat',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento soat'),
        ),
    ]
