# Generated by Django 2.2.6 on 2020-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0120_auto_20200711_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutasAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rutas Athos')),
            ],
            options={
                'verbose_name': 'Rutas Athos',
                'verbose_name_plural': 'Rutas Athos',
            },
        ),
    ]
