# Generated by Django 2.2.6 on 2020-07-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0121_rutasathos'),
    ]

    operations = [
        migrations.AddField(
            model_name='garitaathos',
            name='chofer_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chofer Referencial'),
        ),
        migrations.AddField(
            model_name='garitaathos',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRuta', to='menu.RutasAthos'),
        ),
    ]
