# Generated by Django 2.2.6 on 2020-07-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0122_auto_20200712_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='placasvehiculares',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoVehiculos', to='menu.Estado'),
        ),
    ]
