# Generated by Django 2.2.6 on 2020-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0123_placasvehiculares_anexo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejezona',
            name='cod_zona_eje',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Codigo Zona'),
        ),
    ]
