# Generated by Django 2.2.6 on 2020-07-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0124_ejezona_cod_zona_eje'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopalet',
            name='anexo_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoInfoAlmacen', to='menu.AlmacenesAthos'),
        ),
    ]
