# Generated by Django 2.2.6 on 2020-07-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0125_infopalet_anexo_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pproduccionvariable',
            name='anexo_campana',
        ),
        migrations.RemoveField(
            model_name='pproduccionvariable',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pproduccionvariable',
            name='fecha',
        ),
        migrations.CreateModel(
            name='SubVariableAgronomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_variable', models.CharField(blank=True, max_length=30, null=True, verbose_name='SubVariable')),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripcion')),
                ('anexo_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSubVariable', to='menu.VariableAgronomica')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoVariable', to='menu.Estado')),
            ],
            options={
                'verbose_name': 'Sub Variable Agronomica',
                'verbose_name_plural': 'Sub Variable Agronomica',
            },
        ),
    ]
