# Generated by Django 2.2.6 on 2020-07-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0126_auto_20200721_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pproduccionvariable',
            name='anexo_variable',
        ),
        migrations.AddField(
            model_name='pproduccionvariable',
            name='anexo_subvariable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.SubVariableAgronomica'),
        ),
    ]
