# Generated by Django 2.2.6 on 2020-07-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0127_auto_20200721_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpaletas',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoPaletas', to='menu.Estado'),
        ),
    ]
