# Generated by Django 2.2.6 on 2020-07-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0128_lpaletas_anexo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutasathos',
            name='anexo_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbiRutas', to='menu.LugarAthos'),
        ),
        migrations.AddField(
            model_name='rutasathos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
