# Generated by Django 2.2.6 on 2020-07-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0129_auto_20200729_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='garitaathos',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaGarita', to='menu.ejezona'),
        ),
        migrations.AlterField(
            model_name='garitaathos',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFunGarita', to='menu.fundo'),
        ),
        migrations.AlterField(
            model_name='rutasathos',
            name='anexo_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbifundo', to='menu.fundo'),
        ),
    ]
