# Generated by Django 2.2.6 on 2020-08-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0130_auto_20200730_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiadetallesathos',
            name='anexo_ubi_mmpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPFundo', to='menu.ProgramaProduccion'),
        ),
    ]
