# Generated by Django 2.2.6 on 2020-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0131_auto_20200802_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmmpp',
            name='abr_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Abreviatura  Material'),
        ),
    ]
