# Generated by Django 2.2.6 on 2020-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0132_materialmmpp_abr_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpaletasreal',
            name='fecha_lanzado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Lanzado'),
        ),
    ]
