# Generated by Django 2.2.6 on 2020-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0133_lpaletasreal_fecha_lanzado'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiposuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suelo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Suelo')),
            ],
            options={
                'verbose_name': 'Tipo Suelo',
                'verbose_name_plural': 'Tipo Suelo',
            },
        ),
    ]
