# Generated by Django 2.2.6 on 2020-08-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0135_programaproduccion_anexo_suelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaproduccion',
            name='anexo_suelo',
        ),
    ]
