# Generated by Django 2.2.6 on 2020-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0136_remove_programaproduccion_anexo_suelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='anexo_suelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoSuelo', to='menu.tiposuelo'),
        ),
    ]
