# Generated by Django 2.2.6 on 2020-08-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0137_lote_anexo_suelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpaletasreal',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoLanzado', to='menu.Turno'),
        ),
    ]
