# Generated by Django 2.2.6 on 2020-08-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0138_lpaletasreal_anexo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpaletasreal',
            name='fecha_hora_creacion',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Creación'),
        ),
    ]
