# Generated by Django 2.2.6 on 2020-09-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0139_auto_20200821_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpaletas',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPaletasCultivo', to='menu.cultivo'),
        ),
    ]
