# Generated by Django 2.2.6 on 2020-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0140_lpaletas_anexo_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsable'),
        ),
    ]
