# Generated by Django 2.2.6 on 2020-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0141_programaproduccion_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmmpp',
            name='desc_sap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material SAP'),
        ),
        migrations.AddField(
            model_name='materialmmpp',
            name='var_pep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAR PEP'),
        ),
    ]
