# Generated by Django 2.2.6 on 2020-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0142_auto_20200916_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='lugar_especifico',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar Especifico'),
        ),
    ]
