# Generated by Django 2.2.6 on 2020-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0143_capacitacioncapacitacion_lugar_especifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaproduccion',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
