# Generated by Django 2.2.6 on 2020-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0144_auto_20201111_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacioncapacitacion',
            options={'verbose_name': ' Conf. Capacitacion', 'verbose_name_plural': ' Conf. Capacitaciones'},
        ),
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='dniexpositor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='empresaexpositor',
            field=models.CharField(max_length=100, null=True, verbose_name='Expositor'),
        ),
    ]
