# Generated by Django 2.2.6 on 2020-12-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0145_auto_20201127_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoProgramaProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Turno')),
                ('hectareaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('densidad', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoPPEstado', to='menu.Estado')),
                ('anexo_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProgramaTurnoPP', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionTurnoPP', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModTurnoPP', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno-Programa de Produccion',
                'verbose_name_plural': 'Turno-Programa de Produccion',
            },
        ),
    ]
