# Generated by Django 2.2.6 on 2020-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0146_turnoprogramaproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoprogramaproduccion',
            name='hectareaje',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
