# Generated by Django 2.2.6 on 2020-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0148_auto_20201202_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementopep',
            options={'verbose_name': 'Etapas-Programa Produccion', 'verbose_name_plural': 'Eltapas-Programa Produccion'},
        ),
    ]
