# Generated by Django 2.2.6 on 2020-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0149_auto_20201204_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementopep',
            options={'verbose_name': 'Etapas-Programa Produccion', 'verbose_name_plural': 'Etapas-Programa Produccion'},
        ),
    ]
