# Generated by Django 2.2.6 on 2020-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0150_auto_20201204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaproduccionfeno',
            name='indice',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Indice'),
        ),
    ]
