# Generated by Django 2.2.6 on 2020-12-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0152_auto_20201214_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pproduccionvariable',
            options={'verbose_name': 'PP-variable Agronomica', 'verbose_name_plural': 'PP-variable Agronomica'},
        ),
        migrations.AlterModelOptions(
            name='programaproduccionfeno',
            options={'verbose_name': 'Programa Produccion -Fases Fenologicas', 'verbose_name_plural': 'Programa Produccion -Fases Fenologicas'},
        ),
    ]
