# Generated by Django 2.2.6 on 2020-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableagronomica',
            name='Variable',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Variable Agronomica'),
        ),
    ]
