# Generated by Django 2.2.6 on 2020-12-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0154_auto_20201228_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='placasvehiculares',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlacaZona', to='menu.ejezona'),
        ),
    ]
