# Generated by Django 2.2.6 on 2020-12-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0155_placasvehiculares_anexo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenesathos',
            name='anexo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaAlmacen', to='menu.ejezona'),
        ),
    ]
