# Generated by Django 2.2.6 on 2020-12-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0156_almacenesathos_anexo_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmmpp',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoMPPP', to='menu.cultivo'),
        ),
    ]
