# Generated by Django 2.2.6 on 2020-12-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0158_materialtransporte_anexo_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialacopio',
            name='anexo_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoMaterial', to='menu.cultivo'),
        ),
    ]
