# Generated by Django 2.2.6 on 2021-01-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0159_materialacopio_anexo_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Sabor')),
            ],
            options={
                'verbose_name': 'Tipo Sabor',
                'verbose_name_plural': 'Tipo Sabor',
            },
        ),
        migrations.AddField(
            model_name='materialmmpp',
            name='tipo_fruto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Fruto'),
        ),
    ]
