# Generated by Django 2.2.6 on 2021-01-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0161_hitosfenologicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitosfenologicos',
            name='anexo_variable',
        ),
    ]
