# Generated by Django 2.2.6 on 2021-01-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0162_remove_hitosfenologicos_anexo_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='placasvehiculares',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razon Social'),
        ),
    ]
