# Generated by Django 2.2.6 on 2021-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0163_placasvehiculares_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='variedad',
            name='tipo_fruta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Fruta'),
        ),
    ]
