# Generated by Django 2.2.6 on 2021-02-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0001_initial'),
        ('menu', '0164_variedad_tipo_fruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitosfenologicos',
            name='desc_hito',
        ),
        migrations.RemoveField(
            model_name='hitosfenologicos',
            name='numhito',
        ),
        migrations.RemoveField(
            model_name='hitosfenologicos',
            name='numsubhito',
        ),
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoHitosFenologicosGrupos', to='programaproduccion.Grupos'),
        ),
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_hito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoHitosFenologicosHitos', to='programaproduccion.Hitos'),
        ),
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_subgrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoHitosFenologicosSubGrupos', to='programaproduccion.SubGrupos'),
        ),
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_subhito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSubHitosFenologicos', to='programaproduccion.SubHitos'),
        ),
    ]
