# Generated by Django 2.2.6 on 2021-02-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0165_auto_20210204_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='anexo_suelo',
        ),
    ]
