# Generated by Django 2.2.6 on 2021-02-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0166_remove_lote_anexo_suelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnoprogramaproduccion',
            name='anexo_suelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSueloTurnoPP', to='menu.tiposuelo'),
        ),
    ]
