# Generated by Django 2.2.6 on 2021-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0167_turnoprogramaproduccion_anexo_suelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fundo',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsable'),
        ),
    ]
