# Generated by Django 2.2.6 on 2021-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0168_auto_20210218_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacioncapacitacion',
            name='imagen_acta',
            field=models.ImageField(blank=True, null=True, upload_to='foto_acta_capacitacion'),
        ),
        migrations.AlterField(
            model_name='capacitacioncapacitacion',
            name='imagen_capacitacion',
            field=models.ImageField(blank=True, null=True, upload_to='foto_capacitacion'),
        ),
    ]
