# Generated by Django 2.2.6 on 2021-03-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0169_auto_20210310_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': ' Estado Capacitacion',
                'verbose_name_plural': ' Estado Capacitaciones',
            },
        ),
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoCapacitacion', to='menu.EstadoCapacitacion'),
        ),
    ]
