# Generated by Django 2.2.6 on 2021-04-06 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0170_auto_20210323_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlacasVehiculares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rutas')),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleVehiculos', to='menu.PlacasVehiculares')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariocreacionDetplacas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariomodificacionDetplacas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Placas Vehiculares',
                'verbose_name_plural': 'Detalle Placas Vehiculares',
            },
        ),
    ]
