# Generated by Django 2.2.6 on 2021-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0171_detalleplacasvehiculares'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='idtema',
            field=models.CharField(max_length=50, null=True, verbose_name='id tema'),
        ),
    ]
