# Generated by Django 2.2.6 on 2021-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0172_capacitacioncapacitacion_idtema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitosfenologicos',
            name='valor_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hitosfenologicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
