# Generated by Django 2.2.6 on 2021-05-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0002_planfertilizacion_planmanoobra_planriego_plansanidad'),
        ('menu', '0173_auto_20210504_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementopep',
            name='anexo_fertilizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlanFertilizacionPEP', to='programaproduccion.PlanFertilizacion'),
        ),
        migrations.AddField(
            model_name='elementopep',
            name='anexo_obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlanObraPEP', to='programaproduccion.PlanManoObra'),
        ),
        migrations.AddField(
            model_name='elementopep',
            name='anexo_riego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlanRiegoPEP', to='programaproduccion.PlanRiego'),
        ),
        migrations.AddField(
            model_name='elementopep',
            name='anexo_sanidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlanSanidadPEP', to='programaproduccion.PlanSanidad'),
        ),
    ]
