# Generated by Django 2.2.6 on 2021-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalplanta_athos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_trab', models.CharField(blank=True, max_length=10, null=True)),
                ('tipdoc', models.CharField(blank=True, max_length=5, null=True)),
                ('NroDoc', models.CharField(blank=True, max_length=10, null=True)),
                ('ApellidoPat', models.CharField(blank=True, max_length=30, null=True)),
                ('ApellidoMat', models.CharField(blank=True, max_length=30, null=True)),
                ('Nombres', models.CharField(blank=True, max_length=27, null=True)),
                ('FecNac', models.CharField(blank=True, max_length=10, null=True)),
                ('PaisNacionalidad', models.CharField(blank=True, max_length=10, null=True)),
                ('Nacionalidad', models.CharField(blank=True, max_length=15, null=True)),
                ('Sexo', models.CharField(blank=True, max_length=6, null=True)),
                ('EstadoCivil', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'personalplanta_athos',
                'managed': False,
            },
        ),
    ]
