# Generated by Django 2.2.6 on 2021-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0175_personalplanta_athos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitosfenologicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hitosfenologicos',
            name='valor_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
