# Generated by Django 2.2.6 on 2021-06-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0007_auto_20210629_1059'),
        ('menu', '0176_auto_20210625_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciacapacitacion',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAsisAprobacion', to='capacitaciones.RespuestaAprobacion'),
        ),
    ]
