# Generated by Django 2.2.6 on 2021-07-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0177_asistenciacapacitacion_anexo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacioncapacitacion',
            name='anexo_alcance',
        ),
    ]
