# Generated by Django 2.2.6 on 2021-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0178_remove_capacitacioncapacitacion_anexo_alcance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransporte',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
