# Generated by Django 2.2.6 on 2021-07-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0179_auto_20210711_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopalet',
            name='anexo_envase2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialEnvase2', to='menu.MaterialTransporte'),
        ),
        migrations.AddField(
            model_name='infopalet',
            name='cant_jabas2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
