# Generated by Django 2.2.6 on 2021-07-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0180_auto_20210713_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacioncapacitacion',
            name='puestoexpositor',
            field=models.CharField(max_length=100, null=True, verbose_name='Puesto Expositor'),
        ),
    ]
