# Generated by Django 2.2.6 on 2021-09-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0003_areaathos'),
        ('menu', '0181_capacitacioncapacitacion_puestoexpositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAreaAthosHF', to='programaproduccion.AreaAthos'),
        ),
    ]
