# Generated by Django 2.2.6 on 2021-09-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaproduccion', '0004_tipohitos'),
        ('menu', '0182_hitosfenologicos_anexo_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitosfenologicos',
            name='anexo_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTipoAthosHF', to='programaproduccion.TipoHitos'),
        ),
    ]
