# Generated by Django 2.2.6 on 2021-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0183_hitosfenologicos_anexo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacapacitacion',
            name='nom_area',
            field=models.CharField(max_length=100, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='competenciacapacitacion',
            name='codigo',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigos'),
        ),
        migrations.AlterField(
            model_name='competenciacapacitacion',
            name='nom_capacitacion',
            field=models.CharField(max_length=100, null=True, verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='temacapacitacion',
            name='codigo',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigos'),
        ),
    ]
