# Generated by Django 2.2.6 on 2022-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0184_auto_20211021_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurardia',
            name='fecha_hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='configurardia',
            name='fecha_hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Fecha y Hora de Inicio'),
        ),
    ]
