# Generated by Django 2.2.6 on 2022-02-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0185_auto_20220108_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='inicio_campana',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Inicio de Campaña'),
        ),
    ]
