# Generated by Django 2.2.6 on 2022-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0186_programaproduccion_inicio_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='inicio_cosecha_clp',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha cosecha CLP'),
        ),
    ]
