# Generated by Django 2.2.6 on 2022-06-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='anexo_obra',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plan de Obra'),
        ),
    ]
