# Generated by Django 2.2.6 on 2022-06-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0188_auto_20220609_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='anexo_fertilizacion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plan de Fertilizacion'),
        ),
    ]
