# Generated by Django 2.2.6 on 2022-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0189_auto_20220609_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaproduccion',
            name='organos_campana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
