# Generated by Django 2.2.6 on 2022-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopep',
            name='anexo_riego',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plan de Riego'),
        ),
        migrations.AlterField(
            model_name='elementopep',
            name='anexo_sanidad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plan de Sanidad'),
        ),
    ]
