# Generated by Django 2.2.6 on 2021-06-17 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_trab', models.CharField(blank=True, max_length=10, null=True)),
                ('tipdoc', models.CharField(blank=True, max_length=5, null=True)),
                ('NroDoc', models.CharField(blank=True, max_length=10, null=True)),
                ('ApellidoPat', models.CharField(blank=True, max_length=30, null=True)),
                ('ApellidoMat', models.CharField(blank=True, max_length=30, null=True)),
                ('Nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('FecNac', models.CharField(blank=True, max_length=10, null=True)),
                ('PaisNacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('Sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('EstadoCivil', models.CharField(blank=True, max_length=10, null=True)),
                ('Posicion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal  Athos',
                'verbose_name_plural': 'Personal  Athos',
            },
        ),
    ]
