# Generated by Django 2.2.6 on 2021-11-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='GeneroPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Genero Personas',
                'verbose_name_plural': 'Genero Personas',
            },
        ),
        migrations.CreateModel(
            name='GradoInstruccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Grado de Instruccion',
                'verbose_name_plural': 'Grado de Instruccion',
            },
        ),
        migrations.CreateModel(
            name='RespuestasRrhh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Respuestas SI/NO RRHH',
                'verbose_name_plural': 'Selector Respuestas SI/NO RRHH',
            },
        ),
        migrations.CreateModel(
            name='SelectorPareja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Selector Parejas',
                'verbose_name_plural': 'Selector Parejas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Documentos',
                'verbose_name_plural': 'Tipo Documentos',
            },
        ),
        migrations.CreateModel(
            name='IngresoPersonalAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('ApellidoPat', models.CharField(blank=True, max_length=30, null=True)),
                ('ApellidoMat', models.CharField(blank=True, max_length=30, null=True)),
                ('Nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('FecNac', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_documentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoIngresoTipoDoc', to='rrhh.TipoDocumentos')),
                ('anexo_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoIngresoGenero', to='rrhh.GeneroPersonas')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionIngresoPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionIngresoPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Personal  Athos',
                'verbose_name_plural': 'Ingreso Personal  Athos',
            },
        ),
        migrations.CreateModel(
            name='FiltroPersonalAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('sancion', models.CharField(blank=True, max_length=15, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion_falta', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_falta', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionFiltroPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionFiltroPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Personal Filtro-  Athos',
                'verbose_name_plural': ' Personal Filtro-  Athos',
            },
        ),
        migrations.CreateModel(
            name='FichaPersonalAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('ApellidoPat', models.CharField(blank=True, max_length=30, null=True)),
                ('ApellidoMat', models.CharField(blank=True, max_length=30, null=True)),
                ('Nombres', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('celular_emergencia', models.BigIntegerField(blank=True, null=True)),
                ('nombre_pareja', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_pareja', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_pareja', models.BigIntegerField(blank=True, null=True)),
                ('cant_hijos', models.IntegerField(blank=True, null=True)),
                ('empresa_experiencia', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_experiencia', models.IntegerField(blank=True, null=True)),
                ('cargo_experiencia', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=100, null=True)),
                ('otra_sustancia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_alcohol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaRespuestaAlcohol', to='rrhh.RespuestasRrhh')),
                ('anexo_antecedentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaRespuesta', to='rrhh.RespuestasRrhh')),
                ('anexo_estadocivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaEstadoCivil', to='rrhh.EstadoCivil')),
                ('anexo_farmaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaRespuestaFarmaco', to='rrhh.RespuestasRrhh')),
                ('anexo_grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaGradoInstruccion', to='rrhh.GradoInstruccion')),
                ('anexo_pareja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaSelectorPareja', to='rrhh.SelectorPareja')),
                ('anexo_sustancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaRespuestaSustancia', to='rrhh.RespuestasRrhh')),
                ('anexo_tabaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFichaRespuestaTabaco', to='rrhh.RespuestasRrhh')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionFichaPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionFichaPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Personal  Athos',
                'verbose_name_plural': 'Ficha Personal  Athos',
            },
        ),
    ]
