# Generated by Django 2.2.6 on 2021-12-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0184_auto_20211021_1332'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0002_estadocivil_fichapersonalathos_filtropersonalathos_generopersonas_gradoinstruccion_ingresopersonalat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Area Empresa',
                'verbose_name_plural': 'Area Empresas',
            },
        ),
        migrations.CreateModel(
            name='RequerimientoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoAreaEmpReqPersonalAthos', to='rrhh.AreaEmpresa')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoReqPersonalAthos', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoReqPersonalAthos', to='menu.fundo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionReqPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionReqPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento Personal  Athos',
                'verbose_name_plural': 'Requerimiento Personal Athos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRequerimientoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_contratacion', models.IntegerField(blank=True, null=True)),
                ('rendimiento_esperado', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRedPersonalAthos', to='rrhh.RequerimientoPersonal')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioCreacionDetReqPersonalAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioModificacionDetReqPersonalAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Requerimiento Personal  Athos',
                'verbose_name_plural': 'Detalle Requerimiento Personal Athos',
            },
        ),
    ]
