# Generated by Django 2.2.6 on 2022-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_areaempresa_detallerequerimientopersonal_requerimientopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientopersonal',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
