# Generated by Django 2.2.6 on 2022-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_detallerequerimientopersonal_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientopersonal',
            name='cantidad_aprobada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
