# Generated by Django 2.2.6 on 2022-03-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        ('maestras', '0010_actividadesathos_laboresplantaathos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0005_detallerequerimientopersonal_cantidad_aprobada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionSemanalPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionSemanalPersonal', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionSemanalPersonal', to='menu.fundo')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProyeccionSemanalPersonal', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProyeccionSemanalPersonal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyeccion Semanal Personal',
                'verbose_name_plural': 'Proyeccion Semanal Personal',
            },
        ),
        migrations.CreateModel(
            name='DetalleProyeccionSemanalPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_cantidad', models.IntegerField(blank=True, null=True)),
                ('lunes_avance', models.IntegerField(blank=True, null=True)),
                ('martes_cantidad', models.IntegerField(blank=True, null=True)),
                ('martes_avance', models.IntegerField(blank=True, null=True)),
                ('miercoles_cantidad', models.IntegerField(blank=True, null=True)),
                ('miercoles_avance', models.IntegerField(blank=True, null=True)),
                ('jueves_cantidad', models.IntegerField(blank=True, null=True)),
                ('jueves_avance', models.IntegerField(blank=True, null=True)),
                ('viernes_cantidad', models.IntegerField(blank=True, null=True)),
                ('viernes_avance', models.IntegerField(blank=True, null=True)),
                ('sabado_cantidad', models.IntegerField(blank=True, null=True)),
                ('sabado_avance', models.IntegerField(blank=True, null=True)),
                ('domingo_cantidad', models.IntegerField(blank=True, null=True)),
                ('domingo_avance', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProyeccionSemanalPersonal', to='rrhh.ProyeccionSemanalPersonal')),
                ('anexo_labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLaborProyeccionSemanalPersonal', to='maestras.LaboresPlantaAthos')),
                ('anexo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPepProyeccionSemanalPersonal', to='menu.ProgramaProduccion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleProyeccionSemanalPersonal', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleProyeccionSemanalPersonal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Proyeccion Semanal Personal',
                'verbose_name_plural': 'Detalle Proyeccion Semanal Personal',
            },
        ),
    ]
