# Generated by Django 2.2.6 on 2022-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_detalleproyeccionsemanalpersonal_proyeccionsemanalpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='domingo_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='domingo_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='jueves_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='jueves_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='lunes_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='lunes_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='martes_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='martes_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='miercoles_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='miercoles_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='sabado_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='sabado_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='viernes_avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalpersonal',
            name='viernes_cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
