# Generated by Django 2.2.6 on 2022-10-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0007_auto_20220426_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductividadPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=150, null=True)),
                ('nave', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProduccionPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProduccionPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produccion Planta',
                'verbose_name_plural': 'Produccion Planta',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductividadPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProductividadPlanta', to='rrhh.ProductividadPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleProductividadPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleProductividadPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Productividad Planta',
                'verbose_name_plural': 'Detalle Productividad Planta',
            },
        ),
    ]
