# Generated by Django 2.2.6 on 2022-10-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0190_programaproduccion_organos_campana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0008_detalleproductividadplanta_productividadplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProductividadPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=40, null=True, verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Linea Productividad Planta',
                'verbose_name_plural': 'Linea Productividad Planta',
            },
        ),
        migrations.CreateModel(
            name='MesaProductividadPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(max_length=40, null=True, verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Mesa Productividad Planta',
                'verbose_name_plural': 'Mesa Productividad Planta',
            },
        ),
    ]
