# Generated by Django 2.2.6 on 2022-10-15 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0190_programaproduccion_organos_campana'),
        ('rrhh', '0009_detalleproductividadplantaasistencia_lineaproductividadplanta_mesaproductividadplanta_productividadp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductividadPlantaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_actividad_labor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActividadLaborProductividadPlantaAsistencia', to='menu.AreaPlanta')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProducPlProductividadPlantaAsistencia', to='rrhh.ProductividadPlanta')),
                ('anexo_fecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FechaProductividadPlantaAsistencia', to='menu.ConfigurarDia')),
                ('anexo_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LineaProductividadPlantaAsistencia', to='rrhh.LineaProductividadPlanta')),
                ('anexo_mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesaProductividadPlantaAsistencia', to='rrhh.MesaProductividadPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProduccionPlantaAsistencia', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProduccionPlantaAsistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productividad Planta Asistencia',
                'verbose_name_plural': 'Productividad Planta Asistencia',
            },
        ),
        migrations.CreateModel(
            name='DetalleProductividadPlantaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(max_length=100, null=True, verbose_name='QR')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IdDetalleProductividadPlantaAsistencia', to='rrhh.ProductividadPlantaAsistencia')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetUsercreacionProduccionPlantaAsistencia', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DetUserModProduccionPlantaAsistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Productividad Planta Asistencia',
                'verbose_name_plural': 'Detalle Productividad Planta Asistencia',
            },
        ),
    ]
