# Generated by Django 2.2.6 on 2021-01-02 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0159_materialacopio_anexo_cultivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_turno', models.CharField(max_length=15, null=True, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='UbicacionPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionCultivo', to='menu.cultivo')),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoUbicacion', to='menu.Estado')),
                ('anexo_nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoNavePlanta', to='menu.Nave')),
                ('anexo_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionPlanta', to='menu.Planta')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUbicacionZona', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUserCreateUbicacionPlantaAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUserEditUbicacionPlantaAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicacion Planta Produccion',
                'verbose_name_plural': 'Ubicacion Planta Produccion',
            },
        ),
        migrations.CreateModel(
            name='LanzadoPaletasGrIca2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzado', models.DateField(blank=True, null=True, verbose_name='Fecha Lanzado')),
                ('linea', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linea')),
                ('leerqr', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='leer qr')),
                ('npalet', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('njabas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoLanzadoGrIca2020', to='granada_planta.Turno')),
                ('anexo_ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLanzadoUbicacion2020GrIca', to='granada_planta.UbicacionPlanta')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoPlantaGr2020Ica', to='menu.EstadoPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioCreacionLanzadoGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioModLanzadoGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lanzado Planta Granada 2020-Ica',
                'verbose_name_plural': 'Lanzado Planta Granada 2020-Ica',
            },
        ),
    ]
