# Generated by Django 2.2.6 on 2021-01-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzadopaletasgrica2020',
            name='anexo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoLanzadoGrIca2020', to='menu.Turno'),
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
