# Generated by Django 2.2.6 on 2021-01-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0002_auto_20210102_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanzadopaletasgrica2020',
            name='fecha_hora_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
    ]
