# Generated by Django 2.2.6 on 2021-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0003_auto_20210102_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzadopaletasgrica2020',
            name='fecha_cosecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha'),
        ),
    ]
