# Generated by Django 2.2.6 on 2021-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0004_lanzadopaletasgrica2020_fecha_cosecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzadopaletasgrica2020',
            name='trazabilidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trazabilidad'),
        ),
    ]
