# Generated by Django 2.2.6 on 2021-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0005_lanzadopaletasgrica2020_trazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzadopaletasgrica2020',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='lanzadopaletasgrica2020',
            name='pep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PEP'),
        ),
    ]
