# Generated by Django 2.2.6 on 2021-06-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0020_programaproduccionplanta'),
        ('menu', '0174_auto_20210517_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granada_planta', '0006_auto_20210322_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePaletizadoGrIca2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzado', models.DateField(blank=True, null=True, verbose_name='Fecha Lanzado')),
                ('fecha_hora_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProgramaProduccion2020GrIca', to='planificacion.ProgramaProduccionPlanta')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoPrepaGrIca2020', to='menu.Turno')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioCreacionPaletizadoGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioModPaletizadoGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre Paletizado Planta Granada 2020-Ica',
                'verbose_name_plural': 'Pre Paletizado Planta Granada 2020-Ica',
            },
        ),
        migrations.CreateModel(
            name='DetallePrePaletizadoGrIca2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traza', models.BigIntegerField(blank=True, null=True, verbose_name='Trazabilidad')),
                ('fecha_hora_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetPrepalizado2020GrIca', to='granada_planta.PrePaletizadoGrIca2020')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioCreacionDetPaletizadoGr2020', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioModDetPaletizadoGr2020', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Pre Paletizado Planta Granada 2020-Ica',
                'verbose_name_plural': 'Detalle Pre Paletizado Planta Granada 2020-Ica',
            },
        ),
    ]
