# Generated by Django 2.2.6 on 2021-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0007_detalleprepaletizadogrica2020_prepaletizadogrica2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprepaletizadogrica2020',
            name='traza',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Trazabilidad'),
        ),
    ]
