# Generated by Django 2.2.6 on 2021-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0008_auto_20210622_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaletizadogrica2020',
            name='cantidad_cajas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
