# Generated by Django 2.2.6 on 2021-07-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0009_prepaletizadogrica2020_cantidad_cajas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPrePalet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado Pre Paletizado',
                'verbose_name_plural': 'Estado Pre Paletizado',
            },
        ),
        migrations.AddField(
            model_name='prepaletizadogrica2020',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion'),
        ),
        migrations.AddField(
            model_name='prepaletizadogrica2020',
            name='anexo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoPrepaGrIca2020', to='granada_planta.EstadoPrePalet'),
        ),
    ]
