# Generated by Django 2.2.6 on 2022-01-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0011_lanzadopaletasgrica2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineasPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lineas')),
            ],
            options={
                'verbose_name': 'Lineas Planta ',
                'verbose_name_plural': 'Lineas Planta ',
            },
        ),
    ]
