# Generated by Django 2.2.6 on 2022-03-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0012_lineasplanta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lanzadopaletasgrica2021',
            options={'verbose_name': 'Lanzado Planta Granada Ica 2022', 'verbose_name_plural': 'Lanzado Planta Granada Ica 2022'},
        ),
    ]
