# Generated by Django 2.2.6 on 2022-10-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granada_planta', '0014_lanzadopaletasarica2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineasPlantaHG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lineas')),
            ],
            options={
                'verbose_name': 'Lineas Planta HG',
                'verbose_name_plural': 'Lineas Planta HG',
            },
        ),
        migrations.AddField(
            model_name='lanzadopaletasarica2022',
            name='anexo_linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLineaLanzadoArIca202202', to='granada_planta.LineasPlantaHG'),
        ),
    ]
