# Generated by Django 2.2.6 on 2023-01-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0191_auto_20221121_1025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granada_planta', '0015_auto_20221019_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanzadoPaletasGrIca2023',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzado', models.DateField(blank=True, null=True, verbose_name='Fecha Lanzado')),
                ('linea', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linea')),
                ('leerqr', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='leer qr')),
                ('npalet', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('njabas', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha Cosecha')),
                ('trazabilidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trazabilidad')),
                ('pep', models.CharField(blank=True, max_length=255, null=True, verbose_name='PEP')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('fecha_hora_creacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTurnoLanzadoGrIca2023', to='menu.Turno')),
                ('anexo_ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLanzadoUbicacionGrIca2023', to='granada_planta.UbicacionPlanta')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoPlantaGrIca2023', to='menu.EstadoPlanta')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioCreacionLanzadoGr2023', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuarioModLanzadoGr2023', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lanzado Planta Granada Ica 2023',
                'verbose_name_plural': 'Lanzado Planta Granada Ica 2023',
            },
        ),
    ]
