# Generated by Django 2.2.6 on 2021-05-19 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Pedido')),
            ],
            options={
                'verbose_name': 'Etapa Pedido',
                'verbose_name_plural': 'Etapa Pedido',
            },
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Transporte')),
            ],
            options={
                'verbose_name': 'Tipo Transporte',
                'verbose_name_plural': 'Tipo Transporte',
            },
        ),
        migrations.CreateModel(
            name='MaestraRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMaestraRegion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMaestraRegion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestra Region',
                'verbose_name_plural': 'Maestra Region',
            },
        ),
        migrations.CreateModel(
            name='MaestraClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoClienteRegion', to='planificacion.MaestraRegion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMaestraCliente', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMaestraCliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maestra Clientes',
                'verbose_name_plural': 'Maestra Clientes',
            },
        ),
    ]
