# Generated by Django 2.2.6 on 2021-05-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoCategoria', to='menu.cultivo')),
            ],
            options={
                'verbose_name': 'Cateoria Cultivo',
                'verbose_name_plural': 'Categoria Cultivo',
            },
        ),
        migrations.CreateModel(
            name='MarcaPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMarcaCultivo', to='menu.cultivo')),
            ],
            options={
                'verbose_name': 'Marca Prod. Terminado',
                'verbose_name_plural': 'Marca Prod. Terminado',
            },
        ),
        migrations.CreateModel(
            name='TipoEnvase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Envase')),
            ],
            options={
                'verbose_name': 'Tipo Envase Prod. Terminado',
                'verbose_name_plural': 'Tipo Envase Prod. Terminado',
            },
        ),
        migrations.CreateModel(
            name='MaterialPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_abrev', models.IntegerField(blank=True, null=True, verbose_name='Codigo Abreviado')),
                ('cod_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Material')),
                ('desc_material', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Material')),
                ('grupo_art', models.IntegerField(blank=True, null=True, verbose_name='Grupo Articulo')),
                ('cod_sap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Sap')),
                ('desc_final', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion Material')),
                ('peso_neto', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('calibre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calibre')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCategoriaMatPT', to='planificacion.CategoriaCultivo')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoMatPT', to='menu.cultivo')),
                ('anexo_envase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEnvaseMatPT', to='planificacion.TipoEnvase')),
                ('anexo_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMarcaMatPT', to='planificacion.MarcaPT')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMaestraMateriales', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMaestraMateriales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Producto Terminado',
                'verbose_name_plural': 'Material Producto Terminado',
            },
        ),
    ]
