# Generated by Django 2.2.6 on 2021-05-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0002_categoriacultivo_marcapt_materialpt_tipoenvase'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacultivo',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='categoriacultivo',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='categoriacultivo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionCategpriaCult', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriacultivo',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModCategoriaCult', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcapt',
            name='fecha_hora_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha y Hora de Creación'),
        ),
        migrations.AddField(
            model_name='marcapt',
            name='fecha_hora_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación'),
        ),
        migrations.AddField(
            model_name='marcapt',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMarcaProdT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcapt',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMarcaProdT', to=settings.AUTH_USER_MODEL),
        ),
    ]
