# Generated by Django 2.2.6 on 2021-05-25 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0003_auto_20210521_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Despacho')),
                ('fecha_produccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Produccion')),
                ('num_pedido', models.IntegerField(blank=True, null=True, verbose_name='Numero Pedido')),
                ('pos_pedido', models.IntegerField(blank=True, null=True, verbose_name='Posicion Pedido')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrpcion Material')),
                ('un_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad Material')),
                ('peso_material', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cant_cajas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Cajas')),
                ('kpg', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('calibre', models.IntegerField(blank=True, null=True, verbose_name='Calibre')),
                ('num_semana', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasMatPT', to='planificacion.CategoriaCultivo')),
                ('anexo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoClientesPlVentas', to='planificacion.MaestraClientes')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoPlVentas', to='menu.cultivo')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoPlVentas', to='planificacion.EstadoPedido')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasVariedad', to='menu.MaterialMMPP')),
                ('anexo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTransportePlVentas', to='planificacion.TipoTransporte')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionPlVentas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModPlVentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Ventas',
                'verbose_name_plural': 'Plan Ventas',
            },
        ),
    ]
