# Generated by Django 2.2.6 on 2021-05-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        ('planificacion', '0004_planventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='planventas',
            name='anexo_variedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasVariedad', to='menu.MaterialMMPP'),
        ),
        migrations.AlterField(
            model_name='planventas',
            name='anexo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialPlVentas', to='planificacion.MaterialPT'),
        ),
    ]
