# Generated by Django 2.2.6 on 2021-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_auto_20210525_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planventas',
            name='fecha_despacho',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Despacho'),
        ),
        migrations.AlterField(
            model_name='planventas',
            name='fecha_produccion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Produccion'),
        ),
    ]
