# Generated by Django 2.2.6 on 2021-05-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0006_auto_20210525_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planventas',
            name='anexo_categoria',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='anexo_material',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='anexo_variedad',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='calibre',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='cant_cajas',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='desc_material',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='kpg',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='peso_material',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='pos_pedido',
        ),
        migrations.RemoveField(
            model_name='planventas',
            name='un_material',
        ),
        migrations.CreateModel(
            name='DetallePlanVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_pedido', models.IntegerField(blank=True, null=True, verbose_name='Posicion Pedido')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrpcion Material')),
                ('un_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad Material')),
                ('peso_material', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cant_cajas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Cajas')),
                ('kpg', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('calibre', models.IntegerField(blank=True, null=True, verbose_name='Calibre')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasMatPT', to='planificacion.CategoriaCultivo')),
                ('anexo_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasVariedad', to='planificacion.PlanVentas')),
                ('anexo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMaterialPlVentas', to='planificacion.MaterialPT')),
                ('anexo_variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPlVentasVariedad', to='menu.MaterialMMPP')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetPlVentas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetPlVentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Plan Ventas',
                'verbose_name_plural': 'Detalle Plan Ventas',
            },
        ),
    ]
