# Generated by Django 2.2.6 on 2021-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_auto_20210526_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialpt',
            name='cod_abrev',
        ),
        migrations.RemoveField(
            model_name='materialpt',
            name='desc_final',
        ),
    ]
