# Generated by Django 2.2.6 on 2021-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_auto_20210526_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanventas',
            name='anexo_categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrpcion Material'),
        ),
    ]
