# Generated by Django 2.2.6 on 2021-05-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_auto_20210526_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanventas',
            name='calibre',
        ),
    ]
