# Generated by Django 2.2.6 on 2021-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_remove_detalleplanventas_calibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanventas',
            name='anexo_calibre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='detalleplanventas',
            name='anexo_categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria'),
        ),
    ]
