# Generated by Django 2.2.6 on 2021-05-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_auto_20210526_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad Material')),
            ],
            options={
                'verbose_name': 'Unidad Material Prod. Terminado',
                'verbose_name_plural': 'Unidad Material Prod. Terminado',
            },
        ),
        migrations.AddField(
            model_name='materialpt',
            name='anexo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUnidadMatPT', to='planificacion.UnidadMaterial'),
        ),
    ]
