# Generated by Django 2.2.6 on 2021-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_auto_20210527_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanventas',
            name='cajas_palet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cajas Palet'),
        ),
        migrations.AddField(
            model_name='detalleplanventas',
            name='cant_palet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
