# Generated by Django 2.2.6 on 2021-05-27 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0013_auto_20210527_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.IntegerField(blank=True, null=True, verbose_name='Nro Orden')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrpcion Material')),
                ('un_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad Material')),
                ('peso_material', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cant_cajas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Cajas')),
                ('kpg', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('anexo_categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('anexo_calibre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calibre')),
                ('anexo_variedad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Variedad')),
                ('cajas_palet', models.IntegerField(blank=True, null=True, verbose_name='Cajas Palet')),
                ('cant_palet', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalleplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleProcesoPlVentas', to='planificacion.PlanVentas')),
                ('anexo_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProcesoPlVentas', to='planificacion.PlanVentas')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionOrdenProceso', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModOrdenProceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Proceso',
                'verbose_name_plural': 'Orden Proceso',
            },
        ),
    ]
