# Generated by Django 2.2.6 on 2021-05-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0014_ordenproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproceso',
            name='anexo_detalleplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleProcesoPlVentas', to='planificacion.DetallePlanVentas'),
        ),
    ]
