# Generated by Django 2.2.6 on 2021-05-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0015_auto_20210527_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanventas',
            name='anexo_detalle',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='anexo_detalleplan',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='anexo_plan',
        ),
        migrations.AddField(
            model_name='ordenproceso',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetallePedOrden', to='planificacion.DetallePlanVentas'),
        ),
    ]
