# Generated by Django 2.2.6 on 2021-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0016_auto_20210528_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproceso',
            name='anexo_calibre',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='anexo_categoria',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='anexo_variedad',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='cajas_palet',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='cant_palet',
        ),
        migrations.RemoveField(
            model_name='ordenproceso',
            name='un_material',
        ),
    ]
