# Generated by Django 2.2.6 on 2021-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0017_auto_20210528_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproceso',
            name='consumo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consumos Cajas'),
        ),
    ]
