# Generated by Django 2.2.6 on 2021-05-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0018_ordenproceso_consumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproceso',
            name='peso_material',
        ),
    ]
