# Generated by Django 2.2.6 on 2021-06-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0019_remove_ordenproceso_peso_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaProduccionPlanta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_orden', models.IntegerField(blank=True, null=True, verbose_name='Posicion Orden')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrpcion Material')),
                ('cant_cajas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Cajas')),
                ('kpg', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('consumo', models.IntegerField(blank=True, null=True, verbose_name='Consumos Cajas')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProgramaOrden', to='planificacion.OrdenProceso')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionPProduccionPlanta', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModPProduccionPlanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa Produccion Planta',
                'verbose_name_plural': 'Programa Produccion Planta',
            },
        ),
    ]
