# Generated by Django 2.2.6 on 2021-07-26 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0020_programaproduccionplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVentas2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_campana', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año Campaña')),
                ('cultivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año Campaña')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('trimestre', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='Mes')),
                ('semana', models.IntegerField(blank=True, null=True, verbose_name='Numero Pedido')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('codigo_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Cliente')),
                ('nombre_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Cliente')),
                ('cod_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Material')),
                ('desc_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion Material')),
                ('um', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('kgt', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tipo_despacho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Despacho')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Region')),
                ('continente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Continente')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionPlVentas2021', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModPlVentas2021', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Ventas 2021',
                'verbose_name_plural': 'Plan Ventas 2021',
            },
        ),
    ]
