# Generated by Django 2.2.6 on 2020-12-08 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0150_auto_20201204_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50, verbose_name='Metodo')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionMetodoRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModMetodoRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metodo Riego',
                'verbose_name_plural': 'Metodo Riego',
            },
        ),
        migrations.CreateModel(
            name='EquiposRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=50, verbose_name='Equipo')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('reservorio', models.CharField(max_length=50, verbose_name='Reservorio')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoRiego', to='menu.cultivo')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoRiego', to='menu.Estado')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaRiego', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionEquipoRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModEquipoRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo Riego',
                'verbose_name_plural': 'Equipo Riego',
            },
        ),
    ]
