# Generated by Django 2.2.6 on 2020-12-09 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0150_auto_20201204_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0002_equiposriego_metodoriego'),
    ]

    operations = [
        migrations.CreateModel(
            name='PozosRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Pozo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo Autorizacion')),
                ('npozo', models.IntegerField(blank=True, null=True, verbose_name='NroPozo')),
                ('capacidad', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('capacidad_real', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaPozoRiego', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionPozoRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModPozoRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pozo Riego',
                'verbose_name_plural': 'Pozo Riego',
            },
        ),
    ]
