# Generated by Django 2.2.6 on 2020-12-09 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0003_pozosriego'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeyNutricicionRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Codigo Material')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Comercial')),
                ('um', models.CharField(max_length=50, verbose_name='UM')),
                ('n', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('p2o5', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('k2o', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cao', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('mgo', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('s', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fe', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('mn', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('zn', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('mo', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ci', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('cu', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('h2o', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyProductosRiego', to='riego.ProductosRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionLeyRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModLeyRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ley Nutricion Riego',
                'verbose_name_plural': 'Ley Nutricion Riego',
            },
        ),
    ]
