# Generated by Django 2.2.6 on 2020-12-09 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0004_leynutricicionriego'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeyNutricicionRiego',
            new_name='LeyNutricionRiego',
        ),
    ]
