# Generated by Django 2.2.6 on 2020-12-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0150_auto_20201204_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0005_auto_20201209_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionSemanalRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('semana', models.IntegerField(blank=True, null=True, verbose_name='Semana')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionCultivoRiego', to='menu.cultivo')),
                ('anexo_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionFundoRiego', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProyeccionZonaRiego', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyeccion Semanal Riego',
                'verbose_name_plural': 'Proyeccion Semanal Riego',
            },
        ),
        migrations.CreateModel(
            name='DetalleProyeccionSemanalRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_material', models.IntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('um', models.CharField(max_length=50, verbose_name='UM')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProyeccionCultivoRiego', to='riego.ProyeccionSemanalRiego')),
                ('anexo_ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetalleProySemRiego', to='riego.LeyNutricionRiego')),
                ('anexo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoProductosDetalleProySemRiego', to='riego.ProductosRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Proyeccion Semanal Riego',
                'verbose_name_plural': 'Detalle-Proyeccion Semanal Riego',
            },
        ),
    ]
