# Generated by Django 2.2.6 on 2020-12-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0150_auto_20201204_1425'),
        ('riego', '0006_detalleproyeccionsemanalriego_proyeccionsemanalriego'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRiegoFertilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('conductividad_e', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('kc', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensiometro30', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensiometro60', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensiometro90', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('conductividad_e_sol', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_sol', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCultivoRiegoFerti', to='menu.cultivo')),
                ('anexo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEquiposFertRiego', to='riego.EquiposRiego')),
                ('anexo_fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoRiegofert', to='menu.fundo')),
                ('anexo_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegistroFertRiego', to='riego.MetodoRiego')),
                ('anexo_pep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPPRiego', to='menu.ProgramaProduccion')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoZonaRiegoFert', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRegRiegFer', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRegRiegFer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Riego Fertizacion',
                'verbose_name_plural': 'Registro Riego Fertizacion',
            },
        ),
    ]
