# Generated by Django 2.2.6 on 2020-12-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0007_registroriegofertilizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproyeccionsemanalriego',
            name='anexo_producto',
        ),
        migrations.RemoveField(
            model_name='detalleproyeccionsemanalriego',
            name='cod_material',
        ),
        migrations.RemoveField(
            model_name='detalleproyeccionsemanalriego',
            name='um',
        ),
    ]
