# Generated by Django 2.2.6 on 2020-12-10 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0008_auto_20201210_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProyeccionSemanalRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem2', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem3', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem4', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegDetProyeccionCultivoRiego', to='riego.DetalleProyeccionSemanalRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionRegProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModRegProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Semanal-Proyeccion Semanal Riego',
                'verbose_name_plural': 'Detalle Semanal-Proyeccion Semanal Riego',
            },
        ),
    ]
