# Generated by Django 2.2.6 on 2020-12-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0009_registroproyeccionsemanalriego'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRegistroRiegoFertilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('volumen', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_inicial', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_final', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ha_riego', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegRiegoFert', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetRegRiegFer', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetRegRiegFer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Registro Riego Fertizacion',
                'verbose_name_plural': 'Detalle-Registro Riego Fertizacion',
            },
        ),
    ]
