# Generated by Django 2.2.6 on 2020-12-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0010_detalleregistroriegofertilizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegRiegoFert', to='riego.RegistroRiegoFertilizacion'),
        ),
    ]
