# Generated by Django 2.2.6 on 2020-12-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0011_auto_20201211_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLeyRiegoFertilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_producto', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('codigo_modulador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Modulador')),
                ('codigo_regador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Regador')),
                ('valvula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valvula')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyRegRiegoFert', to='riego.RegistroRiegoFertilizacion')),
                ('anexo_ley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert', to='riego.LeyNutricionRiego')),
                ('anexo_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEquiposDetRegRiegoFert', to='riego.EquiposRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetLeyRegRiegFer', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetLeyRegRiegFer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Ley-Registro Riego Fertizacion',
                'verbose_name_plural': 'Detalle Ley-Registro Riego Fertizacion',
            },
        ),
    ]
