# Generated by Django 2.2.6 on 2020-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0012_detalleleyriegofertilizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='valvula_riego',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valvula Riego'),
        ),
    ]
