# Generated by Django 2.2.6 on 2020-12-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0013_detalleregistroriegofertilizacion_valvula_riego'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleleyriegofertilizacion',
            options={'verbose_name': 'Detalle2-Confirmativa de Fertilizantes ', 'verbose_name_plural': 'Detalle2-Confirmativa de Fertilizantes '},
        ),
        migrations.AlterModelOptions(
            name='detalleregistroriegofertilizacion',
            options={'verbose_name': 'Detalle1-Confirmativa de Riego', 'verbose_name_plural': 'Detalle1-Confirmativa de Riego'},
        ),
    ]
