# Generated by Django 2.2.6 on 2020-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0014_auto_20201214_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_procedencia',
        ),
        migrations.RemoveField(
            model_name='detalleleyriegofertilizacion',
            name='codigo_modulador',
        ),
        migrations.RemoveField(
            model_name='detalleleyriegofertilizacion',
            name='codigo_regador',
        ),
        migrations.RemoveField(
            model_name='detalleleyriegofertilizacion',
            name='valvula',
        ),
    ]
