# Generated by Django 2.2.6 on 2020-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0015_auto_20201214_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='operador_riego_sap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='regador_sap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
