# Generated by Django 2.2.6 on 2020-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0016_auto_20201214_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='eto_acu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
