# Generated by Django 2.2.6 on 2020-12-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0153_auto_20201214_1146'),
        ('riego', '0017_registroriegofertilizacion_eto_acu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleleyriegofertilizacion',
            old_name='total_producto',
            new_name='total_producto1',
        ),
        migrations.RemoveField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley',
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert1', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert10', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert2', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert3', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert4', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert5', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert6', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert7', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert8', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_ley9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert9', to='riego.LeyNutricionRiego'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyProgramaPr', to='menu.ProgramaProduccion'),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto6',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto7',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto8',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleleyriegofertilizacion',
            name='total_producto9',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
