# Generated by Django 2.2.6 on 2021-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0018_auto_20201218_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='conductividad_e_sol',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='kc',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='operador_riego_sap',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='ph_sol',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='regador_sap',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='tensiometro30',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='tensiometro60',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='tensiometro90',
        ),
    ]
