# Generated by Django 2.2.6 on 2021-02-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0019_auto_20210222_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanqueRiegoFertilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tanque Riego Fertizacion',
                'verbose_name_plural': 'Tanque Riego Fertizacion',
            },
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='hectareaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='kc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='turno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='anexo_tanque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTanqueRiegoFert', to='riego.TanqueRiegoFertilizacion'),
        ),
    ]
