# Generated by Django 2.2.6 on 2021-02-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0020_auto_20210222_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleLeyRiegoFertilizacion',
        ),
    ]
