# Generated by Django 2.2.6 on 2021-02-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0021_delete_detalleleyriegofertilizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetRequerimentoRiegoFert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_producto', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_requerimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Requerimiento')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegRiegoFert', to='riego.DetalleRegistroRiegoFertilizacion')),
                ('anexo_ley', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyDetRegRiegoFert1', to='riego.LeyNutricionRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetReqRegRiegFer', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetReqRegRiegFer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle2-Requerimiento de Fertilizantes ',
                'verbose_name_plural': 'Detalle2-Requerimiento de Fertilizantes ',
            },
        ),
    ]
