# Generated by Django 2.2.6 on 2021-02-24 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0022_detrequerimentoriegofert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetRequerimentoRiegoFert',
            new_name='DetRequerimientoRiegoFert',
        ),
    ]
