# Generated by Django 2.2.6 on 2021-02-25 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0023_auto_20210224_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoRequerimientoRiegoFert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fecha_consumo', models.DateField(blank=True, null=True, verbose_name='Fecha Consumo')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Regador')),
                ('ph_agua', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_agua', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_solucion', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_solucion', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio20', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio40', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio60', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio90', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_inicial', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_final', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('paf', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pdf', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pdvr', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoConsumoRegRiegoFert', to='riego.DetRequerimientoRiegoFert')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionConsumoReqRegRiegFer', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModConsumoReqRegRiegFer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle2-COnsumo Requerimiento de Fertilizantes ',
                'verbose_name_plural': 'Detalle2-COnsumo Requerimiento de Fertilizantes ',
            },
        ),
    ]
