# Generated by Django 2.2.6 on 2021-03-01 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0168_auto_20210218_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0024_consumorequerimientoriegofert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplotacionPozos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoExplotacionPozo', to='riego.PozosRiego')),
                ('anexo_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEjeExplotacion', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionExplotacionPozo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModExplotacionPozo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EXPLOTACION POZOS',
                'verbose_name_plural': 'EXPLOTACION POZOS',
            },
        ),
    ]
