# Generated by Django 2.2.6 on 2021-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0025_explotacionpozos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptaExplotacionPozos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta Explotacion pozos',
                'verbose_name_plural': 'Respuesta Explotacion pozos',
            },
        ),
    ]
