# Generated by Django 2.2.6 on 2021-03-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0026_rptaexplotacionpozos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExplotacionPozos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('hidro_inicial', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('hidro_final', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('nivel_estatico', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('nivel_dinamico', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleExplotacion', to='riego.ExplotacionPozos')),
                ('anexo_rpta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo1', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo2', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo3', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo4', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo5', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo6', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo7', to='riego.RptaExplotacionPozos')),
                ('anexo_rpta8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRptaPozo8', to='riego.RptaExplotacionPozos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetExplotacionPozo', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetExplotacionPozo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DETALLE EXPLOTACION POZOS',
                'verbose_name_plural': 'DETALLE EXPLOTACION POZOS',
            },
        ),
    ]
