# Generated by Django 2.2.6 on 2021-03-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0027_detalleexplotacionpozos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='hora_inicio',
        ),
    ]
