# Generated by Django 2.2.6 on 2021-03-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0028_auto_20210305_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='caudal_final',
        ),
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='caudal_inicial',
        ),
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='ha_riego',
        ),
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='valvula_riego',
        ),
        migrations.RemoveField(
            model_name='detalleregistroriegofertilizacion',
            name='volumen',
        ),
    ]
