# Generated by Django 2.2.6 on 2021-03-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0029_auto_20210305_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='conductividad_e',
        ),
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='ph',
        ),
    ]
