# Generated by Django 2.2.6 on 2021-03-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0030_auto_20210305_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumorequerimientoriegofert',
            options={'verbose_name': 'Capa4-COnsumo Requerimiento de Fertilizantes ', 'verbose_name_plural': 'Capa4-COnsumo Requerimiento de Fertilizantes '},
        ),
        migrations.AlterModelOptions(
            name='detalleregistroriegofertilizacion',
            options={'verbose_name': 'Capa2-Regostro Riego Fertilizacion', 'verbose_name_plural': 'Capa2-Regostro Riego Fertilizacion'},
        ),
        migrations.AlterModelOptions(
            name='detrequerimientoriegofert',
            options={'verbose_name': 'Capa3-Requerimiento de Fertilizantes ', 'verbose_name_plural': 'Capa3-Requerimiento de Fertilizantes '},
        ),
        migrations.AlterModelOptions(
            name='registroriegofertilizacion',
            options={'verbose_name': 'Capa1-Registro Riego Fertizacion', 'verbose_name_plural': 'Capa1-Registro Riego Fertizacion'},
        ),
    ]
