# Generated by Django 2.2.6 on 2021-03-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0168_auto_20210218_1627'),
        ('riego', '0031_auto_20210305_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozosriego',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoFundoPozoRiego', to='menu.fundo'),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_abr',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_ago',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_dic',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_ene',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_feb',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_jul',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_jun',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_mar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_may',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_nov',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_oct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='capacidad_sep',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
