# Generated by Django 2.2.6 on 2021-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0032_auto_20210309_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozosriego',
            name='caudal_autorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pozosriego',
            name='factor_correccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
