# Generated by Django 2.2.6 on 2021-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0033_auto_20210309_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='nroreserva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
