# Generated by Django 2.2.6 on 2021-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0034_registroriegofertilizacion_nroreserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumorequerimientoriegofert',
            name='observacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='consumorequerimientoriegofert',
            name='codigo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Codigo Regador'),
        ),
    ]
