# Generated by Django 2.2.6 on 2021-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0035_auto_20210309_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='eto_acu',
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='eto_acu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
