# Generated by Django 2.2.6 on 2021-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0036_auto_20210309_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleregistroriegofertilizacion',
            options={'verbose_name': 'Capa2-Detalle Registro Riego Fertilizacion', 'verbose_name_plural': 'Capa2-Detalle Registro Riego Fertilizacion'},
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='valvula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valvula'),
        ),
    ]
