# Generated by Django 2.2.6 on 2021-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0037_auto_20210309_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='proporcion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='solucion_madre',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
