# Generated by Django 2.2.6 on 2021-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0038_auto_20210309_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='eto_acu',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='hectareaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='kc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='proporcion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='pulso5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleregistroriegofertilizacion',
            name='solucion_madre',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
