# Generated by Django 2.2.6 on 2021-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0039_auto_20210310_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumorequerimientoriegofert',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
