# Generated by Django 2.2.6 on 2021-03-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0040_auto_20210310_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleexplotacionpozos',
            options={'verbose_name': 'CAPA2-DETALLE EXPLOTACION POZOS', 'verbose_name_plural': 'CAPA2-DETALLE EXPLOTACION POZOS'},
        ),
        migrations.AlterModelOptions(
            name='explotacionpozos',
            options={'verbose_name': 'CAPA1-EXPLOTACION POZOS', 'verbose_name_plural': 'CAPA1-EXPLOTACION POZOS'},
        ),
    ]
