# Generated by Django 2.2.6 on 2021-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0041_auto_20210312_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleexplotacionpozos',
            name='hidro_final',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleexplotacionpozos',
            name='hidro_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
