# Generated by Django 2.2.6 on 2021-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0042_auto_20210315_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposriego',
            name='factor_correccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
