# Generated by Django 2.2.6 on 2021-04-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0043_equiposriego_factor_correccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='fecha',
        ),
    ]
