# Generated by Django 2.2.6 on 2021-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0044_remove_registroriegofertilizacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
