# Generated by Django 2.2.6 on 2021-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0045_auto_20210419_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleregistroriegofertilizacion',
            name='anexo_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
