# Generated by Django 2.2.6 on 2021-04-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0046_detalleregistroriegofertilizacion_anexo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detrequerimientoriegofert',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetRegRiegoFert1', to='riego.RegistroRiegoFertilizacion'),
        ),
    ]
