# Generated by Django 2.2.6 on 2021-04-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0047_auto_20210419_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detrequerimientoriegofert',
            name='anexo_detalle',
        ),
    ]
