# Generated by Django 2.2.6 on 2021-04-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0048_remove_detrequerimientoriegofert_anexo_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetReqRiegoFert1', to='riego.RegistroRiegoFertilizacion'),
        ),
    ]
