# Generated by Django 2.2.6 on 2021-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0049_detrequerimientoriegofert_anexo_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='domingo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='jueves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='lunes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='martes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='miercoles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='sabado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='viernes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
