# Generated by Django 2.2.6 on 2021-04-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0050_auto_20210419_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detrequerimientoriegofert',
            name='fecha_requerimiento',
        ),
    ]
