# Generated by Django 2.2.6 on 2021-04-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0051_remove_detrequerimientoriegofert_fecha_requerimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='caudal_final',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='caudal_inicial',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='ce_agua',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='ce_solucion',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='paf',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='pdvr',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='ph_agua',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='ph_solucion',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='tensio20',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='tensio40',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='tensio60',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='tensio90',
        ),
        migrations.RemoveField(
            model_name='consumorequerimientoriegofert',
            name='volumen',
        ),
        migrations.CreateModel(
            name='DetalleRequerimientoRiegot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Codigo Regador')),
                ('ph_agua', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_agua', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ph_solucion', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ce_solucion', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio20', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio40', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio60', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('tensio90', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_inicial', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('caudal_final', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('paf', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pdf', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('pdvr', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('observacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleConsumoReqRegRieg', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleConsumoReqRegRieg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa-COnsumo Requerimiento de Riego ',
                'verbose_name_plural': 'Capa-COnsumo Requerimiento de Riego ',
            },
        ),
    ]
