# Generated by Django 2.2.6 on 2021-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0052_auto_20210419_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='fecha_consumo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Consumo'),
        ),
    ]
