# Generated by Django 2.2.6 on 2021-04-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0053_detallerequerimientoriegot_fecha_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='anexo_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleRegRiegoFertilizacion1', to='riego.DetalleRegistroRiegoFertilizacion'),
        ),
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
