# Generated by Django 2.2.6 on 2021-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0054_auto_20210419_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumorequerimientoriegofert',
            options={'verbose_name': 'Capa3-Consumo Requerimiento de Fertilizantes ', 'verbose_name_plural': 'Capa3-Consumo Requerimiento de Fertilizantes '},
        ),
        migrations.AlterModelOptions(
            name='detalleregistroriegofertilizacion',
            options={'verbose_name': 'Capa2-Detalle  Riego ', 'verbose_name_plural': 'Capa2-Detalle  Riego '},
        ),
        migrations.AlterModelOptions(
            name='detallerequerimientoriegot',
            options={'verbose_name': 'Capa3-COnsumo Requerimiento de Riego ', 'verbose_name_plural': 'Capa3-COnsumo Requerimiento de Riego '},
        ),
        migrations.AlterModelOptions(
            name='detrequerimientoriegofert',
            options={'verbose_name': 'Capa2-Requerimiento de Fertilizantes ', 'verbose_name_plural': 'Capa2-Requerimiento de Fertilizantes '},
        ),
    ]
