# Generated by Django 2.2.6 on 2021-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0055_auto_20210419_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
