# Generated by Django 2.2.6 on 2021-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0056_registroriegofertilizacion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroriegofertilizacion',
            name='idequipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipo'),
        ),
    ]
