# Generated by Django 2.2.6 on 2021-04-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0057_registroriegofertilizacion_idequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroriegofertilizacion',
            name='idequipo',
        ),
    ]
