# Generated by Django 2.2.6 on 2021-04-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0058_remove_registroriegofertilizacion_idequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequerimientoriegot',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
