# Generated by Django 2.2.6 on 2021-04-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0059_auto_20210429_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerequerimientoriegot',
            name='volumen',
        ),
    ]
