# Generated by Django 2.2.6 on 2021-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0060_remove_detallerequerimientoriegot_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='tensio30',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
