# Generated by Django 2.2.6 on 2021-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0061_detallerequerimientoriegot_tensio30'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectorPulsoRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Selector Pulso Riego',
                'verbose_name_plural': 'Selector Pulso Riego',
            },
        ),
    ]
