# Generated by Django 2.2.6 on 2021-04-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0062_selectorpulsoriego'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='anexo_pulso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPulsoDetRiegoT', to='riego.SelectorPulsoRiego'),
        ),
    ]
