# Generated by Django 2.2.6 on 2021-04-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0172_capacitacioncapacitacion_idtema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0063_detallerequerimientoriegot_anexo_pulso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadoresRiegoAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sap', models.IntegerField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNI')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
                ('funcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funcion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOperadorEstadoR', to='menu.Estado')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOperadorFundoR', to='menu.ejezona')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOperadorZonaR', to='menu.ejezona')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionOperadorRieAthos', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModOperadorRieAthos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador Riego Athos',
                'verbose_name_plural': 'Operador Riego Athos',
            },
        ),
    ]
