# Generated by Django 2.2.6 on 2021-04-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0064_operadoresriegoathos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadoresriegoathos',
            name='anexo_fundo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOperadorFundoR', to='menu.fundo'),
        ),
    ]
