# Generated by Django 2.2.6 on 2021-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0067_auto_20210525_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiposriego',
            name='centro_costo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
