# Generated by Django 2.2.6 on 2021-06-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0068_equiposriego_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='anexo_operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoOpeDetRiegoT', to='riego.OperadoresRiegoAthos'),
        ),
    ]
