# Generated by Django 2.2.6 on 2021-06-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0174_auto_20210517_0914'),
        ('riego', '0069_detallerequerimientoriegot_anexo_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionsemanalriego',
            name='anexo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoPepDetalleProySemRiego', to='menu.ProgramaProduccion'),
        ),
    ]
