# Generated by Django 2.2.6 on 2021-06-18 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riego', '0070_detalleproyeccionsemanalriego_anexo_pep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemDetalleProyeccionSemanalRiego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem2', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem3', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('sem4', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetProyeccionCultivoRiego', to='riego.DetalleProyeccionSemanalRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionSemDetProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModSemDetProyeccionSemanalRiego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle-Proyeccion Semanal Riego-Sem x',
                'verbose_name_plural': 'Detalle-Proyeccion Semanal Riego-Sem x',
            },
        ),
    ]
