# Generated by Django 2.2.6 on 2021-06-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0071_semdetalleproyeccionsemanalriego'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproyeccionsemanalriego',
            name='sem5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyeccionsemanalriego',
            name='anexo_detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoRegProyeccionCultivoRiego', to='riego.ProyeccionSemanalRiego'),
        ),
    ]
