# Generated by Django 2.2.6 on 2021-06-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0072_auto_20210623_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproyeccionsemanalriego',
            name='anexo_ley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoLeyRegProySemRiego', to='riego.LeyNutricionRiego'),
        ),
    ]
