# Generated by Django 2.2.6 on 2021-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0073_registroproyeccionsemanalriego_anexo_ley'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequerimientoriegot',
            name='caudal_final',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='detallerequerimientoriegot',
            name='caudal_inicial',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
