# Generated by Django 2.2.6 on 2021-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0074_auto_20210701_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientoriegot',
            name='eto_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
