# Generated by Django 2.2.6 on 2021-11-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0075_detallerequerimientoriegot_eto_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerequerimientoriegot',
            name='eto_real',
        ),
    ]
