# Generated by Django 2.2.6 on 2021-12-31 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0076_remove_detallerequerimientoriegot_eto_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='detrequerimientoriegofert',
            name='anexo_riego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleRiegoF', to='riego.DetalleRegistroRiegoFertilizacion'),
        ),
    ]
