# Generated by Django 2.2.6 on 2021-12-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0077_detrequerimientoriegofert_anexo_riego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detrequerimientoriegofert',
            name='anexo_riego',
        ),
        migrations.AddField(
            model_name='consumorequerimientoriegofert',
            name='anexo_riego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleRiegoF1', to='riego.DetalleRegistroRiegoFertilizacion'),
        ),
    ]
