# Generated by Django 2.2.6 on 2022-01-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0078_auto_20211231_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumorequerimientoriegofert',
            name='anexo_riego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleRiegoF1', to='riego.DetalleRequerimientoRiegot'),
        ),
    ]
