# Generated by Django 2.2.6 on 2022-03-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0187_programaproduccion_inicio_cosecha_clp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maestras', '0009_tanquesathos'),
        ('riego', '0079_auto_20220103_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolucionesMadres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('semana', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_fundo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSolucionesMadresFundo', to='menu.fundo')),
                ('anexo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSolucionesMadresZona', to='menu.ejezona')),
                ('numero_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoSolucionesMadresNumeroTanque', to='maestras.TanquesAthos')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionSolucionesMadres', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModSolucionesMadres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soluciones Madres',
                'verbose_name_plural': 'Soluciones Madres',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolucionesMadres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetSolucionesMadres', to='riego.SolucionesMadres')),
                ('anexo_fertilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoDetalleSolucionesMadres', to='riego.LeyNutricionRiego')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDetalleSolucionesMadres', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDetalleSolucionesMadres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Soluciones Madres',
                'verbose_name_plural': 'Detalle Soluciones Madres',
            },
        ),
    ]
