# Generated by Django 2.2.6 on 2022-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0080_detallesolucionesmadres_solucionesmadres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolucionesmadres',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
