# Generated by Django 2.2.6 on 2022-04-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0081_auto_20220316_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
