# Generated by Django 2.2.6 on 2022-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riego', '0082_auto_20220409_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproyeccionsemanalriego',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='detalleproyeccionsemanalriego',
            name='semana_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
