"""
Django settings for Athos project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2$g9204ig*0-cyx7r4d#4&%+gdg@#(w@kb4)8bu&%w%d6a-wvy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'apps.menu',
    'apps.show_items_menu',
    'apps.acopio',
    'apps.evaluaciones',
    'apps.prterminado',
    'apps.proyecciones',
    'apps.cgfenologias',
    'apps.maestras',
    'apps.logistica',
    'apps.sanidad',
    'apps.riego',
    'apps.acopio_athos.granada',
    'apps.acopio_athos.datil',
    'apps.acopio_athos.arandano',
    'apps.acopio_athos.higo',
    'apps.acopio_athos.aguaymanto',

    'apps.garita',
    'apps.planta.granada_planta',
    'apps.planta.higo_planta',
    'apps.programaproduccion',
    'apps.calidadagricola',
    'apps.topico',
    'apps.planificacion',
    'apps.rrhh',
    'apps.capacitaciones',
    'apps.controlgestion',
    'apps.planta.datil_planta',
    'apps.mantenimiento',

    'apps.api',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'Athos.urls'

TEMPLATES = [ #GUERRERO, ACA SE CAMBIA EL DIRS POR os.path.join(BASE_DIR,"templates") PARA QUE DJANGO SEPA DE DONDE SACAR LOS TEMPLATES
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Athos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'athos0',
        'USER': 'root',
        'PASSWORD': '',
        'HOST':'127.0.0.1',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'
TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = True

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
LOGIN_REDIRECT_URL = "/athos/"
SESSION_COOKIE_AGE = 43200
SESSION_SAVE_EVERY_REQUEST = True 
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
LOGOUT_REDIRECT_URL="/login/"
IMPORT_EXPORT_USE_TRANSACTIONS = True
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL="/media/"