# Generated by Django 2.2.6 on 2020-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedoresathos',
            name='ruc',
            field=models.IntegerField(verbose_name='RUC'),
        ),
    ]
