# Generated by Django 2.2.6 on 2020-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20201023_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedoresathos',
            name='ruc',
            field=models.BigIntegerField(verbose_name='RUC'),
        ),
    ]
