# Generated by Django 2.2.6 on 2020-10-24 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistica', '0003_auto_20201023_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLogistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='estados')),
            ],
            options={
                'verbose_name': 'Estado Logistica',
                'verbose_name_plural': 'Estado Logistica',
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='Monedas')),
            ],
            options={
                'verbose_name': 'Monedas',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=30, verbose_name='TipoOperacion')),
            ],
            options={
                'verbose_name': 'Tipo Operacion',
                'verbose_name_plural': 'Tipo Operacion',
            },
        ),
        migrations.CreateModel(
            name='CartillaProveedoresAthos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Factura')),
                ('orden', models.BigIntegerField(blank=True, null=True, verbose_name='Orden')),
                ('anticipo', models.BigIntegerField(blank=True, null=True, verbose_name='Anticipo')),
                ('fecha', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoEstadoProveedor', to='logistica.EstadoLogistica')),
                ('anexo_moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMonedasProveedor', to='logistica.Monedas')),
                ('anexo_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCartillaProveedor', to='logistica.ProveedoresAthos')),
                ('anexo_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoTOProveedor', to='logistica.TipoOperacion')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionCartillaProveedor', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModCartillaProveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartillas Proveedores Athos ',
                'verbose_name_plural': 'Cartillas Proveedores Athos',
            },
        ),
    ]
