# Generated by Django 2.2.6 on 2020-10-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0142_auto_20200916_1654'),
        ('logistica', '0004_cartillaproveedoresathos_estadologistica_monedas_tipooperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartillaproveedoresathos',
            name='anexo_centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoCentrosProveedor', to='menu.CentrosAthos'),
        ),
    ]
