# Generated by Django 2.2.6 on 2020-07-16 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.TextField(max_length=1000, verbose_name='Lectura Qr')),
                ('traza1', models.CharField(max_length=30, verbose_name='traza')),
                ('traza2', models.CharField(max_length=30, verbose_name='traza')),
                ('traza3', models.CharField(max_length=30, verbose_name='traza')),
                ('traza4', models.CharField(max_length=30, verbose_name='traza')),
                ('traza5', models.CharField(max_length=30, verbose_name='traza')),
                ('traza6', models.CharField(max_length=30, verbose_name='traza')),
                ('traza7', models.CharField(max_length=30, verbose_name='traza')),
                ('traza8', models.CharField(max_length=30, verbose_name='traza')),
                ('traza9', models.CharField(max_length=30, verbose_name='traza')),
                ('traza10', models.CharField(max_length=30, verbose_name='traza')),
                ('traza11', models.CharField(max_length=30, verbose_name='traza')),
                ('traza12', models.CharField(max_length=30, verbose_name='traza')),
                ('traza13', models.CharField(max_length=30, verbose_name='traza')),
                ('traza14', models.CharField(max_length=30, verbose_name='traza')),
                ('traza15', models.CharField(max_length=30, verbose_name='traza')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionPT', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModPT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Terminado',
                'verbose_name_plural': 'ModProducto Terminado',
            },
        ),
    ]
