# Generated by Django 2.2.6 on 2020-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prterminado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='traza1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza10',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza11',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza12',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza13',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza14',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza15',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza6',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza7',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza8',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='traza9',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='traza'),
        ),
    ]
